Repository intellij-rust/intellij-rust, pull requests merged in 2019-02, with the labels that each got.

#3323 ACT: Fix rustfmt install action
  src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
Labels: fix

#3334 INSP: correctly import item inside nested module
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#3336 ANN: Fix duplication of error messages from `cargo check`
  src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
Labels: fix

#3346 ANN: Save all documents before `cargo check`
  src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
Labels: fix

#3348 TYPE: support focus mode for Rust files
  src/191/main/kotlin/org/rust/ide/focusMode/RsFocusModeProvider.kt
  src/191/main/resources/META-INF/platform-plugin.xml
Labels: feature

#3350 ACT&INT: "show macro expansion" now shows error if macro failed to expand
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt
  src/main/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentions.kt
  src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
Labels: fix

#3353 TY: infer box expr `box Foo`
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: feature

#3355 ANN: Annotate the `box` keyword as experimental
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#3255 ANN: Irrefutable let patterns error
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#3330 INSP: make auto import works for path with type params
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#3363 RUN: save all documents before run any external process from run configuration
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsTestRunner.kt
Labels: fix

#3366 GRAM: Fix async fn recover
  src/main/grammars/RustParser.bnf
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.txt
Labels: fix

#3367 ANN: Annotate identifiers as reserved (Edition 2018) keywords only if they are name identifiers
  src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
Labels: fix

#3365 TY: more precise trait pick in type inference
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
Labels: fix

#3338 ACT: Allow a user to install Clippy from IDE
  src/main/kotlin/org/rust/cargo/runconfig/command/RunClippyAction.kt
  src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
  src/main/kotlin/org/rust/ide/actions/InstallComponentAction.kt
  src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
Labels: feature

#3371 Cleanup: use `when(val)` where possible
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
  src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
  src/main/kotlin/org/rust/ide/search/RsUsageTypeProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
  src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
Labels: internal

#3352 MACRO: expand macros in stmt context
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
Labels: internal

#3374 ANN: Fix irrefutability check for struct literals
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3359 PERF: use original element during completion if possible
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: internal

#3320 WIP: Fix exprs with never type processing in CFGBuilder
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: fix

#3356 TY: Supported box pattern (for struct fields)
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatField.kt
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
Labels: fix

#3376 ANN: Use cargo package in cargo check annotator
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
Labels: internal

#3364 COMP: add `dbg` postfix completion
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/resources/postfixTemplates/DbgPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/DbgPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/DbgPostfixTemplate/description.html
  src/test/kotlin/org/rust/ide/template/postfix/DbgPostfixTemplateTest.kt
Labels: feature

#3378 ANN: Non't show E0583 "File not found for module" if syntax error in declaration
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3381 TY: add adjustments for str inside binary expr
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: fix

#3373 COMP: support completion from index for enums
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
Labels: fix

#3388 MACRO: Allow custom macros with name "vec"
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#3382 ACT: add an action to enable/disable cargo check annotator
  src/main/kotlin/org/rust/ide/actions/ToggleCargoCheckAction.kt
  src/main/resources/META-INF/plugin.xml
Labels: feature

#3389 MACRO: Fix expansion of macros containing $crate metavar inside a group
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#3390 TY: enforce builtin binop operand types
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: internal

#3387 Fix extra line markers next to syntax errors
  src/main/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributor.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
Labels: fix

#3384 ACT: make "New | Rust File" action less cocky
  src/main/kotlin/org/rust/ide/actions/RsCreateFileAction.kt
Labels: fix

#3394 TY: Fix type inference in for/while let/if let exprs with complex patterns
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#3398 RUN: Apply `Offline mode` option not only to `cargo build` but also to `cargo check`
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
Labels: fix

#3392 ANN: Fix irrefutability check for tuple struct literals and nullary enum variants
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3380 ANN: Ability to pass arguments to cargo check annotator
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
  src/main/kotlin/org/rust/cargo/util/CargoCommandLineEditor.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
Labels: feature

#3407 GRD: update EAP IDEA & CLion
  gradle-191.properties
  src/191/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherTest.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsMethodLineSeparatorProvider.kt
Labels: internal

#3411 ANN: consider const pattern not irrefutable
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3375 INSP: Trait implementation inspection
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/inspectionDescriptions/RsTraitImplementation.html
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: feature

#3395 ANN: don't treat fns in wasm_bindgen extern block as unsafe
  src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
Labels: fix

#3306 ANN: annotate more precise ranges as unsafe operations
  src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionHighlightingAnnotatorTest.kt
Labels: fix

#3418 Process tuple parameters in `Add mut` quick-fix
  src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
  src/test/kotlin/org/rust/ide/inspections/fixes/AddMutableFixTest.kt
Labels: fix

#3369 T: fix completion performance test
  src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt
Labels: internal

#3299 REF: Make member inplace rename available for identifier owners
  src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
Labels: feature

#3425 COMP: add `.ref` and `.refm` postifx template
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/resources/postfixTemplates/RefPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/RefPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/RefPostfixTemplate/description.html
  src/main/resources/postfixTemplates/RefmPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/RefmPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/RefmPostfixTemplate/description.html
  src/test/kotlin/org/rust/ide/template/postfix/RefPostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/RefmPostfixTemplateTest.kt
Labels: feature

#3431 ANN: Fix saving documents in cargo check annotator
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotator.kt
Labels: fix

#3420 ACT: add `Reformat File with Rustfmt` to cargo toolwindow
  src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
  src/main/resources/META-INF/plugin.xml
Labels: feature

#3441 COMP: Add setting for "Suggest out of scope items" while completion
  .travis.yml
  gradle-183.properties
  src/main/kotlin/org/rust/ide/settings/RsCodeCompletionOptions.kt
  src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
Labels: feature

#3438 Refactor debugger pretty-printers
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  prettyPrinters/rust_types.py
Labels: internal

#3449 DBG: fix GDB pretty-printers for String and OsString
  prettyPrinters/gdb_providers.py
Labels: fix

#3450 TOML: icons for toml files
  intellij-toml/src/main/kotlin/org/toml/ide/icons/TomlIcons.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/ElementTypes.kt
  intellij-toml/src/main/resources/icons/toml-file.svg
  intellij-toml/src/main/resources/icons/toml-file_dark.svg
Labels: feature

#3451 Fix cache invalidation in language injections
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
Labels: fix, next-release

#3452 Fix trait selection cache pollution (was broken in 77016c72d7b20bf62d)
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
Labels: fix, next-release
