Repository intellij-rust/intellij-rust, pull requests merged in 2019-05, with the labels that each got.

#3778 INT: Implement "FlattenUseStatementsIntention"
  src/main/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/intentionDescriptions/FlattenUseStatementsIntention/after.rs.template
  src/main/resources/intentionDescriptions/FlattenUseStatementsIntention/before.rs.template
  src/main/resources/intentionDescriptions/FlattenUseStatementsIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt
Labels: feature

#3645 TY: better type inference for overloaded binops
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsArithmeticOpsTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#3794 ANN: Detect E0081: Duplicate enum discriminant
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#3799 TY: fix match ergonomics
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
Labels: fix

#3772 COMP: add `deref` postfix template
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/resources/postfixTemplates/DerefPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/DerefPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/DerefPostfixTemplate/description.html
  src/test/kotlin/org/rust/ide/template/postfix/DerefPostfixTemplateTest.kt
Labels: feature

#3789 ANN: Detect E0040: Explicit destructor call
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ReplaceWithStdMemDropFix.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceWithStdMemDropFixTest.kt
Labels: feature

#3768 RES: finally support unified paths (2018 edition)
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
Labels: fix

#3795 ANN: Detect E0120: impl Drop for Trait is illegal
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#3793 ACT: Added self parameter support to type declaration provider
  src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt
Labels: feature

#3624 Update nightly rust & compiler features
  .travis.yml
  src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: internal

#3770 PERF: use green stubs everywhere
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAssocTypeBinding.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBaseType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBinaryOp.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLifetime.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMembers.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPolybound.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsRefLikeType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsSelfParameter.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStructItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsValueParameter.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
Labels: internal

#3819 Implement ReadWriteAccessDetector
  src/main/kotlin/org/rust/ide/search/RsReadWriteAccessDetector.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/ide/search/RsReadWriteAccessDetectorTest.kt
Labels: feature

#3740 TYPE:fix matching brace deletion on backspace
  src/main/kotlin/org/rust/ide/typing/RsAttributeParenthesisHandlers.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/ide/typing/RsBraceMatcherTest.kt
Labels: fix

#3800 GRAM:fix 4 slashes doc comment error
  src/main/grammars/RustLexer.flex
  src/test/resources/org/rust/lang/core/lexer/fixtures/docCommentMerging.rs
  src/test/resources/org/rust/lang/core/lexer/fixtures/docCommentMerging.txt
Labels: fix

#3848 RUN: swap expected and actual values in test result diff
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestDiffTest.kt
Labels: fix

#3779 try to fetch stdlib from sysroot even without rustup
  src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
Labels: feature

#3806 Automatically detect "stdlib" when working with rust-lang/rust project
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#3862 Fix match check on complex patterns with multiple types
  src/main/kotlin/org/rust/ide/inspections/checkMatch/CheckMatchUtils.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsMatchCheckInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
Labels: fix

#3857 LI: fix doctests with existing "main" function
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/parser/util.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt
Labels: fix

#3871 RES: resolve extern crate items with alias in 2018 edition
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#3850 RES: ignore atom use items on 2018 edition
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Labels: fix

#3874 GRAM: Support `static` keyword for lambda expressions
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.txt
Labels: feature

#3875 INSP: Fix E0069 false positive
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3738 REF/INT:add refactoring to convert struct and its usages between block and tuple representation
  src/main/kotlin/org/rust/ide/refactoring/RsConvertToNamedFieldsAction.kt
  src/main/kotlin/org/rust/ide/refactoring/RsConvertToNamedFieldsProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldDecl.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferencesSearchExtensionImpl.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt
Labels: feature

#3753 PSI: Introduce RsCodeFragment
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentElementTypeBase.kt
  src/main/kotlin/org/rust/lang/core/psi/RsExprCodeFragmentElementType.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Labels: internal

#3866 TYPE:fix angle brace matching with macro call inside
  src/main/kotlin/org/rust/ide/typing/RsBraceMatcher.kt
  src/test/kotlin/org/rust/ide/typing/RsBraceMatcherTest.kt
Labels: fix

#3755 DBG: Use code fragment instead of plain text
  debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerEditorsExtension.kt
Labels: feature

#3873 Fix feature indexing
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsFeatureIndex.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3884 CARGO: set 2018 edition for std crates with latest rust versions
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Labels: fix

#3885 LI: fix crate attributes parsing in doctest
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
Labels: fix

#3887 REF: Fix parameters renaming in "Extract function"
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
Labels: fix

#3893 ANN: Highlight postfix `await` as a keyword
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
Labels: feature

#3901 T: Fix tests for RsAnsiEscapeDecoder on 192
  src/183/test/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoderTest.kt
  src/191/test/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoderTest.kt
  src/192/test/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoderTest.kt
Labels: internal

#3895 COMP: Add `await` to completion list if receiver's type is `impl Future`
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/Utils.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: feature

#3797 QDOC/LI: fixed block doc comments without infix in quickdoc and doctest
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocKind.kt
  src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/doc/RsDocRemoveDecorationTest.kt
Labels: fix

#3915 PROF: Get rid of RsPerfProfilerProcess on 2019.2
  clion/src/192/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/192/main/kotlin/org/rust/clion/profiler/perf/RsPerfProfilerProcess.kt
Labels: internal

#3911 REF: Extract RsFnInferenceContext into RsTypeInferenceWalker
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Labels: internal

#3918 PERF: filter traits by name before resolve in trait selection
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
Labels: internal

#3725 INT: `Add format string argument` intention
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentPopup.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/intentionDescriptions/AddFmtStringArgumentIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddFmtStringArgumentIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddFmtStringArgumentIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/AddFmtStringArgumentIntentionTest.kt
Labels: feature

#3881 TYPE:fix angle brace completion before brace
  src/main/kotlin/org/rust/ide/typing/RsAngleBraceHandlers.kt
  src/test/kotlin/org/rust/ide/typing/RsAngleBraceTypedHandlerTest.kt
Labels: fix

#3917 Make parameter info handler asynchronous
  src/main/kotlin/org/rust/ide/hints/RsAsyncParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/hints/RsParameterInfoHandler.kt
  src/test/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandlerTest.kt
  src/test/kotlin/org/rust/ide/hints/RsParameterInfoHandlerTest.kt
  src/test/kotlin/org/rust/ide/hints/RsParameterInfoHandlerTestBase.kt
Labels: fix

#3922 INSP: Don't check mutability of expr with unknown type
  src/main/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsReassignImmutableInspection.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/test/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/fixes/AddMutableFixTest.kt
Labels: fix
