Repository intellij-rust/intellij-rust, pull requests merged in 2019-09, with the labels that each got.

#3950 MACRO: support doc comments in macro calls
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/parser/util.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionRangeMappingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#4315 ANN: Improve error messages for E0023 and E0027
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#4343 ANN: fix false-positive E0026 on a struct pattern with a raw identifier
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatField.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#4323 INT: Handle trailing comma in ChopListIntention
  src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ListIntention.kt
  src/test/kotlin/org/rust/ide/intentions/ChopArgumentListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ChopFieldListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ChopParameterListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ChopVariantListIntentionTest.kt
Labels: fix

#4245 RUN: Add "Restart" and "Stop" buttons to Cargo build tool window
  clion/src/main/kotlin/org/rust/clion/cargo/CargoBuildConfigurationProvider.kt
  src/191/main/kotlin/org/rust/cargo/runconfig/buildtool/UtilsExtra.kt
  src/192/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
  src/192/main/kotlin/org/rust/cargo/runconfig/buildtool/UtilsExtra.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskProvider.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
Labels: feature

#4352 PERF&GRAM: micro-optimize parsing
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/fn.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/fn.txt
Labels: feature

#4357 PERF&GRAM: make macros lazy parseable & reparseable
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/macros/Matcher.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/LazyElements.kt
  src/main/kotlin/org/rust/lang/core/psi/MacroBraces.kt
  src/main/kotlin/org/rust/lang/core/psi/RsWithMacroExpansionsRecursiveElementWalkingVisitor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/openapiext/psi.kt
Labels: internal

#4359 QDOC: provide link to external documentation for non stdlib items
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt
Labels: feature

#4335 RES: take into account cfg attributes when collecting impls
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: internal

#4374 CARGO: fix NPE while parsing of rustc commit date
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/test/kotlin/org/rust/cargo/toolchain/RustcVersionParsingTest.kt
Labels: fix

#4353 ACT: Added Go to Implementations action for trait members
  src/main/kotlin/org/rust/ide/navigation/goto/RsImplsSearch.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
Labels: feature

#4376 TY: Fix type inference for await
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: fix

#4383 MACRO: check macro expansion depth during type inference
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt
Labels: fix

#4293 RUN: Always pass `--offline` / `-Zoffline` option to Cargo if "Offline mode" setting is enabled
  idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
  src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt
  src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
  src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
Labels: fix

#4336 COMP: do not add semicolons to other lines
  src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
  src/main/kotlin/org/rust/ide/typing/assist/SemicolonFixer.kt
  src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt
Labels: fix

#4396 TY: Support async and try blocks in lambdas
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: fix

#4127 REF:full rename support for struct pattern variable bindings
  src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#4405 ACT:better find usages for pattern bindings
  src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
  src/main/kotlin/org/rust/ide/search/RsUsageTypeProvider.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Labels: feature

#4411 Fix incompatibilities with latest 2019.3 EAPs
  gradle-193.properties
  src/191/main/kotlin/org/rust/lang/core/completion/CompletionUtilsExt.kt
  src/191/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
  src/192/main/kotlin/org/rust/lang/core/completion/CompletionUtilsExt.kt
  src/192/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
  src/193/main/kotlin/org/rust/lang/core/completion/CompletionUtilsExt.kt
  src/193/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDocCommentImplBase.kt
Labels: fix

#4012 REF: improved rename for mod.rs and directories
  src/main/kotlin/org/rust/ide/presentation/PresentationInfo.kt
  src/main/kotlin/org/rust/ide/presentation/RsDescriptionProvider.kt
  src/main/kotlin/org/rust/ide/refactoring/RsDirectoryRenameProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferencesSearchExtensionImpl.kt
  src/main/resources/META-INF/core.xml
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Labels: fix

#4427 Fix `Hash` trait autoimport on Rust nightly
  debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerTypesHelper.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/Pattern.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
Labels: fix

#4426 MACRO: better logs and try to recover on broken stub indices
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
Labels: internal

#4434 CI: init github actions
  .github/workflows/test-plugin.yml
Labels: internal

#4441 DOC: fix comments in the grammar
  src/main/grammars/RustParser.bnf
Labels: internal

#4454 GRAM: fix macro 2.0 parsing
  src/main/grammars/RustParser.bnf
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros_2.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros_2.txt
Labels: fix

#4403 INT: `Specify type explicitly` take into account type alias
  src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
Labels: feature

#4466 ACT: add `Create New Issue` to help menu
  src/main/resources/META-INF/core.xml
Labels: feature

#4463 T: enable error annotator for real project analysis test
  src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
Labels: internal

#4412 TYPE: Fix type hints navigation for alias
  src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
Labels: fix

#4464 PERF: fix AST switch in the hygiene
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: fix

#4178 DOC: document Cargo project model
  ARCHITECTURE.md
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
Labels: internal
