Repository intellij-rust/intellij-rust, pull requests merged in 2019-04, with the labels that each got.

#3015 Index macro expansions
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/navigation/goto/RsGeneratedSourcesFilter.kt
  src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
  src/main/kotlin/org/rust/ide/search/RsWithMacrosProjectScope.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/LazyStatic.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
  src/main/kotlin/org/rust/lang/core/macros/ReexpandMacrosAction.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/macros/RsIndexableSetContributor.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachesInvalidator.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionWritingAccessProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroCallIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsNamedElementIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
  src/main/kotlin/org/rust/openapiext/DelayedBackgroundableProcessIndicator.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/kotlin/org/rust/stdext/Collections.kt
  src/main/kotlin/org/rust/stdext/CompletableFuture.kt
  src/main/kotlin/org/rust/stdext/Concurrency.kt
  src/main/kotlin/org/rust/stdext/HashCode.kt
  src/main/kotlin/org/rust/stdext/path.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/ExpandMacros.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsPrimitiveTypeImplsTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt
Labels: feature

#3632 GRD: fix test running of non root modules
  build.gradle.kts
Labels: internal

#3634 Fix deadlock in new macro expansion engine
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/stdext/Concurrency.kt
Labels: fix

#3567 RES: Fix non-absolute std-qualified path resolution
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Labels: fix

#3626 ANN: Fix duplicate parameter name error
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3647 Revert "INT: Take into account defaulted type parameters during `Implement members`"
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#3643 RES&MACRO: Fix StackOverflow during macro resolve
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#3540 Add CLion's Valgrind support
  clion/src/191/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
  clion/src/191/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/191/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
  clion/src/191/main/kotlin/org/rust/clion/valgrind/RsValgrindRunner.kt
  clion/src/191/main/resources/META-INF/platform-clion-only.xml
  src/main/kotlin/org/rust/cargo/runconfig/CargoCommandConfigurationExtension.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsRunConfigurationExtensionManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt
Labels: feature

#3644 RUN: Fix MSVC toolchain detection on debug
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
Labels: fix

#3569 PRJ: Implement project settings migration via XML modification
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/SerializationUtils.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
Labels: internal

#3660 MACRO: disable code analysis during macro expansion
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: internal

#3663 COMP: Show local definitions in top of the completion list
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
Labels: feature

#3668 GRD: add more (default for IDEA) JVM options for runIde task
  build.gradle.kts
Labels: internal

#3669 MACRO: better consistency check
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: internal

#3666 PERF: slightly optimize PSI event processing
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
Labels: internal

#3656 DBG: Load Rust stdlib sources
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/test/kotlin/org/rust/RsTestBase.kt
Labels: feature

#3636 DBG: Add HashMap/HashSet formatter for lldb
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/hash_map.rs
Labels: feature

#3673 RUN: Line marker for test with `quickcheck` attribute
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
Labels: feature

#3674 COMP: Fix lookup element presentation and priority for tuple field decl
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
Labels: fix

#3676 (LEX,T): allow paired brackets inside RustDoc link text
  src/main/grammars/RustDocHighlightingLexer.flex
  src/test/resources/org/rust/lang/core/lexer/fixtures/highlighting/docLink.rs
  src/test/resources/org/rust/lang/core/lexer/fixtures/highlighting/docLink.txt
Labels: fix

#3693 PERF: don't invalidate caches when edition expression contains hardcoded macros
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
Labels: fix

#3695 COMP: fix #3694
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
Labels: fix

#3704 ACT: Fix AutoImportHintFix for single import-candidate case
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
Labels: fix

#3679 Find usages of the base declaration
  src/main/kotlin/org/rust/ide/search/RsFindUsagesHandler.kt
  src/main/kotlin/org/rust/ide/search/RsFindUsagesHandlerFactory.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Labels: feature

#3719 Fix ClassCastException in derefRefPathFromActualToExpected
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
Labels: fix

#3724 ANN: Check if project is not disposed before setting highlights from external linter to editor
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
Labels: fix

#3727 Commit document before optimize imports
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
Labels: fix

#3718 ANN: Use `lenient` JSON parser mode for messages from external linter
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
Labels: fix

#3732 Move settings from `misc.xml` to `workspace.xml`
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: fix

#3627 INT & TYPE: Force user to fill initializers for generated fields
  src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt
  src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
  src/main/kotlin/org/rust/openapiext/Template.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
Labels: feature

#3734 RUN: Test runner correctly handles multiple targets with the same name
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
Labels: fix

#3699 RES&ANN: fix restricted visibility for mod
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#3743 INSP: filter out redundant auto import candidates better
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#3726 Mark as excluded workspace `target` dir
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt
Labels: fix

#3705 PERF&MACRO: optimize `getExpandedFrom`
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
Labels: fix

#3744 PERF: slightly optimize name resolution (better cache)
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt
Labels: fix

#3519 ACT: add context menu action to create a new Cargo (sub)crate
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt
  src/main/kotlin/org/rust/ide/actions/ui/CargoNewCrateDialog.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/ide/actions/RsCreateCrateActionTest.kt
Labels: feature

#3754 COMP: fix completion after tuple field expr
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#3687 DBG: Add HashMap/HashSet formatter for gdb
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  pretty_printers_tests/tests/hash_map.rs
Labels: feature

#3715 DBG: add support for printing Enums directly in debugger
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/enum.rs
Labels: feature

#3760 GRD: General improvements
  build.gradle.kts
Labels: internal

#3520 INT: add support for smart pointers, Default implementation, struct init shorthand and local variable to Add struct fields fix
  src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
  src/main/kotlin/org/rust/ide/inspections/RsFieldInitShorthandInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
Labels: fix

#3769 RES: fix disambiguating primitive type qualified paths
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix
