Repository intellij-rust/intellij-rust, pull requests merged in 2019-07, with the labels that each got.

#4064 ANN: add "Create field" quick fix for "No such field" error
  src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFixTest.kt
Labels: feature

#4082 PERF:make lexer incremental
  src/main/grammars/RustLexer.flex
  src/test/kotlin/org/rust/lang/core/lexer/RsRestartLexingTestCase.kt
Labels: internal

#3792 MACRO&RES: delegate references from macro call bodies to expansions
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
  src/main/kotlin/org/rust/ide/search/RsUsageTypeProvider.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBinding.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBodyIdent.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBodyQuoteIdent.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsReferenceElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeReference.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroBodyReferenceDelegateImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceBase.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/attributes.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impls.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/patterns.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/type.txt
Labels: feature

#4056 INT: Fix creation of new module if no corresponding directory exists
  src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#4101 INT: Fix `Make public fix` for mod decl
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
Labels: fix

#3991 INT:make convert struct refactorings available as intentions
  src/main/kotlin/org/rust/ide/intentions/ConvertStructIntentions.kt
  src/main/kotlin/org/rust/ide/refactoring/RsBaseEditorRefactoringAction.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/intentionDescriptions/ConvertToStructIntention/after.rs.template
  src/main/resources/intentionDescriptions/ConvertToStructIntention/before.rs.template
  src/main/resources/intentionDescriptions/ConvertToStructIntention/description.html
  src/main/resources/intentionDescriptions/ConvertToTupleIntention/after.rs.template
  src/main/resources/intentionDescriptions/ConvertToTupleIntention/before.rs.template
  src/main/resources/intentionDescriptions/ConvertToTupleIntention/description.html
Labels: feature

#4060 COMP&MACRO: advanced completion inside macro call bodies
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsFullMacroArgumentCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/Utils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/test/kotlin/org/rust/lang/core/completion/RsMacroCallBodyCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
Labels: feature

#4010 Fix never type processing in CFGBuilder
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: fix

#4114 Fix an infinite recursion around getBounds
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
Labels: fix

#4124 TY: Don't throw exception on unbounded inclusive range
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Labels: fix

#4046 Fix slice destructing processing in borrowck
  src/main/kotlin/org/rust/lang/core/types/borrowck/BorrowChecker.kt
  src/main/kotlin/org/rust/lang/core/types/borrowck/CheckLoans.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: fix

#4022 INSP:added inspection for dyn keyword for trait objects
  src/main/kotlin/org/rust/ide/inspections/RsTraitObjectInspection.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitType.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/inspectionDescriptions/RsTraitObject.html
  src/test/kotlin/org/rust/ide/inspections/RsTraitObjectInspectionTest.kt
Labels: feature

#4108 INT: intention to convert impl Trait to type parameter
  src/main/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntention.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/intentionDescriptions/ImplTraitToTypeParamIntention/after.rs.template
  src/main/resources/intentionDescriptions/ImplTraitToTypeParamIntention/before.rs.template
  src/main/resources/intentionDescriptions/ImplTraitToTypeParamIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntentionTest.kt
Labels: feature

#4047 Fix struct pat processing in borrowck
  src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: fix

#4070 ANN: improve autoimport with UFCS & associated items
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#4090 RUN: Add setting to emulate the terminal on Unix
  src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/BenchRunConfigurationProducerTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/ExecutableRunConfigurationProducerTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench configuration uses default environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench fn is more specific than main or test mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer adds bin name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer ignores selected files that contain no benches.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer uses complete function path.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for annotated functions.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for benches source root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for directories inside benches source root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for module declarations.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for modules.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for multiple files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for nested modules 1.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for nested modules 2.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for root module.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable configuration uses default environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable producer works for bin.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable producer works for example.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ hyphen in name works.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main fn is more specific than bench fn.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main fn is more specific than bench mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main fn is more specific than test fn.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main fn is more specific than test mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main mod is more specific than test mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ meaningful bench configuration name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ meaningful test configuration name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ take into account path attribute.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test configuration uses default environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test fn is more specific than main mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test mod decl is more specific than main mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test mod is more specific than bench mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer adds bin name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer ignores selected files that contain no tests.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer uses complete function path.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for annotated functions.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for directories inside tests source root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for module declarations.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for modules.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for multiple files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for nested modules 1.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for nested modules 2.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for project root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for root module.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for tests source root.xml
Labels: feature

#4099 MACRO: fix macro with arguments defined with another macro
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#4145 ACT: add new line after code snippet
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
Labels: fix

#3979 ANN: Detect E0267, E0268: break/continue used outside of loop
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBreakExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsContExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLabelReferenceOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLooplikeExpr.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#4140 ANN: detect invalid usages of `impl Trait`(E0562, E0666, E0667)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#4154 T: improve `MinRustcVersion` annotation
  src/test/kotlin/org/rust/MinRustcVersion.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
  src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Labels: internal

#4148 ANN: Fix E0618: Type implementing a Fn trait is a function too
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#4136 T: Extract performance and real project tests to rustPerformanceTests
  .idea/runConfigurations/Test_Performance.xml
  .travis.yml
  appveyor.yml
  build.gradle.kts
  src/test/kotlin/org/rustPerformanceTests/RsCompletionPerformanceTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerformanceTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsRealProjectTestBase.kt
Labels: internal

#3618 RUN: Support code coverage via grcov
  CONTRIBUTING.md
  build.gradle.kts
  coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
  coverage/src/main/kotlin/org/rust/coverage/LcovCoverageReport.kt
  coverage/src/main/kotlin/org/rust/coverage/RsCoverageAnnotator.kt
  coverage/src/main/kotlin/org/rust/coverage/RsCoverageEnabledConfiguration.kt
  coverage/src/main/kotlin/org/rust/coverage/RsCoverageEngine.kt
  coverage/src/main/kotlin/org/rust/coverage/RsCoverageRunner.kt
  coverage/src/main/kotlin/org/rust/coverage/RsCoverageSuite.kt
  coverage/src/main/resources/META-INF/coverage-only.xml
  settings.gradle
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/Grcov.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/main/resources/META-INF/plugin.xml
Labels: feature

#4157 TY: Fix inference of full RsPatField and RsPatWild
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Labels: fix

#4160 Fix comment processing in RsStatementUpDownMover
  src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt
  src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt
Labels: fix

#4156 Pretty-printers for GDB: Disable EnumProvider in case of invalid discriminant
  prettyPrinters/gdb_lookup.py
Labels: fix

#4158 INSP: Fix PatField sorting in RsMatchCheckInspection
  src/main/kotlin/org/rust/ide/inspections/checkMatch/CheckMatchUtils.kt
  src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
Labels: fix

#4162 Fix #3544 crash in type inference
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFix.kt
  src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/utils/CargoProjectCache.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/kotlin/org/rust/stdext/Cache.kt
Labels: fix

#4175 INSP: Don't warn about missing 'dyn' for Self
  src/main/kotlin/org/rust/ide/inspections/RsImplicitTraitObjectInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsImplicitTraitObjectInspectionTest.kt
Labels: fix

#4177 INSP: fix auto import inside pub inline module
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
Labels: fix

#4181 PERF: optimize very hot `getExpandedFrom` method
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: fix

#4183 PERF&STUB: stub flag that function has a self parameter (i.e. is method)
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
Labels: fix

#4182 PERF: introduce `RsCachedImplItem`
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Labels: fix

#4141 Pretty-printers for GDB: Update BTreeMap/BTreeSet
  prettyPrinters/gdb_providers.py
  pretty_printers_tests/tests/btree.rs
Labels: fix

#4202 RES: Take into account namespaces when resolving const generics
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
Labels: fix
