Repository intellij-rust/intellij-rust, pull requests merged in 2019-10, with the labels that each got.

#4484 RES: fix cfg inside macros
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: internal

#4478 GRAM: support associated type bounds (RFC 2289)
  src/main/grammars/RustParser.bnf
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/polybounds.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/polybounds.txt
Labels: feature

#4488 Enable cfg attributes support on nightly
  src/main/resources-nightly/META-INF/experiments.xml
Labels: feature

#4490 PERF&MACRO: cancellable extraction step (better editor responsiveness)
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: fix

#4504 ACT: fix IllegalStateException in `Attach` action
  src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
Labels: fix

#4487 PERF: fix index access during PSI event processing
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModificationTrackerOwner.kt
Labels: fix

#4486 Fix copying text from a Cargo project tree
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectTreeStructure.kt
  src/test/kotlin/org/rustSlowTests/CargoProjectStructureTest.kt
Labels: fix

#2651 WIP display items expanded from macros in structure view
  src/main/kotlin/org/rust/ide/colors/RsColors.kt
  src/main/kotlin/org/rust/ide/presentation/Utils.kt
  src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/resources/org/rust/ide/colors/RustDarcula.xml
  src/main/resources/org/rust/ide/colors/RustDefault.xml
Labels: feature

#4479 ACT: Support `Analyze Stack Trace` action
  src/main/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilter.kt
  src/main/resources/META-INF/core.xml
  src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt
Labels: feature

#4523 CARGO: improve rendering of external libraries
  src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
Labels: feature

#4536 RUN: don't show tool window if "Activate tool window" option is disabled
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt
Labels: bug

#4537 Enable cfg attributes support on stable
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature, to be documented

#4491 GRAM&REF&PERF: rework macro calls parsing
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/RsWithMacroExpansionsRecursiveElementWalkingVisitor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/openapiext/psi.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/shifts.txt
Labels: feature

#4545 GRAM: parse use group paths start with `crate` and `super` correctly
  src/main/grammars/RustParser.bnf
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/use_item.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/use_item.txt
Labels: bug

#4538 Fix cfg on nested macros
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: fix

#4553 QDOC: render `async` keyword for async functions in quick doc
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
Labels: fix

#4513 ACT: Take into account async keyword when implementing missing fn
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#4480 UI: Show trait/impl in usage tooltip
  src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
  src/main/kotlin/org/rust/ide/search/RsTraitOrImplGroupingRuleProvider.kt
  src/main/resources/META-INF/core.xml
Labels: feature

#4522 MACRO: rework macro-to-expansion linkage
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiTreeChangeListener.kt
  src/main/kotlin/org/rust/openapiext/Testmark.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
Labels: fix
