Repository intellij-rust/intellij-rust, pull requests merged in 2019-11, with the labels that each got.

#4581 RUN: Enable Code Coverage for CLion (+193)
  README.md
  coverage/src/test/resources/META-INF/plugin.xml
  plugin/src/main/resources/META-INF/plugin.xml
Labels: feature

#4485 TYPE & STUB: Render RsValueParameter without mutability
  src/main/kotlin/org/rust/lang/core/psi/ext/RsValueParameter.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
  src/test/kotlin/org/rust/ide/hints/RsParameterInfoHandlerTest.kt
Labels: fix

#4600 INSP: Ignore `Self` identifier in RsDeprecationInspection
  src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsDeprecationInspectionTest.kt
Labels: fix

#4597 RES: ignore impls with unresolved trait in name resolution
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
Labels: fix

#4555 RUN & INSP: Fix file path in messages from rustc
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Labels: fix

#4596 INSP: improve typecheck to detect mismatches of partially unknown types
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
Labels: fix

#4606 RES: fix impls selection for impl Trait when impl is inside a macro
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Labels: fix

#4598 Use default formatting settings from kotlin official style guide
  .idea/codeStyles/Project.xml
  gradle.properties
Labels: internal

#4621 Fix #4613
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
Labels: fix

#4332 INT: add "Put struct literal fields on separate lines/one line" intention
  src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
  src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ListIntention.kt
  src/main/resources/META-INF/core.xml
  src/main/resources/intentionDescriptions/ChopLiteralFieldListIntention/after.rs.template
  src/main/resources/intentionDescriptions/ChopLiteralFieldListIntention/before.rs.template
  src/main/resources/intentionDescriptions/ChopLiteralFieldListIntention/description.html
  src/main/resources/intentionDescriptions/JoinLiteralFieldListIntention/after.rs.template
  src/main/resources/intentionDescriptions/JoinLiteralFieldListIntention/before.rs.template
  src/main/resources/intentionDescriptions/JoinLiteralFieldListIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ChopLiteralFieldListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/JoinLiteralFieldListIntentionTest.kt
Labels: feature

#4644 Fix #4639 IllegalStateException in `RsSmartEnterProcessor`
  src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
Labels: fix

#4638 RUN & INSP: Fix error span in rustc messages if the error comes from macro expansion
  src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Labels: fix

#4642 MACRO: fix re-highlighting after a macro call change (new engine)
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: fix

#4655 Disable `#[cfg(test)]` in stdlib
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
Labels: fix

#4662 Revert "Use default formatting settings from kotlin official style guide"
  .idea/codeStyles/Project.xml
  gradle.properties
Labels: internal

#4665 Fix infinite non-fading progress bar during macro expansion
  src/main/kotlin/org/rust/openapiext/DelayedBackgroundableProcessIndicator.kt
Labels: fix

#4673 Add support of `Grazie` plugin
  CONTRIBUTING.md
  build.gradle.kts
  gradle-192.properties
  gradle-193.properties
  grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt
  grazie/src/main/resources/META-INF/grazie-only.xml
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
  grazie/src/test/resources/META-INF/plugin.xml
  plugin/src/main/resources/META-INF/plugin.xml
  settings.gradle.kts
  src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestFixture.kt
  src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt
Labels: feature

#4659 GRAM&MACRO: recover parser on macros with unbalanced braces
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/parser/util.kt
  src/main/kotlin/org/rust/lang/core/psi/MacroBraces.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/macros.txt
Labels: fix

#4676 ACT:Display impl block info in Go to Imlementations dialog
  src/main/kotlin/org/rust/ide/navigation/goto/RsGotoTargetRendererProvider.kt
Labels: feature

#4670 ANN: Detect invalid default type parameter usage
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Labels: feature

#4688 TY: skip impls with `rustc_reservation_impl` attribute while type inference
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
Labels: fix

#4694 MACRO: fix matching `$($ e:expr,)+` group
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#4695 MACRO: place even less parens around exprs
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
Labels: fix

#4698 RUN: Show cached compilation warnings in Build Tool Window
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt
Labels: fix

#4687 Fix control flow of some elements
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: feature

#4690 Consider expanded macros in control flow and borrow checker
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: feature
