Repository intellij-rust/intellij-rust, pull requests merged in 2019-08, with the labels that each got.

#4206 COMP: Const keyword completion for const generics
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: feature

#4213 Fix #4212 Error while indexing (RsExternCrateReexportIndex)
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsExternCrateReexportIndex.kt
Labels: fix

#4195 COMP: Assoc functions have higher priority than methods
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
Labels: feature

#4190 REF&PERF: better cache cargo target for files
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
Labels: fix

#4210 PERF: reduce PSI tree access in very hot item resolution
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoBenchRunConfigurationProducer.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
Labels: fix

#4226 Fix items resoution from prelude on the nightly Rust
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
Labels: fix

#4229 TYPE: improve `deref` postfix completion description & example
  src/main/resources/postfixTemplates/DerefPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/DerefPostfixTemplate/description.html
Labels: fix

#4197 DBG: Load pretty-printers and rustc sources via RsDebugProcessConfigurator
  debugger/src/191/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
  debugger/src/191/main/resources/META-INF/platform-debugger-only.xml
  debugger/src/192/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurator.kt
  debugger/src/192/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
  debugger/src/192/main/resources/META-INF/platform-debugger-only.xml
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunParameters.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
  debugger/src/main/resources/META-INF/debugger-only.xml
  prettyPrinters/rust_types.py
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
Labels: feature

#4253 RUN: Ignore `-q` option if using new build toolwindow
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
Labels: fix

#4251 GRAM: Fix parsing of nested async functions
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.txt
Labels: fix

#4255 COMP: bold text for keyword completion element
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
Labels: fix

#4135 Process break/continue in CFG and dataflow
  src/main/kotlin/org/rust/lang/core/DataFlow.kt
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLabeledExpression.kt
  src/main/kotlin/org/rust/lang/core/types/borrowck/BorrowChecker.kt
  src/main/kotlin/org/rust/lang/core/types/regions/Scope.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: fix

#4257 RUN: Fix Build action when build toolwindow is disabled
  src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt
Labels: fix

#4266 RUN: Show executed command line in build tool window
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
Labels: fix

#4252 COMP: keyword completion in trait and impl items
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: feature

#4250 COMP: move caret insice '()' after method completion in UFCS
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#4269 RUN: Fix integration test debugging
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
Labels: fix

#4203 Usages tooltip scope
  src/main/kotlin/org/rust/ide/search/RsFunctionGroupingRuleProvider.kt
  src/main/resources/META-INF/core.xml
Labels: feature

#3996 INT & ANN: Implement intention and fix for struct fields expansion instead of `..`
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsPatFix.kt
  src/main/kotlin/org/rust/ide/intentions/AddStructFieldsPatIntention.kt
  src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/core.xml
  src/main/resources/intentionDescriptions/AddStructFieldsPatIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddStructFieldsPatIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddStructFieldsPatIntention/description.html
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsPatFixTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddStructFieldsPatIntentionTest.kt
Labels: feature

#4094 TY&RES: implement hygiene & infer types in macros
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
  src/main/kotlin/org/rust/lang/core/psi/RsWithMacroExpansionsRecursiveElementWalkingVisitor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStmt.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroBodyReferenceDelegateImpl.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/openapiext/psi.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Labels: feature

#4243 Show type alias names in type hints for TyAdt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
  src/test/kotlin/org/rust/lang/core/type/RsShortTypeRenderingTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: feature

#4280 RUN: Debug runner correctly checks toolchain on Windows
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
Labels: fix

#4290 Fix declaration fields escaping and underscores in struct patterns
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#4259 RUN: Fix exception in "Run/Debug Configurations" menu
  src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt
Labels: fix

#4296 RUN: Fix parsing option arguments
  src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt
Labels: fix

#4298 Revert: Use `--installed` flag and `--toolchain` option in `listComponents`
  src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
Labels: fix

#4278 TY: fix expression type arguments with defaults
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#4301 INT: add "Put fields on separate lines/one line" intentions
  src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
  src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
  src/main/resources/META-INF/core.xml
  src/main/resources/intentionDescriptions/ChopFieldListIntention/after.rs.template
  src/main/resources/intentionDescriptions/ChopFieldListIntention/before.rs.template
  src/main/resources/intentionDescriptions/ChopFieldListIntention/description.html
  src/main/resources/intentionDescriptions/JoinFieldListIntention/after.rs.template
  src/main/resources/intentionDescriptions/JoinFieldListIntention/before.rs.template
  src/main/resources/intentionDescriptions/JoinFieldListIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ChopFieldListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/JoinFieldListIntentionTest.kt
Labels: feature

#4304 INT: add "Put variants on separate lines/one line" intentions
  src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
  src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
  src/main/resources/META-INF/core.xml
  src/main/resources/intentionDescriptions/ChopVariantListIntention/after.rs.template
  src/main/resources/intentionDescriptions/ChopVariantListIntention/before.rs.template
  src/main/resources/intentionDescriptions/ChopVariantListIntention/description.html
  src/main/resources/intentionDescriptions/JoinVariantListIntention/after.rs.template
  src/main/resources/intentionDescriptions/JoinVariantListIntention/before.rs.template
  src/main/resources/intentionDescriptions/JoinVariantListIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ChopVariantListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/JoinVariantListIntentionTest.kt
Labels: feature

#4297 INT: Implement struct literal fields expansion
  src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
  src/main/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralIntention.kt
  src/main/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralRecursiveIntention.kt
  src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt
  src/main/resources/META-INF/core.xml
  src/main/resources/intentionDescriptions/AddStructFieldsLiteralIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddStructFieldsLiteralIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddStructFieldsLiteralIntention/description.html
  src/main/resources/intentionDescriptions/AddStructFieldsLiteralRecursiveIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddStructFieldsLiteralRecursiveIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddStructFieldsLiteralRecursiveIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralRecursiveTest.kt
Labels: feature

#4272 RUN: Fix parsing executable file path when debugging tests
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
Labels: fix

#4320 Wrap some VFS usages into read actions
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
Labels: fix

#4324 RES: enable all cfg features by default
  src/main/kotlin/org/rust/cargo/CfgOptions.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
Labels: internal

#4168 RES: fix re-exported crate via use item on 2018 edition
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#3750 Support `#[macro_export(local_inner_macros)]`
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
Labels: feature

#4150 Bugfix/arbitrary self types#4138
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#4330 TY: fix random type inference fails caused by STUB usage instead of AST
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt
Labels: fix

#4139 RUN: enable --show-output when executing tests
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustChannel.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/test/kotlin/org/rust/cargo/runconfig/CargoTestRunStateTest.kt
Labels: feature
