Repository intellij-rust/intellij-rust, pull requests merged in 2019-12, with the labels that each got.

#4715 INT: don't suggest "Put parameters/arguments/fields/variants on separate lines/one line" if comments are present
  src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
  src/test/kotlin/org/rust/ide/intentions/JoinArgumentListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/JoinFieldListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/JoinLiteralFieldListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/JoinParameterListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/JoinVariantListIntentionTest.kt
Labels: fix

#4619 Allow to manually select arguments
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/ExtractFunctionParameterTablePanel.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: feature

#4726 Introduce `childOfType` method for PsiElement
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
Labels: internal

#4415 ANN: Better detection of duplicate imports/items E0252
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#4671 INT: Fixed move type constraints intentions for default type parameters
  src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToWhereClauseIntentionTest.kt
Labels: fix

#4689 MACRO: Fix full re-expand when showing macro expansion
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
Labels: fix

#4482 ANN: Support `unstable` attribute for items
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#4724 GRAM: Fix underscore constants parsing
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/constants.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/constants.txt
Labels: fix

#4735 INT: improve "specify type explicitly" intention
  src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
  src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
Labels: fix

#4769 RES: fix pattern namespaces
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsNamespaceResolveTest.kt
Labels: fix

#4784 PSI: Rename code fragments consistently
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentElementType.kt
Labels: internal

#4798 TOML: fix crate doc links in toml
  toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
  toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
Labels: fix

#4785 TY: fixed type inference for Fn type parameter with multiple bounds
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: fix

#4805 INT: do not suggest "Lift return out" on 'if' in 'else' branch
  src/main/kotlin/org/rust/ide/inspections/RsLiftInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt
Labels: fix

#4776 ANN: fix false-positive E0277
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix
