Repository intellij-rust/intellij-rust, pull requests merged in 2019-06, with the labels that each got.

#3937 Fix expression type provider multiselect
  src/main/kotlin/org/rust/ide/hints/RsExpressionTypeProvider.kt
Labels: fix

#3939 REF: drop `advancedMultiResolve()`, don't use `instantiatePathGenerics()` if multiresolved
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReference.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
Labels: internal

#3823 ANN: Detect E0084: Enum with no variants can't have repr attribute
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/RemoveAttrFix.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAttr.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveAttrFixTest.kt
Labels: feature

#3931 Fix ReadWriteAccessDetector struct literal
  src/main/kotlin/org/rust/ide/search/RsReadWriteAccessDetector.kt
  src/test/kotlin/org/rust/ide/search/RsReadWriteAccessDetectorTest.kt
Labels: fix

#3933 TY: fix never type unification
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
Labels: fix

#3941 RUN: Fix parsing target name in debug
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
Labels: fix

#3920 REF:added refactoring to convert tuple to struct
  src/main/kotlin/org/rust/ide/refactoring/RsBaseEditorRefactoringAction.kt
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsAction.kt
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToTupleAction.kt
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToTupleProcessor.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsConvertToNamedFieldsActionTest.kt
Labels: feature

#3803 ANN: Detect E0518: Inline attribute is allowed only on functions
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveAttrFixTest.kt
Labels: feature

#3932 TY: fix find free impls for type parameter
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
Labels: fix

#3825 ANN: Detect E0118: Can impl only `struct`s, `enum`s and `union`s
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
Labels: feature

#3930 TY: fix closure type inference with "impl Trait" parameters
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsClosuresResolveTest.kt
Labels: fix

#3878 PERF: optimize method completion
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
Labels: internal

#3913 RES: Fix unified path & star import priorities
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#3947 TOML: Support dot keys
  .idea/runConfigurations/Generate_Parser.xml
  intellij-toml/src/main/grammars/TomlParser.bnf
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.toml
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/tables.txt
Labels: feature

#3945 MACRO: better progress fraction calculation during macro expansion
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: fix

#3951 ANN: fix trait members visibility (false-positive E0603)
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#3956 Fix possible crash in type inference
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Labels: fix

#3967 Fix #3966 Error during macro expansion
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: fix

#3969 Fix #3891 Non-idempotent computation in RsMacroIndex
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
Labels: fix

#3954 LI: don't inject doctests in targets with `doctest=false` in Cargo.toml
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
  src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
Labels: fix

#3971 INSP: fix autoimport on 2018 edition
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#3953 RUN: Fix synchronous execution on EDT in `computeSysroot`
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
Labels: internal

#3980 ANN: Detect E0322, E0328: Explicit impl for sized and unsize trait
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#3952 DBG: Use RsCodeFragment for gdb/lldb console injection
  debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt
  debugger/src/main/resources/META-INF/debugger-only.xml
  src/main/kotlin/org/rust/lang/RsDebugInjectionListener.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
Labels: fix

#3986 TY&RES: fix UFCS-like assoc types resolve (`Iterator.take()`)
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#3898 TYPE:fixed exit points highlighting
  src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
  src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
  src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
Labels: fix

#3990 GRAM: Parse const generics
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/ext/RsContsParameter.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/const_generics.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/const_generics.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/no_lifetime_bounds_in_generic_args.txt
Labels: feature

#3997 RES: fix issue #3989
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
Labels: fix

#3993 COMP & RES: Resolve const generics
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: feature

#4004 TY: Take into account const parameter type
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: feature

#4028 ANN: Highlight const generics
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/colors/RsColors.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
Labels: feature

#4023 RES: fix duplicating definitions for `use` with bang proc macros
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#4029 ANN: Fix E0118 false positive
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
Labels: fix

#4040 TY: fix `type S<T> = T;` case
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: fix

#3832 ANN: Detect E0132: Invalid `#[start]` function
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#4034 TY: fix default type parameters
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#4045 INT: Handle format macros with destinations in AddFmtStringArgument
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt
  src/test/kotlin/org/rust/ide/intentions/AddFmtStringArgumentIntentionTest.kt
Labels: fix

#3946 QFIX: Add option to create a mod file in a subdirectory
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#4050 PRJ: Make creation of the project automatically open generated files
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
Labels: feature

#4055 MACRO&RES: resolve attribute and custom derive proc macros to their defenitions
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMetaItemReferenceContributor.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: feature
