Repository intellij-rust/intellij-rust, pull requests merged in 2019-03, with the labels that each got.

#3432 ANN: Cache cargo check result
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotationInfo.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotatorPass.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
Labels: fix, next-release

#3466 CLEAN: Get rid of `RsCargoCheckAnnotator`
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotationInfo.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotationResult.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotatorPass.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckFilteredMessage.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckUtils.kt
  src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorPassTest.kt
Labels: internal

#3464 COMP: generalize "Add trait imports" setting
  src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
  src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsTraitMethodCompletionTest.kt
Labels: next-release

#3144 LI: inject Rust language to doctests
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/ide/actions/RsEnterHandler.kt
  src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/ide/injected/RsSimpleMultiLineEscaper.kt
  src/main/kotlin/org/rust/ide/injected/RsStringLiteralEscaper.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/typing/RsEnterInLineCommentHandler.kt
  src/main/kotlin/org/rust/lang/core/RsASTFactory.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
Labels: feature, next-release

#3476 Process orPats during CFG building
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: feature, next-release

#3478 Fixed SpecializedAssertQuickFix produced incorrect PSI
  src/main/kotlin/org/rust/ide/inspections/RsAssertEqualInspection.kt
Labels: fix

#3482 Negate `condition.expr` inside "Invert if" intention
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
Labels: fix

#3484 Fix exception on renaming
  src/main/kotlin/org/rust/lang/core/psi/RsPsiTreeChangeListener.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Labels: bug

#3467 ANN: Cancel cargo check process on any PSI change
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotatorPass.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckUtils.kt
Labels: fix

#3489 PSI: `ContributedReferenceHost` for `RsLitExp`
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
Labels: internal

#3415 INSP & ACT: Add cargo check inspection and run cargo check action
  src/main/kotlin/org/rust/ide/actions/RsRunCargoCheckAction.kt
  src/main/kotlin/org/rust/ide/inspections/RsCargoCheckInspection.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/inspectionDescriptions/RsCargoCheck.html
Labels: feature

#3439 RUN: Disable the "Use cargo check when build project" option by default
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
Labels: fix

#3473 INT: Take into account defaulted type parameters during `Implement members`
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#3459 CARGO: don't try to setup cargo package module roots if project is already disposed
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#3460 Support crate and pub(in path) restricted visibility
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/refactoring/RsConvertToNamedFieldsAction.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumVariant.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedFieldDecl.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStructItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTupleFieldDecl.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#3498 QDOC: correct doc urls for primitive and primitive methods
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt
Labels: fix

#3501 INT: Make "unelide lifetimes" intention unavailable in doc comments
  src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
  src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
Labels: fix

#3503 INT: handle conversion of module to self in nest use intention
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
  src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
Labels: fix

#3500 GRAM: fix macro_rules pin
  src/main/grammars/RustParser.bnf
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
Labels: fix

#3485 Provide binary compatible API for Rust project settings
  idea/src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/ide/actions/ToggleCargoCheckAction.kt
  src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
  src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorPassTest.kt
Labels: internal

#3513 CARGO: log `JsonSyntaxException` exception
  src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt
Labels: internal

#3419 T: test our analysis on real rust projects
  src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt
  src/test/kotlin/org/rustSlowTests/RsRealProjectAnalysisTest.kt
  src/test/kotlin/org/rustSlowTests/RsRealProjectTestBase.kt
Labels: internal

#3525 REF: Don't rename tuple fields
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
Labels: fix

#3526 ANN: Remove all cargo check annotations if annotator is disabled
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotatorPass.kt
Labels: fix

#3527 RUN: Destroy external annotator on process cancellation
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotatorPass.kt
  src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckUtils.kt
  src/main/kotlin/org/rust/ide/inspections/RsCargoCheckInspection.kt
  src/main/kotlin/org/rust/openapiext/CommandLineExt.kt
Labels: fix

#3528 GRAM: add support for unnamed use alias (use item as _)
  src/main/grammars/RustParser.bnf
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/use_item.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/use_item.txt
Labels: feature

#3518 COMP: provide primitive type completion
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionTest.kt
Labels: feature

#3496 INSP: Rerun cargo check inspection on any PSI change
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
Labels: fix

#3533 MACRO: support `?`-groups
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#3538 T: fix test name
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: internal

#3535 TOML: Support hexadecimal, binary, octal integers and nan/inf floats
  intellij-toml/src/main/grammars/TomlLexer.flex
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/numbers.toml
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/numbers.txt
Labels: feature

#3542 ANN: Fix external linter cache
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/main/kotlin/org/rust/openapiext/ProjectCache.kt
Labels: fix

#3523 DBG: Show variable value by hovering
  debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerLanguageSupport.kt
  debugger/src/main/kotlin/org/rust/debugger/lang/RsEvaluator.kt
Labels: feature

#3515 Don't jump over multi-line whitespaces in up/down mover
  src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt
  src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt
Labels: fix

#3546 ANN: Don't try to kill the external linter process on any PSI change
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
Labels: fix

#3549 GRD: update IDEA & CLion EAPs
  build.gradle.kts
  gradle-191.properties
Labels: internal

#3553 INSP: cleanup `Match Check` inspection
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsMatchCheckInspection.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/inspectionDescriptions/RsMatchCheck.html
  src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
Labels: fix

#3562 TY: coerce types in vec! macro expressions
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: fix

#3565 TY: better coerce types in generic function args
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#3572 RUN: Run rustfmt with UTF-8 charset
  src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
  src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
Labels: fix

#3455 MACRO&RES: Resolve bang `foo!()` proc macros to appropriate functions
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: feature

#3592 COMP: add `for` postfix completion
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/resources/postfixTemplates/IterPostfixTemplate/before.rs.template
  src/test/kotlin/org/rust/ide/template/postfix/IterPostFixTemplateTest.kt
Labels: feature

#3604 PROF: Fix rustfilt execution
  clion/src/191/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
Labels: fix

#3605 PROF: Disable profiler runner on Windows
  clion/src/191/main/kotlin/org/rust/clion/profiler/RsProfilerRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
Labels: fix

#3610 GRD: update IDEA & CLion
  gradle-183.properties
  gradle-191.properties
  gradle.properties
Labels: internal

#3555 INT: Remove dbg!
  src/main/kotlin/org/rust/ide/intentions/RemoveDbgIntention.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/intentionDescriptions/RemoveDbgIntention/after.rs.template
  src/main/resources/intentionDescriptions/RemoveDbgIntention/before.rs.template
  src/main/resources/intentionDescriptions/RemoveDbgIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/RemoveDbgIntentionTest.kt
Labels: feature

#3595 ANN: fix highlighting of keywords in paths (`crate`/`Self`)
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
Labels: fix

#3615 Don't affect psi of other languages while renaming
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
Labels: fix

#3621 COMP: Fix import duplication when multiple carets are used
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsTraitMethodCompletionTest.kt
Labels: fix

#3617 QDOC: show documentation of the corresponding trait item if element documentation is empty
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
Labels: feature

#3603 COMP: change text attributes in completion for deprecated items
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
Labels: feature
