Repository intellij-rust/intellij-rust, pull requests merged in 2020-11, with the labels that each got.

#6338 COMP: complete parenthesis for repr attribute
  src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
Labels: feature

#6207 INT: Don't show "Add wildcard pattern" for empty match
  src/main/kotlin/org/rust/ide/intentions/AddWildcardArmIntention.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddWildcardArmIntentionTest.kt
Labels: fix

#6301 REF: Add trait imports in move refactoring if necessary
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveTraitMethodsProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#6307 REF: Check if target mod has item with same name in move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#6326 RUN: Take into account execution context in Run Anything
  src/main/kotlin/org/rust/ide/actions/runAnything/RsRunAnythingProvider.kt
Labels: fix

#6330 INT: Compare with zero instead when casting numerical to bool
  src/main/kotlin/org/rust/ide/annotator/fixes/CompareWithZeroFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/CompareWithZeroFixTest.kt
Labels: feature

#6011 REF: Group structs and traits with related impls in move items dialog
  src/main/kotlin/org/rust/ide/refactoring/move/RsMemberSelectionPanel.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveMemberSelection.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt
Labels: feature

#6203 CARGO: Replace paths to symlink source in cargo metadata
  src/main/kotlin/org/rust/cargo/toolchain/impl/BuildScriptsInfo.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: internal

#6291 INSP: allow duplicate parameter bindings for trait methods without a body [E0415]
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/RsDuplicatedTraitMethodBindingInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsDuplicatedTraitMethodBinding.html
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsDuplicatedTraitMethodBindingInspectionTest.kt
Labels: fix

#6306 REF: Support references to generic items in move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#6308 REF: Check impls in move refactoring when moving to other crate
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#6346 COMP: add completion of track_caller attribute for functions
  src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
Labels: feature

#6341 QDOC: show quick documentation for primitive types in stdlib
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/docs/RsDocumentationProviderTest.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
Labels: fix

#6304 ANN: detect E0449 for enum variants
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/enum_vis.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/enum_vis.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/enum_vis.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/enum_vis.txt
Labels: feature

#5933 Introduce line marker for wasm_bindgen attributes in WebAssembly projects
  CONTRIBUTING.md
  build.gradle.kts
  js/src/main/kotlin/org/rust/js/RsWasmBindgenLineMarkerProvider.kt
  js/src/main/resources/META-INF/js-only.xml
  js/src/test/resources/META-INF/plugin.xml
  plugin/src/main/resources/META-INF/plugin.xml
  settings.gradle.kts
Labels: feature

#6272 CARGO: doesn't load Cargo project structure twice
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoEventService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
  src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
  src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherTest.kt
Labels: fix

#6335 COMP: add completion for the non_exhaustive attribute
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Labels: feature

#6368 MACRO: enable macro expansion cache by default
  src/main/resources/META-INF/rust-core.xml
Labels: performance

#6289 COMP: complete cargo features in `Cargo.toml`
  toml/src/202/test/kotlin/org/rust/toml/completion/CargoTomlCompletionEditionTestBase.kt
  toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyFeaturesCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlLookupElements.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlDependencyFeaturesReferenceProvider.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
  toml/src/test/kotlin/org/rust/toml/completion/CargoTomlCompletionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependencyFeaturesCompletionProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProviderTest.kt
Labels: feature

#6356 DBG: Update BTreeMap/BTreeSet GDB pretty-printers
  prettyPrinters/gdb_providers.py
  pretty_printers_tests/tests/btree.rs
Labels: fix

#6378 RES: Add option to settings to enable new resolve
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/test/kotlin/org/rust/NewResolve.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2018.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: feature

#6380 MACRO: fix macro group matching
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#6358 GRD: update 2020.3 EAPs
  build.gradle.kts
  clion/src/202/main/resources/META-INF/platform-clion-only.xml
  clion/src/203/main/resources/META-INF/platform-clion-only.xml
  clion/src/main/resources/META-INF/clion-only.xml
  gradle-203.properties
  gradle.properties
Labels: internal

#6352 INSP: Add error for `repr` without parentheses
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddAttrParenthesesFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddAttrParenthesesFixTest.kt
Labels: feature

#6319 INSP: Extend function argument count check to work for closures (E0057)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#6372 ANN: add check that constants have a type and quick fix that adds it
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddTypeFix.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddTypeFixTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/constants.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/constants.txt
Labels: feature

#6396 TY&MACRO: Support macro types
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: fix

#6395 PERF: optimize `RsExpandedElement.getContextImpl`
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
Labels: performance

#6402 REF: Support resolve macro call to expanded macro def using PSI
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Labels: fix

#6276 RES: resolve cfg/cfg_attr features to Cargo.toml in Rust code
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlReferenceContributor.kt
  toml/src/main/kotlin/org/rust/toml/resolve/RsCargoTomlIntegrationReferenceContributor.kt
  toml/src/main/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProvider.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/test/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProviderTest.kt
Labels: feature

#6407 PERF&MACRO: optimize crate search in macro expansion with new resolve
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Labels: performance

#6323 Validate perf profiler settings
  clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
Labels: fix

#6398 RES: Fix exception when resolving import in cfg-disabled shadowed mod using new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: fix

#6413 INSP: Detect attributes that require parentheses but have no parentheses.
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsAttrWithoutParentheses.html
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddAttrParenthesesFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspectionTest.kt
Labels: feature

#6401 PERF: Use custom HashMap for visibleItems in new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
Labels: performance

#6422 RES: Fix exception when resolve is called during building CrateDefMap
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
Labels: fix

#6406 Fix 2020.3 compatibility
  src/202/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/203/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
Labels: fix

#6430 Fix wrong resolve of cargo feature in `cfg_attr`
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
Labels: fix

#6431 Fix rust structure modification increment after remove a PSI element
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
Labels: fix

#6426 RES: Store fromGlobImport flag inside VisItem in new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
Labels: performance

#6432 RES: resolve cargo features in `#[doc(cfg(feature = "foo"))]` attributes
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProviderTest.kt
Labels: feature

#6434 RES: resolve cargo features in conditional attributes under `cfg_attr`
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  toml/src/main/kotlin/org/rust/toml/resolve/RsCargoTomlIntegrationReferenceContributor.kt
  toml/src/test/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProviderTest.kt
Labels: feature

#5939 RUN: Add build task for wasm-pack configurations
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskProvider.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildTaskProvider.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfiguration.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#6429 REF(MOVE): Use unqualified path for references to target mod if possible
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: fix

#6435 RES: Exclude private items from completion when using new resolve
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#6259 INSP: check if pattern identifiers are not bound multiple times [E0416]
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#6421 ANN: improve "Item is private" annotation and "Make public" fix
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/MakePublicFix.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsInvalidReexportErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
Labels: feature, fix

#6427 Validate DTrace profiler settings
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
Labels: fix

#6440 INSP: improve `AttrWithoutParentheses`: take into account `cfg_attr
  src/main/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspection.kt
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/test/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  toml/src/main/kotlin/org/rust/toml/resolve/RsCargoTomlIntegrationReferenceContributor.kt
Labels: feature

#6445 COMP: complete cfg options and operators in `cfg_attr` and `doc(cfg())`
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProviderTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Labels: feature

#6448 COMP: take into account `cfg_attr` attribute while attribute completion
  src/main/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspection.kt
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLintCompletionProviderTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Labels: feature

#6444 COMP: complete `feature =""` in `cfg` attributes
  src/main/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProviderTest.kt
Labels: feature
