Repository intellij-rust/intellij-rust, pull requests merged in 2020-12, with the labels that each got.

#6462 RES&COMP: resolve & complete `path` attribute under `cfg_attr`
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsFilePathResolveTest.kt
Labels: feature

#6460 RES&COMP: resolve and complete derive attributes under `cfg_attr`
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Labels: feature

#6458 COMP: complete more attributes, don't complete outdated ones
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Labels: fix

#6461 RES: resolve proc macro attributes under `cfg_attr`
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: feature

#6246 Add an extension point for toolchain path suggestion
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RsMacToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RsSysPathToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RsToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RsUnixToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RsWinToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RustupToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/util/ToolchainUtil.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#6423 Support `Find Usages` action for Cargo features
  intellij-toml/src/main/kotlin/org/toml/ide/search/TomlFindUsagesProvider.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/Psi.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/impl/Psi.kt
  intellij-toml/src/main/resources/META-INF/plugin.xml
  src/main/kotlin/org/rust/ide/search/RsWordScanner.kt
  toml/src/main/kotlin/org/rust/toml/CargoTomlElementDescriptionProvider.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
  toml/src/main/kotlin/org/rust/toml/search/CargoTomlFindUsagesHandlerFactory.kt
  toml/src/main/kotlin/org/rust/toml/search/CargoTomlUsageTypeProvider.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/test/kotlin/org/rust/toml/search/CargoTomlFindUsagesTest.kt
Labels: feature

#6443 REF(MOVE): Change references in use groups
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileReexportTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/mod2/foo.rs
Labels: feature

#6506 ANN: Provides case-checking for non-ascii name
  src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/NamingNotationsTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsArgumentNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsAssocTypeNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsConstNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsEnumNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsEnumVariantNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsFieldNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsFunctionNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsLifetimeNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsMacroNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsMethodNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsModuleNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStaticConstNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStructNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTraitNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTypeAliasNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTypeParameterNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt
Labels: fix

#6390 CARGO: Implement crates local index based on cargo registry index
  build.gradle.kts
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  toml/src/main/kotlin/org/rust/toml/completion/CargoNormalizedNamesPrefixMatcher.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexCachesInvalidator.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/completion/DependencyCratesLocalCompletionProvider.kt
  toml/src/main/resources/META-INF/toml-only.xml
Labels: feature

#5644 ANN: add quick fix to fill missing arguments in function call
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt
Labels: feature

#5771 INT: add intention to change item visibility
  src/main/kotlin/org/rust/ide/annotator/fixes/MakePublicFix.kt
  src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt
  src/main/kotlin/org/rust/ide/intentions/visibility/MakePrivateIntention.kt
  src/main/kotlin/org/rust/ide/intentions/visibility/MakePubCrateIntention.kt
  src/main/kotlin/org/rust/ide/intentions/visibility/MakePubIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/MakePrivateIntention/after.rs.template
  src/main/resources/intentionDescriptions/MakePrivateIntention/before.rs.template
  src/main/resources/intentionDescriptions/MakePrivateIntention/description.html
  src/main/resources/intentionDescriptions/MakePubCrateIntention/after.rs.template
  src/main/resources/intentionDescriptions/MakePubCrateIntention/before.rs.template
  src/main/resources/intentionDescriptions/MakePubCrateIntention/description.html
  src/main/resources/intentionDescriptions/MakePubIntention/after.rs.template
  src/main/resources/intentionDescriptions/MakePubIntention/before.rs.template
  src/main/resources/intentionDescriptions/MakePubIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/visibility/MakePrivateIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/visibility/MakePubCrateIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/visibility/MakePubIntentionTest.kt
Labels: feature

#6273 ANN: inspect logging macros of the log crate
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorToolchainTest.kt
Labels: feature

#6491 ANN: do not annotate unimplemented cfg-disabled trait items
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#6498 RES: resolve derive proc macros with new resolve engine
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: fix

#4254 RUN: Support for ANSI colors in build tool window
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoder.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/main/kotlin/org/rust/openapiext/JsonUtils.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildTest.kt
  src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: fix

#6530 RUN: Enable Build Tool Window by default
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#6404 Support fully-qualified paths in macro calls at item level.
  .editorconfig
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.txt
Labels: fix

#6533 Improve popup of `Has implementations` gutter icon
  src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt
  src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt
Labels: fix

#6536 ANN: fix escaping in annotation messages
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#6492 QDOC: show documentation for keyword like elements
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
  src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
  src/test/kotlin/org/rust/ide/docs/RsStdlibResolveLinkTest.kt
Labels: feature

#6526 PERF: fix name resolution performance in large modules
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Labels: performance

#6419 Provide ML completion ranking for Rust
  CONTRIBUTING.md
  build.gradle.kts
  ml-completion/src/203/main/kotlin/org/rust/ml/RsCompletionFeaturesPolicy.kt
  ml-completion/src/203/main/kotlin/org/rust/ml/RsElementFeatureProvider.kt
  ml-completion/src/203/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
  ml-completion/src/203/main/resources/META-INF/ml-completion-only.xml
  ml-completion/src/203/test/kotlin/org/rust/ml/RsElementFeatureProviderTest.kt
  ml-completion/src/203/test/kotlin/org/rust/ml/RsModelMetadataConsistencyTest.kt
  ml-completion/src/203/test/resources/META-INF/plugin.xml
  plugin/src/main/resources/META-INF/plugin.xml
  settings.gradle.kts
Labels: feature

#6541 GRAM: parse `::` as an incomplete path
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.txt
Labels: fix

#6543 RES: Proper resolve textual scoped macros in new resolve
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
Labels: fix

#6545 RES: Fix DefMap updating when changing enum variant name
  src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
Labels: fix

#6542 GRAM: simplify syntax error messages on incorrect paths
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/shifts.txt
Labels: fix

#6555 Introduce message bundle
  src/main/kotlin/org/rust/RsBundle.kt
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectActionBase.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandActionBase.kt
  src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectsAction.kt
  src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt
  src/main/kotlin/org/rust/ide/actions/RsRunExternalLinterAction.kt
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
Labels: internal

#6534 CI: provide regression testing for stdlib
  .github/workflows/regressions.yml
  scripts/fetch_projects.py
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
Labels: internal

#6538 CI: set milestone automatically for PRs from forks
  .github/workflows/milestones.yml
Labels: internal

#6120 ANN: highlight arguments of panic macro
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: feature

#6553 CARGO: resolve URL references in some package and dependency attributes
  toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlReferenceContributor.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlUrlReferenceProvider.kt
  toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlUrlResolveTest.kt
Labels: feature

#6497 Support `cfg_attr` attributes
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsCfgAttrTypeInferenceTest.kt
Labels: feature

#6568 RES: Fix restricted visibility in new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PathUtil.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
Labels: fix

#6576 RES: Support file level macro_use attribute in new resolve
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Labels: fix

#6578 TOML: add TomlVisitor
  intellij-toml/src/main/kotlin/org/toml/lang/psi/TomlVisitor.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/impl/Psi.kt
  intellij-toml/src/test/kotlin/org/toml/lang/psi/TomlVisitorTest.kt
Labels: internal

#6574 Fix cargo features inference with renamed packages
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
Labels: fix

#6439 CARGO: Make crates local index updates incremental
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
Labels: feature

#6549 Evaluate unknown cfg options to false if no `build.rs` in a package
  src/main/kotlin/org/rust/cargo/CfgOptions.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/test/kotlin/org/rust/MockAdditionalCfgOptions.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: fix

#6507 Disable `cfg(test)` in external dependencies if there is `cfg(not(test))`
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsCfgNotTestIndex.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
  src/test/kotlin/org/rust/lang/core/stubs/index/RsCfgNotTestIndexTest.kt
Labels: fix
