Repository intellij-rust/intellij-rust, pull requests merged in 2020-09, with the labels that each got.

#6049 INT: fix FlattenUseStatementsIntention flattens nested `use` statements correctly
  src/main/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntention.kt
  src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt
Labels: fix

#6017 GRD: use kotlin 1.4
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt
Labels: internal

#6050 INT: add missing description and plugin registration for CreateFunctionIntention
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/CreateFunctionIntention/after.rs.template
  src/main/resources/intentionDescriptions/CreateFunctionIntention/before.rs.template
  src/main/resources/intentionDescriptions/CreateFunctionIntention/description.html
Labels: fix

#6051 CI: set PR milestone automatically
  .github/workflows/milestones.yml
  scripts/check_release_branch_date.py
  scripts/github.py
  scripts/set_milestone.py
Labels: internal

#6056 RUN: Fix benches flag in cargo command completion
  src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
Labels: fix

#6042 T: add test that intentions have descriptions and templates
  src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
Labels: internal

#6033 RES: do not resolve std macros when no_std is present
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Labels: fix

#6010 REF: Make moved items public if needed
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#5928 GRAM: add initial parsing of the new asm! macro
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
Labels: feature

#6057 INT: introduce quick fix to add `..` to struct pattern that has missing fields
  src/main/kotlin/org/rust/ide/annotator/fixes/AddPatRestFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddPatRestFixTest.kt
Labels: feature

#6075 Fix project under symlinked directory
  src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt
Labels: fix

#6078 REF: Add explicit visibility check in move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: fix

#5995 RUN: Rename "Cargo Command" run configuration to "Cargo"
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt
Labels: feature

#6069 CI: cache evcxr in check workflow
  .github/workflows/check.yml
Labels: internal

#6041 MACRO: fix RangeMap generation
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
Labels: fix

#6039 INT: add support for creating methods in CreateFunctionIntention
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: feature

#5720 INSP: refactor checking and filling of match expressions
  .idea/dictionaries/intellij_rust.xml
  src/main/kotlin/org/rust/ide/inspections/checkMatch/CheckMatchUtils.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/Constructor.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/Pattern.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsMatchCheckInspection.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsNonExhaustiveMatchInspection.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsUnreachablePatternsInspection.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/Usefulness.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddRemainingArmsFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddWildcardArmFix.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/intentions/FillMatchArmsIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsMatchCheck.html
  src/main/resources/inspectionDescriptions/RsNonExhaustiveMatch.html
  src/main/resources/inspectionDescriptions/RsUnreachablePatterns.html
  src/main/resources/intentionDescriptions/FillMatchArmsIntention/after.rs.template
  src/main/resources/intentionDescriptions/FillMatchArmsIntention/before.rs.template
  src/main/resources/intentionDescriptions/FillMatchArmsIntention/description.html
  src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/match/RsUnreachablePatternsInspectionTest.kt
  src/test/kotlin/org/rust/ide/intentions/FillMatchArmsIntentionTest.kt
Labels: feature

#6080 REF: Use same processor for move files and move items refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileReexportTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTestBase.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileVisibilityTest.kt
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/mod2/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/before/mod1/mod1_inner/foo.rs
Labels: internal

#6102 INT: add missing title and fix typo in CreateFunctionIntention
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/resources/intentionDescriptions/CreateFunctionIntention/after.rs.template
Labels: fix

#5657 REF: handle name conflicts after renaming bindings
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Labels: feature

#5369 COMP: Deprioritize completion of &mut self methods for const references and bindings
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
Labels: feature

#6113 DBG: properly update debugger after NativeDebug plugin update
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
Labels: fix

#6118 REF: don't rename `src` dir
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/test/kotlin/org/rust/RsTestBase.kt
Labels: fix

#5704 FMT: Add an option to use rustfmt instead of build-in formatter
  src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/SerializationUtils.kt
  src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
  src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
  src/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/main/kotlin/org/rust/ide/formatter/processors/RsPostFormatProcessor.kt
  src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/cargo/RustupTestFixture.kt
  src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
  src/test/kotlin/org/rust/ide/formatter/RsTrailingCommaFormatProcessorTest.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Labels: feature

#6122 Get rid of `Don't reformat child modules` option
  src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
Labels: fix

#6125 Fix exception in the cargo toolwindow init
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#6126 Fix exception `PsiElementBase.notNullChild` after variable inlining
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt
  src/test/kotlin/org/rust/RsTestBase.kt
Labels: fix

#6127 Fix "Incorrect CachedValue use" exception in RsFile
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
Labels: fix

#3829 INT: add support for generic types to unelide lifetimes intention
  src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
  src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
Labels: feature

#5456 FIX: render types with a fully qualified name when needed
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
Labels: fix

#6114 CARGO: introduce CargoSyncTask
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/openapiext/AsyncTasks.kt
  src/main/kotlin/org/rust/openapiext/TaskResult.kt
Labels: internal

#6132 INT: add remaining arms and add wildcard arm intentions
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsNonExhaustiveMatchInspection.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsUnreachablePatternsInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddRemainingArmsFix.kt
  src/main/kotlin/org/rust/ide/intentions/AddRemainingArmsIntention.kt
  src/main/kotlin/org/rust/ide/intentions/AddWildcardArmIntention.kt
  src/main/kotlin/org/rust/ide/utils/checkMatch/CheckMatchUtils.kt
  src/main/kotlin/org/rust/ide/utils/checkMatch/Constructor.kt
  src/main/kotlin/org/rust/ide/utils/checkMatch/Pattern.kt
  src/main/kotlin/org/rust/ide/utils/checkMatch/PatternKind.kt
  src/main/kotlin/org/rust/ide/utils/checkMatch/Usefulness.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/AddRemainingArmsIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddRemainingArmsIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddRemainingArmsIntention/description.html
  src/main/resources/intentionDescriptions/AddWildcardArmIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddWildcardArmIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddWildcardArmIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/AddRemainingArmsIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddWildcardArmIntentionTest.kt
Labels: feature

#5955 RES: Add name to RsResolveProcessor
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
Labels: internal

#6153 Use Java 11 to build and develop the plugin
  .github/workflows/check.yml
  .github/workflows/regressions.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  CONTRIBUTING.md
  build.gradle.kts
Labels: internal

#6156 Follow `rustc --print sysroot` stdlib path without Rustup
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Labels: fix

#6071 Add `updateCargoOptions` task to update cargo options automatically
  build.gradle.kts
  src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
  src/main/kotlin/org/rust/cargo/util/CargoOptions.kt
  src/main/kotlin/org/rust/ide/actions/runAnything/cargo/RunAnythingCargoItem.kt
  src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
  src/test/kotlin/org/rust/ide/actions/runAnything/cargo/CargoRunAnythingProviderTest.kt
Labels: fix, internal

#6157 STUB: Add helper methods for new resolve
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/psi/RsStubElementTypes.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
  src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/stdext/HashCode.kt
Labels: internal

#6167 INSP: Convert implicit trait type inspection into lint one
  src/main/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsBareTraitObjects.html
  src/test/kotlin/org/rust/ide/inspections/RsBareTraitObjectsInspectionTest.kt
Labels: feature

#6168 PERF&MACRO: Take heavy process latch only if there are macros to expand
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: performance

#6170 RUN: Fix `Run with Coverage` on nightly channel
  src/main/kotlin/org/rust/cargo/toolchain/Grcov.kt
Labels: fix

#6178 INT: Use public visibility when creating function in other crate
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: fix

#6176 T: Show test result in the gutter
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt
Labels: fix

#6048 RUN: Don't use `-Cpanic=abort` when `Run with Coverage`
  coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
  coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt
Labels: fix

#6143 GRAM: properly parse special macro calls with fqn
  common/src/main/kotlin/com/intellij/lang/parser/utils.kt
  intellij-toml/src/main/kotlin/org/toml/lang/parse/TomlParserUtil.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/parser/util.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
Labels: fix

#6179 UI: Get rid of scrollbar in project creation dialog in CLion
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
Labels: fix
