Repository intellij-rust/intellij-rust, pull requests merged in 2020-08, with the labels that each got.

#5849 [CARGO] Include RUSTC in environment
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
Labels: fix

#5841 TY: infer type parameters from assoc type bindings
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#5856 Properly check spelling in lifetimes
  src/main/kotlin/org/rust/ide/spelling/RsNameIdentifierOwnerTokenizer.kt
  src/test/kotlin/org/rust/ide/spellchecker/RsSpellCheckerTest.kt
Labels: fix

#5747 RUN: fold external stack traces
  src/main/kotlin/org/rust/cargo/runconfig/filters/FilterUtils.kt
  src/main/kotlin/org/rust/cargo/runconfig/filters/RegexpFileLinkFilter.kt
  src/main/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilter.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleFolding.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/console/RsConsoleFoldingTest.kt
  src/test/kotlin/org/rust/ide/console/RsConsoleFoldingTestBase.kt
Labels: feature

#5661 COMP: prefer trait methods before private inherent methods
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
Labels: fix

#5643 INT: add intention to substitute an associated type
  src/main/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/after.rs.template
  src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/before.rs.template
  src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntentionTest.kt
Labels: feature

#5857 REF: find occurrences for introduce constant/variable outside functions
  src/main/kotlin/org/rust/ide/refactoring/extraxtExpressionUtils.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
Labels: fix

#5842 HINT: don't show a hint for single lambda param
  src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt
  src/test/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHintsProviderTest.kt
Labels: fix

#5736 REF: Update references in move items refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMovePathHelper.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
Labels: feature

#5613 NAV: allow navigation from RsAbstractable to its implementations
  src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/navigation/goto/RsImplsSearch.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStructOrEnumItemElement.kt
  src/test/kotlin/org/rust/ide/lineMarkers/RsLineMarkerProviderTestBase.kt
  src/test/kotlin/org/rust/ide/lineMarkers/RsMethodLineSeparatorProviderTest.kt
  src/test/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProviderTest.kt
Labels: feature

#5855 Don't skip doc comments provided via macro definition
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsErrorChainMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
Labels: fix

#5306 INSP: add AddTypeArguments quick fix to RsWrongTypeArgumentsNumberInspection
  src/main/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddTypeArguments.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
Labels: feature

#5715 PRJ: Project generation with cargo-generate
  idea/src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt
  idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/ide/newProject/ConfigurationData.kt
  src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
  src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt
  src/main/kotlin/org/rust/ide/newProject/RsProjectTemplate.kt
  src/main/kotlin/org/rust/ide/newProject/Utils.kt
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
  src/main/kotlin/org/rust/ide/ui/layout.kt
Labels: feature

#5838 RES: Fix stdlib source paths on nightly
  .github/workflows/check.yml
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
Labels: fix

#5828 HINT: allow comparison of consecutive iterator special case types in chain method hints
  src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt
  src/test/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProviderTest.kt
Labels: feature

#5885 Update icons for Cargo, REPL, `cargo-generate` and `wasm-pack`
  src/main/kotlin/org/rust/cargo/icons/CargoIcons.kt
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
  src/main/kotlin/org/rust/ide/newProject/RsProjectTemplate.kt
  src/main/resources/icons/cargo-generate.svg
  src/main/resources/icons/cargo-lock.png
  src/main/resources/icons/cargo-lock.svg
  src/main/resources/icons/cargo-lock@2x.png
  src/main/resources/icons/cargo.png
  src/main/resources/icons/cargo.svg
  src/main/resources/icons/cargo@2x.png
  src/main/resources/icons/cargo_dark.svg
  src/main/resources/icons/repl.svg
  src/main/resources/icons/repl_dark.svg
  src/main/resources/icons/wasm-pack.svg
  src/main/resources/icons/wasm-pack_dark.svg
Labels: feature

#5760 RUN: Show error message when trying to run with coverage on non-nightly channel
  .github/workflows/check.yml
  coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
  coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt
Labels: feature

#5641 ANN: Fix custom macro attr (name conflicts)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#5877 COMP: don't insert double parentheses
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt
Labels: fix

#5889 INSP: create separate Lint group in inspection settings
  src/main/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLintLevel.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/inspections/lints/NamingNotationsTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLintLevelTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsArgumentNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsAssocTypeNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsConstNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsEnumNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsEnumVariantNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsFieldNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsFunctionNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsLifetimeNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsMacroNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsMethodNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsModuleNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStaticConstNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStructNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTraitNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTypeAliasNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTypeParameterNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt
Labels: feature

#5891 INSP: support `nonstandard_style` attribute for naming inspections
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsConstNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsModuleNamingInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTraitNamingInspectionTest.kt
Labels: feature

#5890 INSP: convert while true inspection into lint one
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsWhileTrueLoopInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/inspections/lints/RsWhileTrueLoopInspectionTest.kt
Labels: feature

#5865 ANN: Check if the `derive` attr is placed on the supported item
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
Labels: feature

#5745 RUN: Implement wasm-pack run configuration
  .idea/dictionaries/intellij_rust.xml
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/WorkingDirectoryComponent.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfigurationType.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunStateBase.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/ui/WasmPackCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/WasmPack.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#5912 PERF: slightly optimize let bindings resolve
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
Labels: performance

#5845 PRJ: Project generation with custom user templates
  src/main/kotlin/org/rust/ide/newProject/state/RsUserTemplatesState.kt
  src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#5873 RUN: Add autocompletion for partial `cargo` word in Run Anything
  src/main/kotlin/org/rust/ide/actions/runAnything/CargoRunAnythingProvider.kt
  src/test/kotlin/org/rust/ide/actions/runAnything/CargoRunAnythingProviderTest.kt
Labels: fix

#5870 INSP: do not offer ChangeReturnTypeFix in lambdas without an explicit return type
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
Labels: fix

#5645 COMP: Support function and struct complete current statement
  src/main/kotlin/org/rust/ide/typing/assist/AfterFunctionOrStructEnterProcessor.kt
  src/main/kotlin/org/rust/ide/typing/assist/FunctionOrStructFixer.kt
  src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
  src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt
Labels: feature

#5926 PERF: set of name resolution optimizations
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Labels: performance

#5940 RUN: Suggest configuration name from command
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
Labels: feature

#5910 PRJ: Create default run configuration after project generation
  idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfigurationType.kt
  src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
  src/main/kotlin/org/rust/ide/newProject/RsProjectTemplate.kt
  src/main/kotlin/org/rust/ide/newProject/Utils.kt
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
Labels: feature

#5946 CI: create a release branch on a schedule from CI
  .github/workflows/release-branch.yml
  scripts/check_release_branch_date.py
Labels: internal

#5919 Update package name validation during new project creation
  src/main/kotlin/org/rust/ide/newProject/RsPackageNameValidator.kt
  src/test/kotlin/org/rust/ide/newProject/RsProjectNameValidationTest.kt
Labels: fix

#5937 INSP: select a better location for attaching file to modules
  src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt
  src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt
Labels: fix

#5920 REF: Support reexports in move items refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#5664 REF: Add related impls to initial items to move
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt
Labels: feature

#5932 CI: initial regression testing
  .github/workflows/regressions.yml
  build.gradle.kts
  gradle.properties
  scripts/calculate_regressions.py
  src/test/kotlin/org/rustPerformanceTests/CustomRealProjectAnalysisTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
Labels: internal

#5864 RES: Macro from local import should shadow macro from crate root
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#5959 PRJ: Force cargo-generate to skip name conversion
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
Labels: fix

#5945 RUN: Fix exception on build cancel
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
Labels: fix

#5874 ACT: Don't try to initialize Cargo Tool Window if it already initialized
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#5979 REF: Check visibility conflicts in move top-level items refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTestBase.kt
Labels: feature

#5998 ANN: ignore string format parameters that are not string literals
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: fix

#5966 INSP: fix false positive unresolved reference error
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Labels: fix

#5663 REF: Handle selection in move top-level items refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt
  src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsSelectionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTestBase.kt
Labels: feature

#6001 PRJ: Add Procedural Macro project template
  src/main/kotlin/org/rust/ide/newProject/RsProjectTemplate.kt
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
Labels: feature

#5989 PERF: Don't expand cfg-disabled macro calls
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
Labels: performance

#5459 REF: add inline value refactoring
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineUtils.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/ui.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/refactoring/RsInlineFunctionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsInlineValueTest.kt
Labels: feature

#5999 RUN: Don't try to initialize Cargo Tool Window before project opened
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#5505 INT: add intention to create a function from an unresolved function call
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantProcessor.kt
  src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt
Labels: feature

#5986 RES: fix mod path attributes to another dirs
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Labels: fix

#5352 INT: generate accessors for struct fields
  src/main/kotlin/org/rust/ide/refactoring/generate/BaseGenerateHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/StructMember.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/constructor/GenerateConstructorHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/getter/GenerateGetterHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/RsGenerateBaseTest.kt
Labels: feature, to be documented

#5980 CARGO: Use package name for cargo project if possible
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#6024 INSP: don't apply RsStaticConstNamingInspection for extern statics
  src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStaticConstNamingInspectionTest.kt
Labels: fix

#6028 Show "missing toolchain" notification in Cargo.toml
  src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
Labels: feature

#6019 INT: add support for guessing return type in CreateFunctionIntention
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: feature

#6031 RES: fix issue #5961
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
Labels: fix

#6032 INT: disable SubstituteAssociatedTypeIntention for type aliases
  src/main/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntention.kt
  src/test/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntentionTest.kt
Labels: fix

#5949 T: Don't unescape test output
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt
Labels: fix

#6038 REF: handle struct field shorthand init in RsInlineValue
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RsInlineValueTest.kt
Labels: fix
