Repository intellij-rust/intellij-rust, pull requests merged in 2020-07, with the labels that each got.

#5683 Fix `AnnotationHolderImpl` not running in context
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
Labels: fix

#5652 INT: allow extracting non-root modules in ExtractInlineModuleIntention
  src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt
  src/test/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntentionTest.kt
Labels: feature

#5669 QDOC: fix some corner cases in doc rendered
  src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
  src/test/kotlin/org/rust/ide/docs/RsCodeHighlightingInQuickDocumentationTest.kt
Labels: fix

#5687 Structure View: add alpha sorter
  src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
Labels: feature

#5678 Fix `Lift return` inspection on empty match expr
  src/main/kotlin/org/rust/ide/inspections/RsLiftInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt
Labels: fix

#5667 CI: release beta and stable toml builds from GitHub workflow
  .github/workflows/release-branch.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
Labels: internal

#5689 CARGO: Fix finding location of evcxr and grcov on arch linux
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
Labels: fix

#5701 RUN: Add an experimental feature to enable/disable Test Tool Window
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#5441 RUN: Fix environment variables for Coverage runner
  .github/workflows/check.yml
  .travis.yml
  appveyor.yml
  coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
  coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
Labels: fix

#5693 Notify user about unsupported toolchain version
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
Labels: feature

#5705 UI: update target icons
  src/main/kotlin/org/rust/cargo/icons/CargoIcons.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectTreeStructure.kt
  src/main/resources/icons/target-bench.svg
  src/main/resources/icons/target-bench_dark.svg
  src/main/resources/icons/target-bin.svg
  src/main/resources/icons/target-bin_dark.svg
  src/main/resources/icons/target-example.svg
  src/main/resources/icons/target-example_dark.svg
  src/main/resources/icons/target-lib.svg
  src/main/resources/icons/target-test.svg
  src/main/resources/icons/targetBench.svg
  src/main/resources/icons/targetBin.svg
  src/main/resources/icons/targetCustomBuild.svg
  src/main/resources/icons/targetExample.svg
  src/main/resources/icons/targetLib.svg
  src/main/resources/icons/targetTest.svg
  src/main/resources/icons/targets.svg
Labels: feature

#5710 ANN: Fix exception with invalid rustc annotation
  src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt
Labels: fix

#5700 RUN: Show cargo output in Test Tool window
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt
Labels: fix

#4848 T: Fix jump from test results to doctest
  debugger/src/main/kotlin/org/rust/debugger/lang/RsEvaluator.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
  src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/SubstituteTextFix.kt
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentPopup.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsRecursiveCallLineMarkerProvider.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoDependencyReferenceProvider.kt
  toml/src/test/kotlin/org/rust/toml/CargoTomlGotoSuperHandlerTest.kt
Labels: fix

#5716 Enable new macro expansion engine
  build.gradle.kts
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#5718 Fix cache invalidation when editing function-local macro
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
Labels: fix

#5648 RUN: add custom text for assert test diff
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestConsoleProperties.kt
Labels: feature

#5658 COMP: do not offer let and return inside struct literals and pats
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: fix

#5647 ANN: add quick fix to change local variable type
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertLetDeclTypeFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ConvertLetDeclTypeFixTest.kt
Labels: feature

#5717 Fix `go to type declaration` for macro-generated items
  src/main/kotlin/org/rust/cargo/project/model/RsGeneratedSourcesFilter.kt
  src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt
Labels: fix

#5539 INSP: improve AddUnsafeFix to find the closest enclosing block
  src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
Labels: fix

#5723 STUB: improve block stub creation
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTest.kt
  src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTestBase.kt
  src/test/kotlin/org/rustSlowTests/RsCompilerSourcesLazyBlockStubCreationTest.kt
Labels: fix

#5688 REF: Keep existing reference style in move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTest.kt
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/mod2/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/usages1.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/usages2.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/usages3.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/mod1/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/usages1.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/usages2.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/usages3.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/after/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/after/usages.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/before/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/before/usages.rs
Labels: feature

#5744 FIX: set expired Valgrind callback parameter to nullable
  clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
Labels: fix

#5729 Fix crash during the plugin unloading on 2020.2
  gradle-202.properties
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: fix

#5757 INSP: support auto import with module reexports with aliases
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
Labels: fix

#5762 RES: properly handle `crate::macro_name!` calls while name resolution
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
Labels: fix

#5536 TOML: initial formatter implementation
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/TomlFmtBlock.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/TomlFmtContext.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/TomlFormattingModelBuilder.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/impl/indent.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/impl/spacing.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/impl/utils.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/settings/TomlCodeStyleSettings.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/settings/TomlCodeStyleSettingsProvider.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/settings/TomlLanguageCodeStyleSettingsProvider.kt
  intellij-toml/src/main/kotlin/org/toml/ide/formatter/utils.kt
  intellij-toml/src/main/resources/META-INF/plugin.xml
  intellij-toml/src/test/kotlin/org/toml/TomlTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotationTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/ide/formatter/TomlAutoIndentTest.kt
  intellij-toml/src/test/kotlin/org/toml/ide/formatter/TomlFormatterTest.kt
  intellij-toml/src/test/kotlin/org/toml/ide/formatter/TomlFormatterTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/ide/typing/TomlTypingTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/ide/wordSelection/TomlSelectionHandlerTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/lang/TomlFileTypeTest.kt
  intellij-toml/src/test/kotlin/org/toml/lang/psi/TomlPsiFactoryTest.kt
Labels: feature

#5777 MACRO: fix groups substitution
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix, performance

#5484 REF: Support reexports in move single file refactoring
  src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMovePathHelper.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileReexportTest.kt
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/after/lib.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/before/lib.rs
Labels: feature

#5790 Avoid resolve in `RsVisible.isPublic` for restricted visibility
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumVariant.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
Labels: internal

#5779 Fix mod declarations with #[path = "mod.rs"] attribute
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
Labels: fix

#5690 Introduce `Crate`, `CrateGraphService`
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
  src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunConfigurationProducer.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/MakePublicFix.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/icons/RsIconProvider.kt
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/DeriveCopyFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/crate/CrateGraphService.kt
  src/main/kotlin/org/rust/lang/core/crate/CratePersistentId.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/Util.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsExternCrateReexportIndex.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/kotlin/org/rust/stdext/Collections.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: fix, internal

#5758 COMP: true/false completion for bool values
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsBoolCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsBoolCompletionTest.kt
Labels: feature

#5793 CI: enable GitHub actions to merge PRs
  .github/workflows/check.yml
  .travis.yml
  README.md
  appveyor.yml
  bors.toml
Labels: internal

#5797 Disallow dynamic plugin unloading
  src/201/resources/META-INF/platform-core.xml
  src/202/main/kotlin/org/rust/ide/dynamic/RsDynamicPluginListener.kt
  src/202/main/resources/META-INF/platform-core.xml
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#5798 INSP: detect E0601 in build scripts
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
Labels: feature

#5782 Get rid of `PackageOrigin.TRANSITIVE_DEPENDENCY`
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/PackageOrigin.kt
  src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
Labels: internal

#5796 MACRO: resolve `$crate` via hygiene
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/macros/RsErrorChainMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Labels: fix

#5808 TY: support associated type bounds in paths
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: feature

#5809 TY: fix nested projections normalization
  src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#5810 ACT: replace `IntellijRustDollarCrate` with a crate name in `show macro expansion` action
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
Labels: fix

#5451 INT: add Import for intention
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/intentions/AddImportIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/AddImportIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddImportIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddImportIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/AddImportIntentionTest.kt
Labels: feature

#5659 COMP: add colon after struct literal field if no matching binding is found
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPartialParseCompletionTest.kt
Labels: feature

#5733 TY: infer Try impl for try expressions
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: feature

#5766 INSP: attach module without a parent to a parent module in AttachFileToModuleFix
  src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt
  src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt
Labels: fix

#5660 COMP: offer only struct fields in struct pat
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: feature

#5811 INSP: add support for trait refs in RsWrongTypeArgumentsNumberInspection
  src/main/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
Labels: feature

#5825 COMP: offer rest in struct pats
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsStructPatRestCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStructPatRestCompletionTest.kt
Labels: feature

#5820 INSP: suppress snake_case naming lint for #[no_mangle] functions
  src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt
  src/test/kotlin/org/rust/ide/inspections/naming/RsFunctionNamingInspectionTest.kt
Labels: feature

#5824 TY: exclude negative impls from type inference
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#5812 TY: fix self substitution in bounds
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#5822 Don't provide color highlighting in batch mode
  common/src/test/kotlin/com/intellij/ide/annotator/AnnotationTestFixtureBase.kt
  common/src/test/kotlin/com/intellij/ide/annotator/BatchMode.kt
  common/src/test/kotlin/com/intellij/utils.kt
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
  intellij-toml/src/main/kotlin/org/toml/ide/annotator/TomlHighlightingAnnotator.kt
  intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotationTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotationTestFixture.kt
  intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotatorTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlHighlightingAnnotatorTest.kt
  src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestFixture.kt
  src/test/kotlin/org/rust/ide/annotator/RsAnnotatorTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt
  src/test/kotlin/org/rust/ide/inspections/RsMultipleInspectionsTestBase.kt
Labels: fix

#5789 Don't create checkboxes in inlay hint settings manually
  src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
Labels: fix

#5837 TY: fix `?` try expr for complex types
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#5840 CI: allow triggering github workflow from UI
  .github/workflows/check.yml
  .github/workflows/release-branch.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  MAINTAINING.md
  scripts/release-actions.py
Labels: internal
