Repository intellij-rust/intellij-rust, pull requests merged in 2020-02, with the labels that each got.

#4783 TYPE: Display ?Sized properly for impl blocks
  src/main/kotlin/org/rust/ide/presentation/Utils.kt
  src/test/kotlin/org/rust/ide/structure/RsStructureViewTest.kt
Labels: fix

#4879 REPL: Hide tool window by default
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleRunnerFactory.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleToolWindow.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleToolWindowFactory.kt
  src/main/kotlin/org/rust/ide/console/RunRustConsoleAction.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#4880 REPL: Don't add commands with errors to completion context
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/Evcxr.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleExecuteActionHandler.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleView.kt
Labels: fix

#4847 ANN&REF: add annotations to leafs when highlighting leafs
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
Labels: fix

#4932 INT: use text with aliases in Type Info intention
  src/main/kotlin/org/rust/ide/hints/RsExpressionTypeProvider.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/test/kotlin/org/rust/ide/hints/RsExpressionTypeProviderTest.kt
Labels: fix

#4939 RUN: Fix code coverage runner on 2020.1
  src/201/main/kotlin/org/rust/cargo/runconfig/RsDefaultProgramRunnerBase.kt
Labels: fix

#4950 PERF&GRAM: replace `PathIdent` with external rule
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
Labels: performance

#4952 RES&TY: support enum type aliases
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: feature

#4925 PERF: don't parse function bodies during indexing
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
  src/main/kotlin/org/rust/ide/hints/RsDeclarationRangeHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
  src/test/kotlin/org/rust/lang/core/stubs/RsStubTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerformanceTest.kt
  src/test/kotlin/org/rustSlowTests/RsLazyCodeBlockIsNotExpandedDuringStubBuildingTest.kt
Labels: performance

#4938 INT: add support for type aliases in ImplementMembersFix
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#4919 ACT: Show cargo tool window after attaching a cargo project
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
Labels: fix

#4913 RES: resolve/completion for trait object inherent impl
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#4849 TY: Fix type checking for async blocks
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
Labels: fix

#4910 INT: fixed ImplementMembersFix for Fn type
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#4955 GRAM: fix `crate`-qualified path in tuple fields
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/visibility.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/visibility.txt
Labels: fix

#4956 GRAM: parse `default` keyword after visibility
  src/main/grammars/RustParser.bnf
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impls.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impls.txt
Labels: internal

#4958 TYPE: render type arguments of type aliases in inlay hints in proper way
  src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
  src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt
Labels: fix

#4961 TY: normalize trait bounds
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#4964 RUN: introduce id for cargo configuration factory
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt
Labels: internal

#3869 ANN:Format macros syntax support
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/colors/RsColors.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: feature

#4900 INT: handle raw identifiers in AddStructFieldsFix
  src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
Labels: fix

#4977 INT: handle raw identifiers in ImplementMembersFix
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#4982 Provide correct title for code folding settings panel
  src/main/kotlin/org/rust/ide/folding/RsCodeFoldingOptionsProvider.kt
Labels: fix

#4881 REPL: Add more actions
  src/main/kotlin/org/rust/ide/console/RsConsoleActions.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
Labels: feature

#4971 REPL: Fix macro completion inside Rust Console
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
Labels: fix

#4990 RES&MACRO: evaluate `cfg` in macro resolve
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: feature

#5003 CI: initial version of nightly publish workflow
  .github/workflows/publish-rust-nightly.yml
  build.gradle.kts
  gradle.properties
Labels: internal

#5019 INT: fix ConvertToNamedFields handling of function calls
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt
Labels: fix
