Repository intellij-rust/intellij-rust, pull requests merged in 2020-03, with the labels that each got.

#5033 REF: use initialization shorthand after rename
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Labels: feature

#4978 INT: build default values for constants in ImplementMembersFix
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: feature

#4944 INT: AddConstructor intention
  src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generateConstructor/ui.kt
  src/test/kotlin/org/rust/ide/refactoring/GenerateConstructorActionTest.kt
Labels: feature

#5050 GRAM: better error recovery in some cases
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/ElideLifetimesFix.kt
  src/main/kotlin/org/rust/ide/intentions/SetMutableIntention.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/bounds.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/bounds.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/impl_body.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/items.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/items.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/no_lifetime_bounds_in_generic_args.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/types.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/types.txt
Labels: feature

#5064 PERF&GRAM: parser optimizations
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt
  src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/diesel_macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/oror.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/shifts.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/shifts.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_expr_fields.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_pat.txt
Labels: performance

#4996 REPL: Replace custom command history implementation with default one
  src/main/kotlin/org/rust/ide/console/CommandHistory.kt
  src/main/kotlin/org/rust/ide/console/HistoryKeyListener.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleExecuteActionHandler.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleHistoryModelProvider.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleRootType.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleView.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#4242 TY: Initial type inference for const generics
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/CheckMatchUtils.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/Constructor.kt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/PatternKind.kt
  src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/utils/BooleanExprSimplifier.kt
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBlockExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/Kind.kt
  src/main/kotlin/org/rust/lang/core/types/Substitution.kt
  src/main/kotlin/org/rust/lang/core/types/consts/Const.kt
  src/main/kotlin/org/rust/lang/core/types/consts/CtConstParameter.kt
  src/main/kotlin/org/rust/lang/core/types/consts/CtInfer.kt
  src/main/kotlin/org/rust/lang/core/types/consts/CtUnevaluated.kt
  src/main/kotlin/org/rust/lang/core/types/consts/CtUnknown.kt
  src/main/kotlin/org/rust/lang/core/types/consts/CtValue.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/core/types/regions/ReEarlyBound.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyInfer.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExpr.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprBuilder.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprEvaluator.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ExprValue.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/RsConstExprEvaluator.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/Utils.kt
  src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: feature

#5079 TY: better disambiguate inherent/trait methods & assoc items
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
Labels: fix

#4872 PERF&MACRO: Introduce MacroExpansionVFS
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachesInvalidator.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/main/kotlin/org/rust/stdext/path.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
Labels: performance

#5084 MACRO: Avoid infinite recursion in macros control flow
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: fix

#5009 GRAM: fixed parsing of lifetime bound on Fn bound when it returns reference
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/polybounds.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/polybounds.txt
Labels: fix

#5066 REPL: Fix for windows (use new escape characters)
  src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt
Labels: fix

#5020 INT: support type aliases in DestructureIntention
  src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/intentions/DestructureIntentionTest.kt
Labels: fix

#5085 PERF&STUB: store `cfg` existence flags to stubs
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
Labels: performance

#5082 MACRO: Process nested macros in `descendantsWithMacrosOfType`
  src/main/kotlin/org/rust/lang/core/psi/RsWithMacroExpansionsRecursiveElementWalkingVisitor.kt
  src/main/kotlin/org/rust/openapiext/psi.kt
  src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
Labels: fix

#5057 FMT: add newline between items inside function
  src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
  src/test/kotlin/org/rust/ide/formatter/RsFormatterLineBreaksTest.kt
Labels: fix

#5012 REF: handle async functions in ExtractFunction refactoring
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldLookup.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#5103 QDOC: improve generation of external documentation links
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt
  src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt
Labels: fix

#5107 GRAM: fix `&raw` expression parsing
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/raw_operator.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/raw_operator.txt
Labels: fix

#5087 INT: Add "Change return type" fix
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
Labels: feature

#5053 REF: Fix introduce variable when first expression is inside nested block
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
Labels: fix

#4936 RES: support impls for aliased types
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: feature

#5101 PERF&MACRO: use refresh-based VFS batch
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
  src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
Labels: performance

#5115 GRAM & ANN: Parse const trait impls and annotate them as experimental
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impls.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impls.txt
Labels: feature

#5124 INSP: improve unresolved reference inspection
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportHintFix.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: feature

#5120 ANN: Detect E0451: constructing struct which has private field
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
Labels: feature

#5037 INT: add ExtractEnumVariantIntention
  src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/ExtractEnumVariantIntention/after.rs.template
  src/main/resources/intentionDescriptions/ExtractEnumVariantIntention/before.rs.template
  src/main/resources/intentionDescriptions/ExtractEnumVariantIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntentionTest.kt
Labels: feature

#5131 TOML: add plugin icons
  intellij-toml/src/main/resources/META-INF/pluginIcon.svg
  intellij-toml/src/main/resources/META-INF/pluginIcon_dark.svg
Labels: feature

#5135 Do not add directory as source/excluded entries if it doesn't exist
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt
Labels: fix

#5139 COMP: Provide completion for `union` keyword
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: fix

#4998 REPL: Add variables view
  src/main/kotlin/org/rust/ide/console/RsConsoleActions.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleOptions.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleVariablesView.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleView.kt
  src/main/kotlin/org/rust/ide/presentation/Utils.kt
  src/main/kotlin/org/rust/ide/structure/RsPsiStructureViewFactory.kt
  src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/structure/RsStructureViewTest.kt
Labels: feature

#5150 ANN: Fix false positive E0451 when constructing enum
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#5142 INT: replace usages of struct literals and tuple constructors in ExtractEnumVariantIntention
  src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntentionTest.kt
Labels: fix

#5149 COMP: fix println postfix template for string variables
  src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
  src/test/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplateTest.kt
Labels: fix

#5156 COMP: prefer Display before Debug in PrintlnPostfixTemplate
  src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
  src/test/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplateTest.kt
Labels: fix
