Repository intellij-rust/intellij-rust, pull requests merged in 2020-01, with the labels that each got.

#4825 INT: don't combile pub and non-pub uses into one in "nest use statements"
  src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
  src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
Labels: fix

#4834 CPP-18528: provide help id for cargo command configuration type in IDEA and CLion
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt
Labels: fix

#4818 TY: provide `Copy` and `Clone` impls for array types
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
Labels: fix

#4823 Remove CLion dependencies from `debugger` module
  build.gradle.kts
  clion/src/main/kotlin/org/rust/clion/debugger/runconfig/RsCLionDebugRunner.kt
  clion/src/main/kotlin/org/rust/clion/debugger/runconfig/RsCLionDebugRunnerUtils.kt
  clion/src/main/kotlin/org/rust/clion/debugger/runconfig/legacy/RsCLionDebugRunnerLegacy.kt
  clion/src/main/resources/META-INF/clion-only.xml
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerBase.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacy.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacyBase.kt
  debugger/src/main/resources/META-INF/debugger-only.xml
  gradle-192.properties
  gradle-193.properties
Labels: internal

#4816 INT: drop "Remove parentheses from expression" intention
  src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/RemoveRedundantParenthesesFix.kt
  src/main/kotlin/org/rust/ide/intentions/RemoveParenthesesFromExprIntention.kt
  src/main/resources/META-INF/core.xml
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveRedundantParenthesesFixTest.kt
  src/test/kotlin/org/rust/ide/intentions/RemoveParenthesesFromExprIntentionTest.kt
Labels: fix

#4782 PERF: Prevent switches to AST when processing array type
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: fix

#4807 Add "import filtering rule" for "find usages"
  src/main/kotlin/org/rust/ide/search/RsImportFilteringRule.kt
  src/main/resources/META-INF/core.xml
Labels: feature

#4102 CARGO: Hide Cargo tool window button for non-Rust/non-Cargo projects
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#4860 Fix PSI produced by PrintlnPostfixTemplate
  src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
Labels: fix

#4877 PERF: make macro call body reparseable
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/LazyElements.kt
Labels: internal

#4875 PERF: do not touch PSI in `shouldCreateStub`
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/formatter/impl/utils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/openapiext/ast.kt
Labels: performance

#4885 Fix potential memory leak in suppress quick fix
  src/main/kotlin/org/rust/ide/inspections/RsLintInspection.kt
Labels: performance

#4812 COMP: guess proper type of braces while macro call completion
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/completion/RsMacroBracketCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
Labels: feature

#4886 TOML: use `fileType` EP instead of deprecated `TomlFileTypeFactory`
  intellij-toml/src/main/kotlin/org/toml/lang/TomlFileTypeFactory.kt
  intellij-toml/src/main/resources/META-INF/plugin.xml
  intellij-toml/src/test/kotlin/org/toml/lang/TomlFileTypeTest.kt
Labels: internal

#4772 INT: select unimplemented after Implement members fix
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: feature

#4862 PERF&GRAM: lazy parseable & reparseable code block
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/impl_body.txt
Labels: performance
