Repository intellij-rust/intellij-rust, pull requests merged in 2020-04, with the labels that each got.

#5168 REPL: Show icon in console
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
Labels: feature

#5143 COMP: Insert trailing comma in match after "Complete current statement"
  src/main/kotlin/org/rust/ide/typing/assist/CommaFixer.kt
  src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
  src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt
Labels: fix

#5179 Fix local history
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: fix

#4972 INT: don't generate useless match arm for irrefutable patterns in IfLetToMatchIntention
  src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
  src/test/kotlin/org/rust/ide/intentions/IfLetToMatchIntentionTest.kt
Labels: fix

#5144 INT: don't import inner types of type aliases in ImplementMembers intention
  src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#5137 GRD: make 2020.1 main platform for development
  build.gradle.kts
  clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
  gradle-201.properties
  gradle.properties
  grazie/src/201/test/kotlin/org/rust/grazie/RsGrammarCheckingTestBase.kt
  src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
  src/main/kotlin/org/rust/cargo/icons/CargoIcons.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
  src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceParameter/ui.kt
  src/main/kotlin/org/rust/ide/template/RsLiveTemplatesProvider.kt
  src/main/kotlin/org/rust/ide/todo/RsTodoApplicationComponent.kt
  src/main/kotlin/org/rust/ide/update/UpdateComponent.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: internal

#5199 Recognize irrefutable constant patterns
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/test/kotlin/org/rust/ide/intentions/IfLetToMatchIntentionTest.kt
Labels: fix

#5076 RUN: Set TERM variable and terminal's width if terminal emulation is enabled
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/Evcxr.kt
Labels: fix

#5204 ANN: highlight exit points if last statement is loop
  src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
  src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
  src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsExtraSemicolonInspectionTest.kt
Labels: feature

#5130 ANN: Fix union pattern match error
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Labels: fix

#5133 Fix `Add _ pattern` and` Add remaining patterns` generated code being incorrect
  src/main/kotlin/org/rust/ide/inspections/fixes/AddRemainingArmsFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddWildcardArmFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
Labels: fix

#5170 REPL: Use Ctrl+Enter as shortcut for executing instead of Enter
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
Labels: fix

#5157 INSP: add RsRedundantElseInspection
  src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsRedundantElse.html
  src/test/kotlin/org/rust/ide/inspections/RsRedundantElseInspectionTest.kt
Labels: feature

#5220 Fix stdlib detection when working with rust-lang/rust project
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#5161 INT: Fix SpecifyTypeExplicitlyIntention on `ref` pat bindings
  src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
  src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
Labels: fix

#5226 TY: Type inference for subslice patterns
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
Labels: feature

#5229 Fix file type mapping for Rust file in IDEA 2020.1
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#5222 Get rid of some project/application components
  src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingPassFactoryRegistrar.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#5173 REPL: Fix IndexNotReadyException when execute command during dumb mode
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
Labels: internal

#5244 REPL: Fix for windows (update evcxr)
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt
  src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt
Labels: fix

#5257 TYPE: don't remove curly braces after insertion paired one
  src/main/kotlin/org/rust/ide/formatter/processors/RsSingleImportRemoveBracesFormatProcessor.kt
  src/main/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseGroup.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/formatter/RsSingleImportRemoveBracesFormatProcessorTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
  src/test/kotlin/org/rust/ide/surroundWith/RsSurroundWithTest.kt
Labels: fix

#5184 COMP: add block comment suffix after enter
  src/main/kotlin/org/rust/ide/commenter/RsCommenter.kt
  src/test/kotlin/org/rust/ide/commenter/RsCommenterTest.kt
Labels: feature

#5252 FMT: better visibility formatting
  src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
  src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
Labels: fix

#5250 Make all extension points of Rust plugin dynamic
  debugger/src/main/resources/META-INF/debugger-only.xml
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#5236 REF: don't remove empty lines in "Extract function"
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#5245 MACRO: turn MacroExpansionManager into a service
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/RsGeneratedSourcesFilter.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoPackageIndex.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
  src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
  src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt
  src/main/kotlin/org/rust/ide/search/RsWithMacrosProjectScope.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsIndexableSetContributor.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionWritingAccessProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
Labels: fix

#5195 Add support for blacklisting to RsInlayParameterHintsProvider
  src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
Labels: feature

#5200 DBG: provide debugger support outside of CLion
  build.gradle.kts
  clion/src/main/resources/META-INF/clion-only.xml
  debugger/src/193/main/kotlin/org/rust/debugger/settings/CompatUtils.kt
  debugger/src/193/main/resources/META-INF/platform-debugger-only.xml
  debugger/src/201/main/kotlin/org/rust/debugger/RsDebuggerDriverConfigurationProviderImpl.kt
  debugger/src/201/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/201/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/201/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtilsExt.kt
  debugger/src/201/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacy.kt
  debugger/src/201/main/kotlin/org/rust/debugger/settings/CompatUtils.kt
  debugger/src/201/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt
  debugger/src/201/main/resources/META-INF/platform-debugger-only.xml
  debugger/src/201/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerDataViewConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
  debugger/src/main/resources/META-INF/core-debugger-only.xml
  debugger/src/main/resources/META-INF/debugger-only.xml
  debugger/src/main/resources/META-INF/native-debug-only.xml
  debugger/src/test/resources/META-INF/plugin.xml
  plugin/src/main/resources/META-INF/plugin.xml
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
Labels: feature

#5147 INT: add support for `extern` keyword in ImplementMembersFix
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#5281 INSP: proper display name for `RsRedundantElseInspection`
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#5288 RUN: start build project in EDT
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
Labels: fix

#5279 CI: provide workflow for beta and stable releases
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  MAINTAINING.md
  scripts/Pipfile
  scripts/common.py
  scripts/get_release_branch.py
  scripts/make_release_branch.py
  scripts/release-actions.py
  scripts/update-changelog-link.py
Labels: internal

#5297 PERF: less recursive `RsExpandedElement.getContextImpl`
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
Labels: performance

#5293 REF: don't rename non rust directories
  src/main/kotlin/org/rust/ide/refactoring/RsDirectoryRenameProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Labels: fix

#5296 Fix "find usages" action with `include!()` macros and `pub(crate)` items in crate root
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#5292 FIX: search for parent expression recursively in SurroundWithUnsafeFix
  src/main/kotlin/org/rust/ide/annotator/fixes/SurroundWithUnsafeFix.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeTest.kt
Labels: fix

#5261 MACRO: properly do "Invalidate caches & Restart"
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachesInvalidator.kt
Labels: fix

#5197 TYPE: Add type hints to type placeholders
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTestBase.kt
Labels: feature

#5270 DBG: add support for pretty printing nonzero numbers
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  prettyPrinters/rust_types.py
  pretty_printers_tests/src/test_runner.rs
  pretty_printers_tests/tests/nonzero.rs
Labels: feature
