Repository intellij-rust/intellij-rust, pull requests merged in 2020-06, with the labels that each got.

#5430 COMP: add file system completion for string literals in path context
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: feature

#5493 GRAM: Fix parsing `crate` at the beginning of macro call as vis modifier
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/visibility.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/visibility.txt
Labels: fix

#5489 TYPE: Fix run icon display
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunConfigurationProducer.kt
Labels: fix

#5501 Fix UI freezes caused by chain method hints
  src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
Labels: performance

#5500 MACRO: more consistency checks
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
  src/main/kotlin/org/rust/lang/core/macros/VfsInternals.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/kotlin/org/rust/stdext/HashCode.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
Labels: fix

#5496 MACRO: enable new macro expansion engine in nightly builds
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#5486 RUN: add --ignored to command line for ignored tests
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ignored_test_is_run_with_ignored_option.xml
Labels: feature

#5472 UI: sort packages and targets alphabetically in Cargo tool window
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectTreeStructure.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
Labels: feature

#5495 Add postfix templates for Result/Option wrapping
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/resources/postfixTemplates/ErrPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/ErrPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/ErrPostfixTemplate/description.html
  src/main/resources/postfixTemplates/OkPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/OkPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/OkPostfixTemplate/description.html
  src/main/resources/postfixTemplates/SomePostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/SomePostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/SomePostfixTemplate/description.html
  src/test/kotlin/org/rust/ide/template/postfix/ErrPostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/OkPostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/SomePostfixTemplateTest.kt
Labels: feature

#5481 ANN: check if the `main` function exists [E0601]
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddMainFnFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsMainFunctionNotFound.html
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/fixes/AddMainFnFixTest.kt
Labels: feature

#4489 Assert we do not access indices during document committing
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroCallIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsExternCrateReexportIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsFeatureIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsNamedElementIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
Labels: internal

#4993 Place the caret near a type when navigating to an impl
  src/main/kotlin/org/rust/ide/intentions/AddImplIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
Labels: feature

#5521 FIX: add unsafe now also works inside loops and conditions
  src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeTest.kt
Labels: fix

#5514 Support 2020.2 platform
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  .travis.yml
  build.gradle.kts
  clion/src/201/main/kotlin/org/rust/clion/profiler/dtrace/compatUtils.kt
  clion/src/202/main/kotlin/org/rust/clion/profiler/dtrace/compatUtils.kt
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceNavigatableNativeCall.kt
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
  common/src/test/kotlin/com/intellij/ide/annotator/AnnotationTestFixtureBase.kt
  debugger/src/201/main/kotlin/org/rust/debugger/lang/RsDebuggerEditorsExtension.kt
  debugger/src/201/main/resources/META-INF/platform-core-debugger-only.xml
  debugger/src/202/main/kotlin/org/rust/debugger/lang/RsDebuggerEditorsExtension.kt
  debugger/src/202/main/resources/META-INF/platform-core-debugger-only.xml
  debugger/src/main/kotlin/org/rust/debugger/PrettyPrinters.kt
  debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerEditorsExtensionBase.kt
  debugger/src/main/resources/META-INF/core-debugger-only.xml
  gradle-201.properties
  gradle-202.properties
  gradle.properties
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
  src/201/main/kotlin/org/rust/ide/highlight/compatUtils.kt
  src/201/main/kotlin/org/rust/ide/lineMarkers/compatUtils.kt
  src/201/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/201/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt
  src/201/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildTest.kt
  src/201/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
  src/202/main/kotlin/org/rust/ide/highlight/compatUtils.kt
  src/202/main/kotlin/org/rust/ide/lineMarkers/compatUtils.kt
  src/202/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
  src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
  src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsCrateDocLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsMethodLineSeparatorProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsRecursiveCallLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProvider.kt
  src/main/kotlin/org/rust/lang/core/macros/VfsInternals.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/openapiext/ProjectCache.kt
  src/test/kotlin/org/rust/IgnoreInPlatform.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
  src/test/kotlin/org/rust/ide/intentions/RsIntentionDocumentationTest.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_project_root.xml
  toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
Labels: feature

#5490 INSP: add attach file to module quick fix
  src/main/kotlin/org/rust/ide/inspections/RsDetachedFileInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt
  src/main/kotlin/org/rust/ide/notifications/DetachedFileNotificationProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsDetachedFile.html
  src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt
  src/test/kotlin/org/rust/ide/notifications/DetachedFileNotificationProviderTest.kt
Labels: feature

#5538 Fix go-to-declaration from assoc type binding on 2020.2
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAssocTypeBinding.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt
Labels: fix

#5354 INSP: simplify and modernize RsWrongTypeArgumentsNumberInspection
  src/main/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongTypeParametersNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeArguments.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsWrongTypeArgumentsNumber.html
  src/main/resources/inspectionDescriptions/RsWrongTypeParametersNumber.html
  src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongTypeParametersNumberInspectionTest.kt
Labels: feature

#5549 RUN: Get rid of `Show test tool window` and `Show stdout/stderr in tests (and disable test tool window)` options
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/SerializationUtils.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/BenchRunConfigurationProducerTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/ExecutableRunConfigurationProducerTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_configuration_uses_default_environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_fn_is_more_specific_than_main_or_test_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_adds_bin_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_ignores_selected_files_that_contain_no_benches.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_uses_complete_function_path.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_annotated_functions.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_benches_source_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_directories_inside_benches_source_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_module_declarations.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_modules.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_multiple_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_nested_modules_1.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_nested_modules_2.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_root_module.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executable_configuration_uses_default_environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executable_producer_works_for_bin.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executable_producer_works_for_example.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/hyphen_in_name_works.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ignored_test_is_run_with_ignored_option.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_bench_fn.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_bench_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_test_fn.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_test_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_mod_is_more_specific_than_test_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/meaningful_bench_configuration_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/meaningful_test_configuration_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/take_into_account_path_attribute.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_configuration_uses_default_environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_fn_is_more_specific_than_main_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_mod_decl_is_more_specific_than_main_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_mod_is_more_specific_than_bench_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_adds_bin_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_ignores_selected_files_that_contain_no_tests.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_uses_complete_function_path.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_annotated_functions.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_directories_inside_tests_source_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_module_declarations.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_modules.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_multiple_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_nested_modules_1.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_nested_modules_2.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_project_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_root_module.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_tests_source_root.xml
Labels: fix

#5547 INSP: do not trigger RsMainFunctionNotFoundInspection for files with a root error
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
Labels: fix

#5436 ANN: support E0435 error detection
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#5462 Improve `RemoveTypeArguments`
  src/main/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeArguments.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
Labels: feature

#5313 REF: allow the user to select mutability of parameters in ExtractFunction
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/ExtractFunctionParameterTablePanel.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: feature

#5583 Fix exception during code folding of invalid macro calls
  src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
  src/test/resources/org/rust/ide/folding/fixtures/macro_brace_arg.rs
Labels: fix

#5584 Fix possible NPEs in some LocalQuickFix.getText()
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveRefFix.kt
Labels: fix

#5591 Fix PsiInvalidElementAccessException in RsExternalLinterPass
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
Labels: fix

#5579 IDE: show parent folder name in editor tab for lib.rs, main.rs and Cargo.toml
  src/main/kotlin/org/rust/ide/miscExtensions/RsFileTabTitleProvider.kt
  src/main/kotlin/org/rust/ide/miscExtensions/RsModTabTitleProvider.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#5550 INSP: add quick fix to convert immutable reference to mutable reference
  src/main/kotlin/org/rust/ide/inspections/fixes/ChangeRefToMutableFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeRefToMutableFixTest.kt
Labels: feature

#5595 Fix PsiInvalidElementAccessException in structure view
  src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
Labels: fix

#5596 Fix IndexNotReadyException in RustfmtListener
  src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
Labels: fix

#5574 FIX: correctly complete parentheses for Fn like traits
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#5597 Fix macro expansion infinite progress on 2020.2
  src/main/kotlin/org/rust/openapiext/DelayedBackgroundableProcessIndicator.kt
Labels: fix

#5375 INSP: check if supertrait is implemented
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#5599 ANN: fix false positive of impl Trait in associated type binding
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#5586 INT: add intention to introduce local variable
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/IntroduceLocalVariableIntention/after.rs.template
  src/main/resources/intentionDescriptions/IntroduceLocalVariableIntention/before.rs.template
  src/main/resources/intentionDescriptions/IntroduceLocalVariableIntention/description.html
Labels: feature

#5580 INT: enable MatchToIfLetIntention for irrefutable patterns
  src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt
  src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
Labels: feature

#5557 INSP: add remove variable quick fix to liveness inspection
  src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveVariableFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
Labels: feature

#5523 Fix unable to join doc comment lines
  src/main/kotlin/org/rust/ide/actions/RsJoinLinesHandler.kt
  src/main/kotlin/org/rust/ide/actions/RsJoinRawLinesHandler.kt
  src/test/kotlin/org/rust/ide/actions/RsJoinLinesHandlerTest.kt
Labels: fix

#5466 INSP: Fix non_exhaustive false positive in same crate
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/inspections/checkMatch/RsMatchCheckInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
Labels: fix

#5571 INSP: Improve lint check
  src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/RsLintInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsLintLevel.kt
  src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsLintLevelTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
Labels: feature

#5603 RES: take into account namespace during shadowing
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#5611 RUN: Unescape test output
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTestBase.kt
Labels: fix

#5618 REF: do refactoring and inplace rename within a single write command
  src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
Labels: fix

#5582 ANN: Enhanced Repr error detection
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/RemoveReprValueFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveReprValueFixTest.kt
Labels: feature

#5622 Provide issue/pr navigation in git log in IDE
  .idea/vcs.xml
Labels: internal

#5570 Self enum #4980
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#5614 INT: convert UFCS to method call
  src/main/kotlin/org/rust/ide/intentions/ConvertUFCSToMethodCallIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/ConvertUFCSToMethodCallIntention/after.rs.template
  src/main/resources/intentionDescriptions/ConvertUFCSToMethodCallIntention/before.rs.template
  src/main/resources/intentionDescriptions/ConvertUFCSToMethodCallIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ConvertUFCSToMethodCallTest.kt
Labels: feature

#5601 INT: convert method call to UFCS
  src/main/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/ConvertMethodCallToUFCSIntention/after.rs.template
  src/main/resources/intentionDescriptions/ConvertMethodCallToUFCSIntention/before.rs.template
  src/main/resources/intentionDescriptions/ConvertMethodCallToUFCSIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSTest.kt
Labels: feature

#5623 MACRO: fix `#[macro_export(local_inner_macros)]`
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Labels: bug

#5561 INSP: add remove parameter quick fix to liveness inspection
  src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveParameterFix.kt
  src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
Labels: feature

#5629 Enable proofreading in commit messages
  .idea/vcs.xml
Labels: internal

#5535 DBG: Enable CLion debug runners when using MSVC toolchain on 2020.2
  clion/src/main/kotlin/org/rust/clion/debugger/runconfig/RsCLionDebugRunner.kt
  clion/src/main/kotlin/org/rust/clion/debugger/runconfig/RsCLionDebugRunnerUtils.kt
  clion/src/main/kotlin/org/rust/clion/debugger/runconfig/legacy/RsCLionDebugRunnerLegacy.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacyBase.kt
  prettyPrinters/rust_types.py
  src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
Labels: feature

#5640 Properly escape types in annotations for 2020.2
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
Labels: fix

#5612 ANN: use more precise error annotations for missing/extraneous function call arguments
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#5626 REF: enable move refactoring
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#5649 CI: release nightly toml from github actions
  .github/workflows/rust-nightly.yml
  build.gradle.kts
  scripts/common.py
  scripts/get_tag_commit.py
  scripts/save_tag.py
Labels: internal

#5455 REF: Basic version of move top-level items refactoring
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMemberSelectionPanel.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt
  src/main/kotlin/org/rust/openapiext/ui.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#5653 QDOC: render aliased types for let bindings
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
Labels: feature

#5637 INT: fix `Introduce Variable` intention
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt
  src/test/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntentionTest.kt
Labels: fix

#5671 Fix cyclic stdlib dependencies
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
Labels: internal

#5672 Add `custom-build` cargo target kind
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectTreeStructure.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
Labels: internal

#5670 Fix move analysis of path assignments
  src/main/kotlin/org/rust/lang/core/types/borrowck/MoveData.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: fix

#5674 PERF: slightly optimize `RsModulesIndex`
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
Labels: performance

#5673 Parse `DepKind` from `cargo metadata`
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
Labels: internal

#5679 Fix infinite cargo refresh on openid 0.4.0
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherIntegrationTest.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherTest.kt
Labels: fix

#5624 Initial support of or_patterns
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsAnnotationHolder.kt
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/hints/RsImplementationTextSelectioner.kt
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt
  src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt
  src/main/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProvider.kt
  src/main/kotlin/org/rust/ide/presentation/PresentationInfo.kt
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsCondition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMatchArm.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/blocks.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/conditions.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/conditions.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/loops.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/match.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/match_call_ambiguity.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/patterns.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/patterns.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/match_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_pat.txt
Labels: feature
