Repository intellij-rust/intellij-rust, pull requests merged in 2020-10, with the labels that each got.

#6172 UI: use recommended guidelines for settings UI
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsConfigurableBase.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
Labels: fix

#6163 INSP: improve integration with Grazie plugin
  build.gradle.kts
  grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
Labels: fix

#6184 Fix #6183
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddSelfFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/ElideLifetimesFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/inspections/fixes/AddMutableFixTest.kt
Labels: fix

#6177 GRAM: support `tuple.0.0` as tuple indexing
  src/main/grammars/RustLexer.flex
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/resources/org/rust/lang/core/lexer/fixtures/numbers.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
Labels: fix

#6188 CI: improve presentation of regression annotations
  scripts/calculate_regressions.py
  src/test/kotlin/org/rustPerformanceTests/CustomRealProjectAnalysisTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
Labels: internal

#5444 RUN: resolve stdlib and Cargo source code hyperlinks in backtrace
  src/main/kotlin/org/rust/cargo/runconfig/filters/RegexpFileLinkFilter.kt
  src/test/kotlin/org/rust/cargo/runconfig/filters/HighlightFilterTestBase.kt
  src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterCargoTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/filters/RsConsoleFilterTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/filters/RsPanicFilterTest.kt
Labels: feature

#6212 MACRO: introduce shared persistent cache for macro expansion
  src/202/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/203/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionStubsProvider.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
  src/main/kotlin/org/rust/stdext/HashCode.kt
  src/main/kotlin/org/rust/stdext/path.kt
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#6202 TOML: recover parser on errors in arrays
  intellij-toml/src/main/grammars/TomlParser.bnf
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.toml
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.txt
Labels: fix

#6223 GRD: update IDE dependencies
  build.gradle.kts
  gradle-202.properties
  gradle-203.properties
  src/202/main/kotlin/org/rust/lang/core/resolve/ref/compatUtils.kt
  src/203/main/kotlin/org/rust/lang/core/resolve/ref/compatUtils.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
Labels: fix

#6221 T: introduce tests for intention scope
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
Labels: internal

#6196 INT: don't remove required parentheses in RemoveDbgIntention
  src/main/kotlin/org/rust/ide/intentions/RemoveDbgIntention.kt
  src/test/kotlin/org/rust/ide/intentions/RemoveDbgIntentionTest.kt
Labels: fix

#5189 CARGO: Support configuring workspace features in `Cargo.toml`
  .idea/dictionaries/intellij_rust.xml
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/UserDisabledFeatures.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/UserDisabledFeaturesHolder.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
  src/main/kotlin/org/rust/cargo/project/workspace/FeatureGraph.kt
  src/main/kotlin/org/rust/cargo/project/workspace/PackageFeature.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
  src/main/kotlin/org/rust/ide/inspections/RsMissingFeaturesInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/EnableCargoFeaturesFix.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/utils/Graph.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsMissingFeatures.html
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoFeaturesModificationTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
  src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsMissingFeaturesInspectionTest.kt
  toml/src/main/kotlin/org/rust/toml/CargoFeatureLineMarkerProvider.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlMissingFeaturesInspection.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/inspectionDescriptions/CargoTomlMissingFeatures.html
  toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/CargoTomlLineMarkerProviderTestBase.kt
  toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlMissingFeaturesInspectionTest.kt
Labels: feature

#6248 Allow only LMB double-click for `targets` in the cargo tool window
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectsTree.kt
Labels: fix

#6250 UI: `Setup toolchain` action shows Rust settings dialog instead of configurable
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
Labels: fix

#5871 INSP: check if struct fields are not bound multiple times in struct pats [E0025]
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#6249 DBG: make NonZero printers compatible with Rust 1.48+
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/nonzero.rs
Labels: fix

#6258 Update HashMap/HashSet pretty-printers to Rust 1.47
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  pretty_printers_tests/tests/hash_map.rs
Labels: fix

#6264 GRD: generate code compatible with java 8 runtime
  build.gradle.kts
Labels: fix

#6242 CARGO: initial support for Sync tool window
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectActionBase.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectsAction.kt
  src/main/kotlin/org/rust/openapiext/CommandLineExt.kt
  src/main/kotlin/org/rust/openapiext/TaskResult.kt
  src/main/kotlin/org/rust/stdext/Concurrency.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
Labels: feature

#6106 REF: Improve newline handling in move items refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: fix

#6205 REPL: Clear variables view after :clear command
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleView.kt
Labels: feature

#6280 Refresh inlay hints when modifying cargo features
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#6253 INT: fix availability check in CreateFunctionIntention
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: fix

#6251 Simplify rustc version parsing
  src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/RustcVersion.kt
  src/test/kotlin/org/rust/cargo/toolchain/RustcVersionParsingTest.kt
Labels: fix

#6241 Name resolution 2.0
  src/202/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/203/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/main/kotlin/org/rust/cargo/CfgOptions.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiTreeChangeListener.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/DollarCrateUtil.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PathUtil.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/kotlin/org/rust/stdext/CompletableFuture.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
Labels: internal

#5646 COMP: add completion of lint attributes
  build.gradle.kts
  scripts/fetch_lints.py
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/ClippyLints.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/Lint.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RsClippyLintCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RsLintCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RsRustcLintCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RustcLints.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLintCompletionProviderTest.kt
Labels: feature

#6107 REF: Support move multiple files
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTestBase.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveMultipleFilesTest.kt
Labels: feature

#6267 DBG: support debugging on Windows outside of CLion
  README.md
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacy.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacyBase.kt
  debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
Labels: feature

#6204 RES: resolve cargo features in `Cargo.toml`
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlDependencyFeaturesReferenceProvider.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlNameResolution.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlReferenceContributor.kt
  toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlDependencyFeaturesReferenceProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlResolveTestBase.kt
Labels: feature

#6279 ANN: take into account workspace features in external linter
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Labels: fix

#6283 GRAM: improve parser recovering in several cases
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/fn.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/structs.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/structs.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/enum_vis.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/items.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/items.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/match_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/match_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/patterns.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/patterns.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_def.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_def.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_expr_fields.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_expr_fields.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_pat.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_pat.txt
Labels: fix

#6238 INSP: Check that match on uninhabited type cannot be unexhaustive
  src/main/kotlin/org/rust/ide/utils/checkMatch/CheckMatchUtils.kt
  src/main/kotlin/org/rust/ide/utils/checkMatch/Constructor.kt
  src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
Labels: fix

#6298 Fix control flow of async blocks
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: fix

#6285 GRAM: better parser recovery for incomplete paths (pin path)
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/highlight/RsRainbowVisitor.kt
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/intentions/AddCurlyBracesIntention.kt
  src/main/kotlin/org/rust/ide/intentions/AddImportIntention.kt
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt
  src/main/kotlin/org/rust/ide/todo/RsTodoSearcher.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RsLintCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPathReferenceElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsDeriveTraitReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PathUtil.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddCurlyBracesIntentionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStubOnlyCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
  src/test/kotlin/org/rust/lang/core/stubs/RsStubTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.txt
Labels: fix

#6305 COMP: simplify script for fetching Clippy lints
  scripts/fetch_lints.py
  src/main/kotlin/org/rust/lang/core/completion/lint/ClippyLints.kt
Labels: internal

#6314 ACT: provide proper rustc version by "Create New Issue" action
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
Labels: fix

#6315 T: run macro cleaning task synchronously in tests
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: internal

#5791 INSP: add inspection for E0364/E0365 errors
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsInvalidReexportErrorAnnotatorTest.kt
Labels: feature

#6318 INSP: It is not allowed to cast to a bool. (E0054)
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/inspections/RsCastToBoolInspection.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsCastToBool.html
  src/test/kotlin/org/rust/ide/inspections/RsCastToBoolInspectionTest.kt
Labels: feature

#6313 COMP: do not complete lints for paths starting with leading ::
  src/main/kotlin/org/rust/lang/core/completion/lint/RsLintCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLintCompletionProviderTest.kt
Labels: fix
