Repository intellij-rust/intellij-rust, pull requests merged in 2020-05, with the labels that each got.

#5155 Fix move analysis of struct literals with base expr
  src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: fix

#5317 TY: Trait object takes into account all trait bounds
  src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt
  src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/Kind.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
  src/test/kotlin/org/rust/ide/hints/RsExpressionTypeProviderTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: fix

#5308 COMP: add completion of angle brackets for generic types
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: feature

#5291 REF: change ExtractEnumVariant from an intention to a refactoring
  src/main/kotlin/org/rust/ide/intentions/ConvertStructIntentions.kt
  src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt
  src/main/kotlin/org/rust/ide/intentions/RsRefactoringAdaptorIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantAction.kt
  src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantProcessor.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt
Labels: feature, performance

#5320 TYPE: improve complete current statement action
  src/main/kotlin/org/rust/ide/typing/assist/AfterSemicolonEnterProcessor.kt
  src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
  src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt
Labels: fix

#5326 GRD: improve developer workflows
  .idea/runConfigurations/RunCLion.xml
  .idea/runConfigurations/RunIDEA.xml
  CONTRIBUTING.md
  build.gradle.kts
Labels: internal

#5251 MACRO: save MacroExpansionManager asynchronously
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/stdext/io.kt
Labels: fix

#5333 Fix. Ignore entire mod subtree if disabled `#[cfg]`
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: fix

#5304 Copy enum attributes in RsExtractEnumVariant
  src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt
Labels: feature

#5343 PERF&MACRO: optimize macro resolve
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: performance

#5335 Initial support of multiple module declarations of the same module
  src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
Labels: feature, fix

#5336 MACRO: support `include!` macro calls generated by another macro call
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt
  src/test/kotlin/org/rust/ide/notifications/DetachedFileNotificationProviderTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
Labels: feature

#5341 CARGO: fetch cargo metadata even with compilation error
  src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: fix

#4985 REF: introduce constant refactoring
  src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceConstant/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceParameter/RsIntroduceParameterHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
Labels: feature

#5345 COMP: fix IndexNotReadyException while completion
  src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: fix

#5312 REF: omit unchanged default type parameters of parameters in ExtractFunction
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#5205 MACRO: use common task queue with cargo sync
  src/main/kotlin/org/rust/RsProjectTaskQueueService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/openapiext/AsyncTasks.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
Labels: fix

#5359 Use the proper grammar for path fragments in macro_rules!
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Labels: fix

#5358 INSP: Fix false positive in refutability check
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/test/kotlin/org/rust/ide/inspections/RsRedundantElseInspectionTest.kt
  src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
Labels: fix

#5362 PERF&MACRO: slightly optimize macro matching
  src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroGraphWalker.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/parser/util.kt
Labels: performance

#5218 REPL: Fix imports
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleView.kt
  src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTest.kt
  src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTestBase.kt
  src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTestFixture.kt
Labels: fix

#5273 Improve breadcrumbs
  src/main/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProvider.kt
  src/main/kotlin/org/rust/ide/presentation/Utils.kt
  src/test/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProviderTest.kt
Labels: feature

#5383 Fix control flow analysis of paren expression
  src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
Labels: fix

#5382 RUN: Fix clippy/rustfmt is installed check
  src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
Labels: fix

#5310 ANN: highlight never type exit points
  src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
  src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
Labels: feature

#5379 REF: fix auto-import in introduce constant refactoring
  src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
Labels: fix

#5356 RUN: Fix environment variables for Coverage runner
  coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
Labels: fix

#5380 ANN: don't annotate unknown types in format macros
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: fix

#5361 HINT: special case for `impl Iterator` types
  src/main/kotlin/org/rust/ide/hints/RsChainMethodTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/test/kotlin/org/rust/ide/hints/RsChainMethodTypeHintsProviderTest.kt
  src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt
Labels: feature

#5399 INT: Add "Replace with block/EOL comment" intentions
  src/main/kotlin/org/rust/ide/intentions/ReplaceBlockCommentWithLineCommentIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ReplaceLineCommentWithBlockCommentIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/ReplaceBlockCommentWithLineCommentIntention/after.rs.template
  src/main/resources/intentionDescriptions/ReplaceBlockCommentWithLineCommentIntention/before.rs.template
  src/main/resources/intentionDescriptions/ReplaceBlockCommentWithLineCommentIntention/description.html
  src/main/resources/intentionDescriptions/ReplaceLineCommentWithBlockCommentIntention/after.rs.template
  src/main/resources/intentionDescriptions/ReplaceLineCommentWithBlockCommentIntention/before.rs.template
  src/main/resources/intentionDescriptions/ReplaceLineCommentWithBlockCommentIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ReplaceBlockCommentWithLineCommentIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ReplaceLineCommentWithBlockCommentIntentionTest.kt
Labels: feature

#5405 RES: Fix struct field resolve when using type alias
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#5408 RUN: Fix debug when terminal emulator is enabled
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
Labels: fix

#5393 DBG: advertising of Native Debugging Support plugin
  src/201/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
  src/201/main/resources/META-INF/platform-core.xml
Labels: feature

#5409 DBG: don't interrupt debugging session if debugger is not loaded/update
  debugger/src/201/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/201/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtilsExt.kt
  debugger/src/201/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt
  debugger/src/201/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
Labels: feature

#5437 PERF&MACRO: FileTypeOverrider for macro expansions
  src/main/kotlin/org/rust/lang/core/macros/RsFileTypeOverriderForMacroExpansionFileSystem.kt
  src/main/resources/META-INF/rust-core.xml
Labels: performance

#5448 ANN: don't annotate format-like non-stdlib marcos
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: fix

#5423 PERF&MACRO: disable some indices for macro expansions
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/RsGlobalIndexFilterForMacroExpansionFileSystem.kt
  src/main/resources/META-INF/rust-core.xml
Labels: performance

#5416 TYPE: implement SelfManagingCommenter
  src/main/kotlin/org/rust/ide/commenter/RsCommenter.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/commenter/RsCommenterTest.kt
Labels: feature

#5181 REF: Move single file
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesConflictsDetector.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileReexportTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTestBase.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileVisibilityTest.kt
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/mod2/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/usages1.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/usages2.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/after/usages3.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/mod1/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/usages1.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/usages2.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/add_import_if_there_are_many_usages/before/usages3.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/after/inner1/inner2/inner3/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/after/inner1/inner2/inner3/mod2/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/after/inner1/inner2/inner3/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/after/lib.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/after/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/before/inner1/inner2/inner3/mod1/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/before/inner1/inner2/inner3/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/before/inner1/inner2/inner3/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/before/lib.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/before/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/after/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/after/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/after/mod2/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/after/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/after/usages.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/before/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/before/mod1/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/before/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/before/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_inside_references/before/usages.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/mod1/mod1_inner/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/mod2/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/mod2/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/before/main.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/before/mod1/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/before/mod1/mod1_inner/foo.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/before/mod1/mod1_inner/mod.rs
  src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/before/mod2/mod.rs
Labels: feature

#5445 HINT: fix inlay hints for type placeholders
  src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyInfer.kt
  src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt
Labels: fix

#5392 ANN: fix raw format strings in RsFormatMacroAnnotator
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/RsLiteralKind.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: fix
