Repository intellij-rust/intellij-rust, pull requests merged in 2021-01, with the labels that each got.

#6588 INSP: Ignore expanded members in `Trait implementation` inspection
  src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt
Labels: fix

#6606 RES&COMP: don't duplicate `Self` while name resolution and completion
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#6582 CARGO: basic support for rustup override
  .github/workflows/check.yml
  coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorWithToolchainOverrideTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/RustupOverrideTest.kt
Labels: feature

#6084 TOML: add folding builder
  intellij-toml/src/main/kotlin/org/toml/ide/folding/TomlFoldingBuilder.kt
  intellij-toml/src/main/resources/META-INF/plugin.xml
  intellij-toml/src/test/kotlin/org/toml/TomlTestBase.kt
  intellij-toml/src/test/kotlin/org/toml/ide/folding/TomlFoldingBuilderTest.kt
  intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/array.toml
  intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/array_table.toml
  intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/custom_regions.toml
  intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/inline_table.toml
  intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/table.toml
Labels: feature

#6613 ANN: improve fill function arguments fix
  src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt
Labels: fix

#6602 ANN: gray out disabled cfg_attr attributes
  src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/utils/CfgUtils.kt
  src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
Labels: feature

#6636 Take into account cfg_attr during experimental compiler features annotation
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsFeatureIndex.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#6609 CARGO: download stdlib dependencies into system dir
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
Labels: fix

#6643 TY: infer type of default type parameters for known stdlib items
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Labels: fix

#6535 INSP&COMP: Improve cyclic feature dependencies handling
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlCyclicFeatureInspection.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/inspectionDescriptions/CargoTomlCyclicFeature.html
Labels: feature

#6658 Add proc-macro-expander source
  .gitignore
  proc_macro_expander/Cargo.lock
  proc_macro_expander/Cargo.toml
  proc_macro_expander/src/main.rs
Labels: internal

#6650 COMP: show all re-exports of the same item in completion
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixture.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
Labels: fix

#6623 TOML: unify toml key parsing
  intellij-toml/src/main/grammars/TomlParser.bnf
  intellij-toml/src/main/kotlin/org/toml/lang/psi/Psi.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/TomlPsiFactory.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/TomlVisitor.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/ext/TomlKey.kt
  intellij-toml/src/main/kotlin/org/toml/lang/psi/impl/Psi.kt
  intellij-toml/src/test/kotlin/org/toml/lang/psi/TomlPsiFactoryTest.kt
  intellij-toml/src/test/kotlin/org/toml/lang/psi/TomlVisitorTest.kt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/arrayTables.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/arrays.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/boolean.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/inlineTables.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/numbers.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/strings.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/tables.txt
  intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/time.txt
  toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
  toml/src/main/kotlin/org/rust/toml/CargoFeatureLineMarkerProvider.kt
  toml/src/main/kotlin/org/rust/toml/CargoTomlElementDescriptionProvider.kt
  toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlLookupElements.kt
  toml/src/main/kotlin/org/rust/toml/completion/CratesIoApi.kt
  toml/src/main/kotlin/org/rust/toml/completion/CratesIoCargoTomlDependencyCompletionProviders.kt
  toml/src/main/kotlin/org/rust/toml/completion/RsCfgFeatureCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/completion/RsTomlKeysCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/completion/TomlKeyValueCompletionProviderBase.kt
  toml/src/main/kotlin/org/rust/toml/completion/TomlSchema.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoDependencyReferenceProvider.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFileReferenceProvider.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlNameResolution.kt
  toml/src/main/kotlin/org/rust/toml/search/CargoTomlFindUsagesHandlerFactory.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlKeyResolveTest.kt
Labels: internal

#6659 PERF: split TyFingerprint for slices and arrays
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
Labels: performance

#6671 Fix endless go-to-declaration for invalid self-containing structs
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
Labels: fix

#4550 RUN: Don't activate Build Tool Window if "Activate tool window" option is disabled
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildTaskProvider.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
Labels: fix

#6678 REF: correctly extract selected statements inside blocks into a function
  src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#6684 REF: correctly extract selected statements inside exprs into a function
  src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#6580 INT: do not offer ChangeVisibilityIntention in trait impl blocks
  src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt
  src/test/kotlin/org/rust/ide/intentions/visibility/MakePrivateIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/visibility/MakePubCrateIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/visibility/MakePubIntentionTest.kt
Labels: fix

#6471 INT: add support for associated functions in CreateFunctionIntention
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: feature

#6324 RUN: Implicitly pass required features to a run configuration
  src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/BenchRunConfigurationProducerTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/ExecutableRunConfigurationProducerTest.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_configuration_uses_default_environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_fn_is_more_specific_than_main_or_test_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_adds_bin_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_ignores_selected_files_that_contain_no_benches.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_uses_complete_function_path.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_annotated_functions.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_benches_source_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_directories_inside_benches_source_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_module_declarations.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_modules.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_multiple_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_nested_modules_1.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_nested_modules_2.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/bench_producer_works_for_root_module.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executable_configuration_uses_default_environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executable_producer_works_for_bin.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executable_producer_works_for_example.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/hyphen_in_name_works.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ignored_test_is_run_with_ignored_option.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_bench_fn.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_bench_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_test_fn.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_fn_is_more_specific_than_test_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/main_mod_is_more_specific_than_test_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/meaningful_bench_configuration_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/meaningful_test_configuration_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/take_into_account_path_attribute.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_configuration_uses_default_environment.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_fn_is_more_specific_than_main_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_mod_decl_is_more_specific_than_main_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_mod_is_more_specific_than_bench_mod.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_adds_bin_name.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_ignores_selected_files_that_contain_no_tests.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_uses_complete_function_path.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_annotated_functions.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_directories_inside_tests_source_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_module_declarations.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_modules.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_multiple_files.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_nested_modules_1.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_nested_modules_2.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_project_root.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_root_module.xml
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/test_producer_works_for_tests_source_root.xml
Labels: feature

#5552 ANN: annotate wrong return type for empty functions
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#6590 RUN: Support Build tool window for cargo check and clippy
  coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTestBase.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt
Labels: feature

#6662 PERF: slightly optimize associated items and methods resolution
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/types/Substitution.kt
  src/main/kotlin/org/rust/stdext/Collections.kt
Labels: performance

#6501 INSP: make items from std appear first when auto import
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
Labels: fix

#6504 RUN: Fix working directory when run `cargo test` in debug mode
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoDependencyReferenceProvider.kt
Labels: fix

#5475 HINT: add type parameter name to non-smart parameter hints of generic enum variants
  src/main/kotlin/org/rust/ide/utils/CallInfo.kt
  src/test/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHintsProviderTest.kt
Labels: feature

#6668 INT: fix incorrect replacing when no space between parameters in JoinParameterListIntention
  src/main/kotlin/org/rust/ide/intentions/ListIntention.kt
  src/test/kotlin/org/rust/ide/intentions/JoinParameterListIntentionTest.kt
Labels: fix

#6563 ACT: introduce `Share in Playground` action
  build.gradle.kts
  src/main/kotlin/org/rust/ide/actions/RsToolsActionGroup.kt
  src/main/kotlin/org/rust/ide/actions/ShareInPlaygroundAction.kt
  src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionGroup.kt
  src/main/kotlin/org/rust/ide/notifications/Utils.kt
  src/main/kotlin/org/rust/ide/utils/IoUtils.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/MockServerFixture.kt
  src/test/kotlin/org/rust/ide/actions/ShareInPlaygroundActionTest.kt
  toml/src/main/kotlin/org/rust/toml/completion/CratesIoApi.kt
Labels: feature, to be documented

#6702 RUN: Allow to build different projects simultaneously
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildSessionsQueueManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
Labels: fix

#6364 ANN: Support `min_const_generics` feature
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceFeatureAttributeFixTest.kt
Labels: feature

#6685 RES: prefer trait methods before private inherent methods
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
Labels: fix

#5944 REF: add basic implementation of change signature refactoring
  src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveParameterFix.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/functionSignature.kt
  src/main/kotlin/org/rust/ide/search/RsFindUsagesProvider.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: feature, to be documented

#6716 INT: Support async function by create function intention
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: fix

#6688 TY&ANN: fix false-positive E0277
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#6723 PERF: Optimize backtrace filter and folding when using new resolve
  src/main/kotlin/org/rust/ide/console/RsConsoleFolding.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Labels: fix

#6692 RES: Fix completion of unqualified macro calls in new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#6725 TY: fix assoc type bounds with supertrait
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#6724 REF: Fix types auto import in change signature dialog with new resolve
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
Labels: fix

#6622 ANN: add quick fix to remove redundant function call arguments
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFix.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFixTest.kt
Labels: feature

#6750 GRD: update 2020.3 IDE and plugin dependencies
  clion/src/202/main/kotlin/org/rust/clion/cargo/CidrBuildConfigurationProvider.kt
  clion/src/202/main/resources/META-INF/platform-clion-only.xml
  clion/src/203/main/kotlin/org/rust/clion/cargo/CidrBuildConfigurationProvider.kt
  clion/src/203/main/resources/META-INF/platform-clion-only.xml
  clion/src/main/kotlin/org/rust/clion/cargo/CargoBuildConfigurationProvider.kt
  clion/src/main/resources/META-INF/clion-only.xml
  gradle-203.properties
Labels: fix

#6738 RUN: Show test hierarchy tree on the client when using "Code with me" plugin
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt
Labels: fix

#6719 Fix passing item name through RsResolveProcessor
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
Labels: performance

#6764 CI: create new milestone during new branch creation
  .github/workflows/release-branch.yml
  scripts/github.py
  scripts/make_next_milestone.py
Labels: internal
