Repository intellij-rust/intellij-rust, pull requests merged in 2021-04, with the labels that each got.

#7035 Fix fetching registry index branch on nightly
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: fix

#7036 Update BTreeMap/BTreeSet GDB pretty-printers to Rust 1.50
  prettyPrinters/gdb_providers.py
  pretty_printers_tests/tests/btree.rs
Labels: fix

#7042 Bump kotlin api version to 1.4
  build.gradle.kts
  src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
Labels: internal

#7031 Fix crates local index state updates
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: fix

#7038 PERF: speedup proc macro tt json serialization/deserialization
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/Request.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/Response.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/TokenTree.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonAdapter.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonDeserializer.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonSerializer.kt
  src/main/kotlin/org/rust/lang/core/psi/MacroBraces.kt
  src/main/kotlin/org/rust/util/RsJacksonDeserializer.kt
  src/main/kotlin/org/rust/util/RsJacksonSerializer.kt
  src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonTest.kt
Labels: performance

#7051 MACRO: Fix non-ASCII literals in proc macros
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpansionTest.kt
Labels: fix

#7053 Do not evaluate unknown cfg to false in stdlib crates
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
Labels: fix

#6890 CARGO: improve fetching actual stdlib data
  build.gradle.kts
  clion/src/test/kotlin/org/rust/clion/RsCLionProjectViewTest.kt
  clion/src/test/resources/META-INF/plugin.xml
  idea/src/test/kotlin/org/rust/ide/idea/RsIdeaProjectViewTest.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/PackageOrigin.kt
  src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/inspections/import/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/main/kotlin/org/rust/openapiext/RsPathManager.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rust/cargo/RustupTestFixture.kt
  src/test/kotlin/org/rust/cargo/project/model/CargoStdlibPackagesTest.kt
  src/test/kotlin/org/rust/common.kt
  src/test/kotlin/org/rustSlowTests/RsProjectViewTestBase.kt
Labels: fix

#7059 Update HashMap/HashSet pretty-printers to Rust 1.52
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_providers.py
  pretty_printers_tests/tests/hash_map.rs
Labels: fix

#6599 CARGO: Use semver to sort crate versions
  build.gradle.kts
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlCompletionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt
Labels: feature

#7057 RES: Filter out cfg-disabled items during resolve and completion in new resolve
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: fix

#7046 Implement stub-only `QueryAttributes` API
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPathReferenceElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt
  src/main/kotlin/org/rust/lang/core/stubs/common/PsiOrStubInterfaces.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLintLevelTest.kt
Labels: internal

#7070 ANN: If no `crate` exists, no check is performed
  src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
Labels: fix

#7004 INSP&COMP: Use exceptions to check whether index is updating
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt
Labels: fix

#7072 INT: make `Show the result of macro expansion` intention low priority
  src/main/kotlin/org/rust/ide/intentions/RunCargoExpandIntention.kt
Labels: fix

#7076 FIX: correctly place visibility in ChangeSignature with attributes
  src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#5650 INT: replace usages in DestructureIntention
  src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt
  src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/RsMultipleVariableRenamer.kt
  src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/resources/intentionDescriptions/DestructureIntention/after.rs.template
  src/main/resources/intentionDescriptions/DestructureIntention/before.rs.template
  src/test/kotlin/org/rust/ide/intentions/DestructureIntentionTest.kt
Labels: feature

#7080 FIX: do not import default type arguments in ChangeSignature refactoring
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#7079 MACRO: fix expansion if proc macro is added as separate cargo project
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
Labels: fix

#7089 RES: Fix resolve of macros with absolute paths in new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#6960 INT: Introduce expand dependency specification intention
  src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
  toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt
  toml/src/main/kotlin/org/rust/toml/intentions/TomlElementBaseIntentionAction.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/intentionDescriptions/ExpandDependencySpecificationIntention/after.rs.template
  toml/src/main/resources/intentionDescriptions/ExpandDependencySpecificationIntention/before.rs.template
  toml/src/main/resources/intentionDescriptions/ExpandDependencySpecificationIntention/description.html
  toml/src/test/kotlin/org/rust/toml/intentions/CargoTomlIntentionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntentionTest.kt
Labels: feature

#7081 FIX: check namespaces in ChangeSignature name conflict detection
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#7100 Associate `poetry.lock` files with TOML file type
  CONTRIBUTORS.txt
  intellij-toml/src/main/resources/META-INF/plugin.xml
  intellij-toml/src/test/kotlin/org/toml/lang/TomlFileTypeTest.kt
Labels: feature

#6013 Don't run inspections on files outside a valid project
  src/main/kotlin/org/rust/ide/inspections/RsApproxConstantInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsAssertEqualInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsCStringPointerInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsDanglingElseInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsDetachedFileInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsDiagnosticBasedInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsDoubleNegInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsDropRefInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsDuplicatedTraitMethodBindingInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsExtraSemicolonInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsFieldInitShorthandInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsLiftInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsMissingElseInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsReassignImmutableInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsSimplifyBooleanExpressionInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsSimplifyPrintInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsSuspiciousAssignmentInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsTryMacroInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongLifetimeParametersNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsWhileTrueLoopInspection.kt
Labels: feature

#6903 Introduce EDITION_2021
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspection.kt
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Labels: internal

#7094 GRD: enable Gradle Build Cache
  .gitignore
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
Labels: internal

#6845 INT: add intention to toggle feature state from cfg attribute
  src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/ToggleFeatureIntention/after.rs.template
  src/main/resources/intentionDescriptions/ToggleFeatureIntention/before.rs.template
  src/main/resources/intentionDescriptions/ToggleFeatureIntention/description.html
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt
Labels: feature

#7093 CARGO: fetch cfg options according to Cargo config
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CustomTargetCfgResolveTest.kt
Labels: feature

#7108 Fix auto import in the case of a renamed cargo package
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#7114 GRD: don't show "Tip of the Day" at startup in internal IDEs
  build.gradle.kts
Labels: internal

#7115 INT: prioritize `ToggleFeatureIntention` and extend its availability range
  src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt
  src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt
Labels: fix

#7121 Refresh Cargo project when workspace `Cargo.toml` is changed
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt
Labels: fix

#7101 FIX: better check where clause in RsNeedlessLifetimesInspection
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Labels: fix

#6992 MACRO: expand custom derive, resolve impls from custom derive
  native-helper/Cargo.lock
  native-helper/Cargo.toml
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt
  src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt
  src/main/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentions.kt
  src/main/kotlin/org/rust/ide/utils/CfgUtils.kt
  src/main/kotlin/org/rust/ide/wordSelection/RsMacroCallSelectionHandler.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroCallData.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt
  src/main/kotlin/org/rust/lang/core/psi/RsProcMacroKind.kt
  src/main/kotlin/org/rust/lang/core/psi/RsProcMacroPsiUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStructOrEnumItemElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroCallIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/common.kt
  src/test/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
  src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: feature

#7111 Support fold `where`
  src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
  src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt
  src/test/resources/org/rust/ide/folding/fixtures/where.rs
Labels: feature

#7112 Support for `imports` and `method bodies` options in `Code Folding`
  src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
Labels: feature

#6581 IDE: add support for navbar breadcrumbs
  src/main/kotlin/org/rust/ide/navigationToolbar/RsNavBarModelExtension.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#7132 RES: fix resolve of field shorthand in unknown struct literal
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#6837 INT: add intention to create a struct
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/CreateStructIntention/after.rs.template
  src/main/resources/intentionDescriptions/CreateStructIntention/before.rs.template
  src/main/resources/intentionDescriptions/CreateStructIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt
Labels: feature

#6986 INT: use template for unknown return type in CreateFunctionIntention
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: feature

#7131 INSP: properly proofread single sentence in sequential Rust comments
  grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
Labels: fix

#7142 CARGO: drop `org.rust.cargo.fetch.out.dir` feature
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: feature

#7119 RES: resolve qualified attribute proc macro paths
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: fix

#6201 Deduplicate cargo projects
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoProjectDeduplicationTest.kt
Labels: fix

#6801 TOML: add CrateVersionInvalidInspection
  toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CrateVersionRequirement.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CargoDependencyCrateVisitor.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlCyclicFeatureInspection.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlInspectionToolBase.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspection.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/inspectionDescriptions/CrateVersionInvalid.html
  toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlCrateInspectionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/inspections/CrateNotFoundInspectionTest.kt
  toml/src/test/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspectionTest.kt
Labels: feature

#7150 Update DTrace profiler integration to CLion 2021.1
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
Labels: fix

#7102 ANN: annotate unknown cfg predicates [E0537]
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#7063 INSP: improve `Can't find crate` annotations
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Labels: fix

#7098 RES: Basic resolve of macros 2.0 with new resolve
  src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsAttributeProcMacroReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsDeriveTraitReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
Labels: feature

#7152 RES: Fix changing crate name when using new name resolution engine
  src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: fix

#7162 CI: speed up check workflow
  .github/workflows/check.yml
  scripts/github.py
  scripts/has_successful_status.py
Labels: internal

#7167 RES: Fix exception when removing crate from workspace in new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: fix

#7181 PERF: Fix which files are checked for modification after cargo refresh
  src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsMultipleDefMapsUpdateTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsBuildDefMapTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsProfileCargoRefreshTest.kt
Labels: performance

#7178 ANN: Take into account enum's lifetimes in `Needless Lifetimes` inspection
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Labels: fix

#7140 RES: Enable new name resolution engine by default
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/resources-stable/META-INF/experiments.xml
  src/main/resources/messages/RsBundle.properties
Labels: feature

#7187 Introduce `existsAfterExpansion`, use it instead of `isEnabledByCfg`
  src/main/kotlin/org/rust/ide/annotator/RsAnnotationHolder.kt
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
  src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt
  src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ControlFlowGraph.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
Labels: internal

#7165 ANN: Add quick fix to correct invalid cfg predicates
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/NameSuggestionFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature
