Repository intellij-rust/intellij-rust, pull requests merged in 2021-08, with the labels that each got.

#7596 MACRO: expand macro 2.0
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/macros/RsMacroData.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroDefinitionBase.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacro2ExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
Labels: feature

#7630 RUN: Set Cargo environment variables when debug/profile
  src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
Labels: fix

#7625 INSP: Take into account `start` feature in `Main function not found` inspection
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
Labels: fix

#7501 RUN: Fix WSL support on 212
  src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt
Labels: fix

#7539 INSP&COMP: Add completion and quick-fix for `crate_type` attribute
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspection.kt
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCrateTypeAttrCompletionProvider.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCrateTypeAttrCompletionProviderTest.kt
Labels: feature

#7568 RUN: Introduce setting to navigate to first error in editor
  src/211/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
  src/212/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
Labels: feature

#7653 ANN: fix auto-import popup rendering on 212
  src/211/main/kotlin/org/rust/ide/inspections/import/RsImportCandidateCellRenderer.kt
  src/212/main/kotlin/org/rust/ide/inspections/import/RsImportCandidateCellRenderer.kt
  src/main/kotlin/org/rust/ide/inspections/import/ui.kt
Labels: fix

#7666 Show unstable macro 2.0 items in structure view
  src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt
  src/test/kotlin/org/rust/ide/structure/RsStructureViewModelTest.kt
Labels: fix

#7664 GRAM: pin the `fn` keyword in FnPointer
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFnPointerType.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn_type.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn_type.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/types.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/types.txt
Labels: feature

#7614 RUN: Allow removing "Build" step in Cargo Command configurations
  src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfiguration.kt
Labels: fix

#7668 ANN: disable Make Public fix for trait impl methods
  src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
Labels: fix

#7646 INT: Implement intention to expand inline tables into full ones
  intellij-toml/core/src/main/kotlin/org/toml/ide/intentions/TomlElementBaseIntentionAction.kt
  intellij-toml/core/src/main/kotlin/org/toml/ide/intentions/TomlExpandInlineTableIntention.kt
  intellij-toml/core/src/main/kotlin/org/toml/lang/psi/TomlPsiFactory.kt
  intellij-toml/core/src/main/resources/META-INF/toml-core.xml
  intellij-toml/core/src/main/resources/intentionDescriptions/TomlExpandInlineTableIntention/after.toml.template
  intellij-toml/core/src/main/resources/intentionDescriptions/TomlExpandInlineTableIntention/before.toml.template
  intellij-toml/core/src/main/resources/intentionDescriptions/TomlExpandInlineTableIntention/description.html
  intellij-toml/core/src/test/kotlin/org/toml/ide/intentions/TomlExpandInlineTableIntentionTest.kt
  intellij-toml/core/src/test/kotlin/org/toml/ide/intentions/TomlIntentionTestBase.kt
  intellij-toml/src/main/resources/META-INF/plugin.xml
  toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt
  toml/src/main/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntention.kt
  toml/src/main/kotlin/org/rust/toml/intentions/RsTomlElementBaseIntentionAction.kt
  toml/src/main/kotlin/org/rust/toml/intentions/SimplifyDependencySpecificationIntention.kt
Labels: feature

#7635 Change useAliasNames and skipUnchangedDefaultTypeArguments defaults to true in type rendering and import helper
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertLetDeclTypeFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyFix.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt
  src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
  src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/utils/CallInfo.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddTypeFixTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
  src/test/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ConvertUFCSToMethodCallIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceParameterTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Labels: fix

#7682 ANN: detect E0121 in struct
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#7692 TY: ignore associated type aliases
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt
Labels: fix

#7676 INT: support aliases in AddRemainingArmsIntention
  src/main/kotlin/org/rust/ide/utils/checkMatch/Pattern.kt
  src/test/kotlin/org/rust/ide/intentions/AddRemainingArmsIntentionTest.kt
Labels: fix

#7690 INT: import types in create function/struct/tuple struct intentions
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
Labels: fix

#7557 INSP: remove some false positives from RsSelfConventionInspection
  src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
Labels: fix

#7703 Optimize Rust completion contributors order to collect keywords first
  src/main/resources/META-INF/rust-core.xml
Labels: performance

#7638 INT: Handle tail expressions in "Surround with unsafe" inspection
  src/main/kotlin/org/rust/ide/annotator/fixes/SurroundWithUnsafeFix.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
Labels: fix

#7640 Improve external ABI support
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddFeatureAttributeFix.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsExternAbiCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFnPointerType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsExternAbiCompletionTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/attrs_in_params.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/extern_block.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/extern_block.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/extern_fns.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/extern_fns.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/fn.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/type.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/type.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/items.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/types.txt
Labels: feature

#7582 COMP: don't show popup for let binding starting with a lowercase char
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/inspections/RsMissingElseInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt
  src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/main/kotlin/org/rust/ide/intentions/SplitIfIntention.kt
  src/main/kotlin/org/rust/ide/surroundWith/expression/RsWithIfExpSurrounder.kt
  src/main/kotlin/org/rust/ide/surroundWith/expression/RsWithWhileExpSurrounder.kt
  src/main/kotlin/org/rust/ide/utils/ExprUtils.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionConfidence.kt
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
Labels: fix

#7598 QDOC: Display implied shortcut reference links in quick documentation
  src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
  src/test/kotlin/org/rust/ide/docs/RsRenderedDocumentationTest.kt
Labels: fix

#7711 TY: introduce `Ty.isEquivalentTo` that should replace `==` for `Ty`s
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprBuilder.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix, internal

#7734 UI: update icons for macros
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt
  src/main/resources/icons/nodes/macro.svg
  src/main/resources/icons/nodes/macro2.0.svg
Labels: feature

#7751 GRAM&ANN: parse `unsafe` keyword in modules and annotate it as error
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/mod.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/mod.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt
Labels: feature

#7758 CARGO: don't fetch stdlib metadata for rustc project
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
Labels: fix

#7757 GRAM&ANN&TY: Parse and annotate `const_generics_defaults` feature
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/RsDiagnosticBasedInspection.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/const_generics.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/const_generics.txt
Labels: feature
