Repository intellij-rust/intellij-rust, pull requests merged in 2021-03, with the labels that each got.

#6900 Fix cargo features state inference on renamed packages
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/FeatureGraph.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/test/kotlin/org/rust/common.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: fix

#6892 RES: Add method to RsPathReference to resolve only public items
  src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReference.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#6917 Initialize services outside of write action
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: performance

#6881 Simplify bit flags creation
  src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt
  src/main/kotlin/org/rust/stdext/BitFlagsBuilder.kt
Labels: internal

#6876 Do not expand builtin macros as "{}"
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroData.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
Labels: fix, internal

#6717 ANN: Take into account const generics in inspections about generic parameters/arguments ordering
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: fix

#6930 GRD: use 211 as default platform for development
  gradle.properties
Labels: internal

#6931 GRAM&PSI: put macro argument subtree delimiters inside the nodes
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/attributes.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impls.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/patterns.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/raw_operator.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/type.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/visibility.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/macros.txt
Labels: internal

#6933 TYPE: auto-indent line when typing <enter> inside an array literal
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/formatter/RsAutoIndentTest.kt
Labels: fix

#6934 TYPE&FMT: auto-indent line when typing <enter> in macro bodies
  src/main/kotlin/org/rust/ide/formatter/RsFormattingModelBuilder.kt
  src/main/kotlin/org/rust/ide/formatter/blocks/RsMacroArgFmtBlock.kt
  src/test/kotlin/org/rust/ide/formatter/RsAutoIndentMacrosTest.kt
Labels: feature

#6941 New Rust plugin icon
  plugin/src/main/resources/META-INF/pluginIcon.svg
  plugin/src/main/resources/META-INF/pluginIcon_dark.svg
Labels: feature, to be documented

#6944 Fix crashes on 2021.1 when proc macros are enabled
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: fix

#6799 COMP: Add completion by subwords for dependencies
  toml/src/main/kotlin/org/rust/toml/completion/CargoDependenciesPrefixMatcher.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoNormalizedNamesPrefixMatcher.kt
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlCompletionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/inspections/CrateNotFoundInspectionTest.kt
Labels: feature

#6907 DBG: debugger support for Rider for Unreal Engine 2021.1
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
  src/main/kotlin/org/rust/debugger/utils.kt
Labels: feature

#6769 ANN: fix false positive E0658 in stdlib
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
Labels: fix

#6955 ANN: fix false-positive redundant `::` annotation in array types
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
Labels: fix

#6948 Fix type rendering with const generic parameters
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericParameter.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameterList.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: fix

#6959 ACT: support `Move Element Right/Left` actions for const generic parameters
  src/main/kotlin/org/rust/ide/actions/RsMoveLeftRightHandler.kt
  src/test/kotlin/org/rust/ide/actions/RsMoveLeftRightHandlerTest.kt
Labels: fix

#6958 QDOC: properly render const generics in signature of top-level items
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
Labels: fix

#6896 REF: Don't insert default type parameters by Implement Member actions
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#6947 REF: Support import aliases in Move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#6956 Increase minimal supported rustc version to 1.41.0
  .github/workflows/check.yml
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  pretty_printers_tests/src/main.rs
  pretty_printers_tests/src/test_runner.rs
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
  src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
  src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt
  src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: feature

#6966 Use the default Project Rust toolchain when creating a new project
  src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Labels: feature

#6450 ANN & RES: Fix in-band lifetimes support
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#6893 REF: Import types after Extract Function refactoring
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: feature

#7001 ANN: Support const generics in E0107 inspection
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsWrongGenericArgumentsNumber.html
  src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt
Labels: feature

#6066 Use todo!() instead of unimplemented!() in generated bodies of implemented members.
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/UnwrapToMatchIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/resources/intentionDescriptions/CreateFunctionIntention/after.rs.template
  src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/after.rs.template
  src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/before.rs.template
  src/main/resources/intentionDescriptions/UnwrapToMatchIntention/after.rs.template
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/UnwrapToMatchIntentionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: feature

#7007 TY: fix unification with `!` in match arms
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#6968 COMP: Don't suggest postfix templates inside string literals
  src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/kotlin/org/rust/ide/template/postfix/surrounderBasedPostfixTemplates.kt
  src/main/kotlin/org/rust/ide/template/postfix/utils.kt
  src/test/kotlin/org/rust/ide/template/postfix/DerefPostfixTemplateTest.kt
Labels: fix

#6457 TOML: add TomlUnresolvedReferenceInspection
  intellij-toml/src/main/kotlin/org/toml/ide/inspections/TomlUnresolvedReferenceInspection.kt
  intellij-toml/src/main/resources/META-INF/plugin.xml
  intellij-toml/src/main/resources/inspectionDescriptions/TomlUnresolvedReference.html
  toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlUnresolvedPathReferenceInspectionTest.kt
Labels: feature

#7005 ANN: Annotate wrong order of const generic parameters without `const_generics` feature
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Labels: feature

#7018 Fix control flow of break/continue expanded from a macro
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Labels: fix

#6829 INSP: Implement unreachable code detection
  .idea/dictionaries/intellij_rust.xml
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspection.kt
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ControlFlowGraph.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsUnreachableCode.html
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Labels: feature

#6969 COMP: Improve dependency completion when using crates local index
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProviderTest.kt
Labels: feature

#6945 REF: Refactor restoring outside references in Move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
Labels: fix

#7026 Improve `Convert to type` quick-fixes
  src/main/kotlin/org/rust/ide/annotator/fixes/AddAsTyFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToStrFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingFromTraitFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTraitFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyWithDerefsRefsFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToBorrowedTyFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToBorrowedTyWithMutFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToMutTyFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToRefTyFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToTyUsingFromTraitFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToTyUsingTraitMethodFixTestBase.kt
Labels: fix

#7033 RES: Basic multiresolve at module scope in new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
Labels: feature

#7019 GRAM: improve parser recovery in function arguments
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
Labels: fix
