Repository intellij-rust/intellij-rust, pull requests merged in 2021-09, with the labels that each got.

#7728 Fix DTrace profiler integration with CLion 2021.2
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
Labels: fix

#7740 DOC: Drop CLA requirement
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  MAINTAINING.md
Labels: internal

#7772 CARGO: show warning/error during stdlib metadata fetching in Sync View
  src/main/kotlin/org/rust/cargo/project/model/ProcessProgressListener.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
Labels: feature

#7777 Enable by default ML code completion ranking for Rust
  ml-completion/src/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
Labels: feature, to be documented

#7782 CARGO: enable fetching actual stdlib metadata
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#3790 INSP: Using a function that is going to be deprecated should warn
  build.gradle.kts
  src/main/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspectionTest.kt
Labels: feature

#7663 TYPE: Support move left/right action for predicates in where clause
  src/main/kotlin/org/rust/ide/actions/RsMoveLeftRightHandler.kt
  src/test/kotlin/org/rust/ide/actions/RsMoveLeftRightHandlerTest.kt
Labels: feature

#7637 REF: Use existing impl block in "Extract function" refactoring
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#7506 RUN: Fix macros and generated items support for WSL toolchains
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/RustcMessage.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/openapiext/RsPathManager.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
  src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/RsProcMacroExpansionResolveIntegrationTest.kt
Labels: fix

#7804 REF: create generics and where clauses for inherent impl items in RsExtractFunctionHandler
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#7805 INT: Remove ExtractDependencySpecificationIntention
  toml/src/main/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntention.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/after.rs.template
  toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/before.rs.template
  toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/description.html
  toml/src/test/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntentionTest.kt
Labels: fix

#7809 RES: Fix injecting prelude in 2021 edition
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2021.kt
Labels: fix

#7811 RES: Fix resolving macros 2 from prelude
  src/main/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroGraphWalkerTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Labels: fix

#7810 Show completion autopopup when typing let mut with existing ident
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionConfidence.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt
Labels: fix

#7806 INSP: Insert import at correct location during auto-import
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/main/kotlin/org/rust/ide/utils/import/UseItemWrapper.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/main/kotlin/org/rust/stdext/Collections.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
  src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: fix

#7841 ANN: fix infinite loop when invoking a quick fix on an element with a syntax error
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFixTest.kt
Labels: fix

#7818 PERF: Expand macros in parallel during CrateDefMap building
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/kotlin/org/rust/stdext/CompletableFuture.kt
Labels: performance

#7795 GRAM&ANN: Improve parsing of const generic arguments / defaults
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/EncloseExprInBracesFix.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/EncloseExprInBracesFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/const_generics.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/const_generics.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/const_generics.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/const_generics.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/no_lifetime_bounds_in_generic_args.txt
Labels: fix

#7861 RES: Fix inserting import to different crate at correct location
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
Labels: fix

#7550 INSP: Support child modules in unused import inspection
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/GlobImportGraph.kt
  src/main/kotlin/org/rust/lang/utils/Graph.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: feature

#7488 DBG: automatically break on panic inside debugger
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsBreakOnPanicConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerGeneralSettingsConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerUiComponent.kt
Labels: feature, to be documented

#7869 UI: Reset "Standard library" on "Toolchain location" change in Rust settings
  src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Labels: fix

#7317 RUN: Enable WSL toolchains by default
  src/main/resources/META-INF/rust-core.xml
Labels: feature, to be documented

#7870 ANN: Show error when defaults for const parameters are used in `fn`s or `impl`s
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#7651 REF: Don't offer to move file to same directory
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt
Labels: fix

#7876 RUN: Fix check if rustup is available on WSL
  src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt
Labels: fix

#7879 MACRO: fix proc macro expansion with Rust 1.56
  native-helper/Cargo.lock
  native-helper/Cargo.toml
Labels: fix

#7836 GRAM: drop special parsing rules for `try!` and `await!` macros
  src/main/kotlin/org/rust/ide/inspections/RsTryMacroInspection.kt
  src/main/kotlin/org/rust/lang/core/dfa/ControlFlowGraph.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
  src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsTryMacroInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/async_await.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/try.txt
Labels: internal

#7883 Drop support for 2021.1 IDEs
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  .gitignore
  build.gradle.kts
  clion/src/211/main/kotlin/org/rust/clion/profiler/dtrace/compatUtils.kt
  clion/src/211/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/211/main/kotlin/org/rust/clion/profiler/perf/compatUtils.kt
  clion/src/212/main/kotlin/org/rust/clion/profiler/dtrace/compatUtils.kt
  clion/src/212/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/212/main/kotlin/org/rust/clion/profiler/perf/compatUtils.kt
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
  clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  gradle-211.properties
  gradle.properties
  grazie/src/211/main/resources/META-INF/platform-grazie-only.xml
  grazie/src/211/test/kotlin/org/rust/grazie/compatUtils.kt
  grazie/src/212/main/resources/META-INF/platform-grazie-only.xml
  grazie/src/212/test/kotlin/org/rust/grazie/compatUtils.kt
  grazie/src/main/resources/META-INF/grazie-only.xml
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
  ml-completion/src/test/kotlin/org/rust/ml/RsElementFeatureProviderTest.kt
  src/211/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
  src/211/main/kotlin/org/rust/debugger/runconfig/compatUtils.kt
  src/211/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/211/main/kotlin/org/rust/ide/formatter/processors/RsPostFormatProcessor.kt
  src/211/main/kotlin/org/rust/ide/inspections/import/RsImportCandidateCellRenderer.kt
  src/211/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/211/main/resources/META-INF/platform-core.xml
  src/211/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
  src/211/test/kotlin/org/rust/ide/search/RsUsageViewTreeTest.kt
  src/212/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
  src/212/main/kotlin/org/rust/debugger/runconfig/compatUtils.kt
  src/212/main/kotlin/org/rust/ide/inspections/import/RsImportCandidateCellRenderer.kt
  src/212/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/212/main/resources/META-INF/platform-core.xml
  src/212/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
  src/212/test/kotlin/org/rust/ide/search/RsUsageViewTreeTest.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
  src/main/kotlin/org/rust/ide/formatter/RustfmtFormattingService.kt
  src/main/kotlin/org/rust/ide/inspections/import/ui.kt
  src/main/kotlin/org/rust/ide/statistics/RsProjectUsagesCollector.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
  src/test/kotlin/org/rust/ide/search/RsUsageViewTreeTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/utils.kt
Labels: feature

#7844 RES: Move option to disable new resolve from settings to registry
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/actions/RsToggleNewResolveAction.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/NewResolve.kt
  src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: internal

#7837 REF: Add trait imports for UFCS in move refactoring if necessary
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveTraitMethodsProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: fix

#7839 ANN: Get rid of `const_generic` feature, support `adt_const_params` feature
  build.gradle.kts
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceFeatureAttributeFixTest.kt
Labels: feature

#7673 INT: use template to fill unknown field types in Create(Tuple)StructIntention
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt
  src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
Labels: fix

#7330 ANN: improve Change function signature fix
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/RemoveRedundantFunctionArgumentsFix.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFixTest.kt
Labels: feature

#7886 RES: Fix that `alloc` crate can be resolved without `extern crate`
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2018.kt
Labels: fix

#7860 RES: Fix visibility of reexported item with restricted visibility
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Labels: fix

#7903 RUN: generate proper names for run configurations provided by Cargo tool window
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectsTree.kt
  src/test/kotlin/org/rustSlowTests/CargoProjectStructureTest.kt
  src/test/kotlin/org/rustSlowTests/CargoProjectsTreeTest.kt
Labels: fix
