Repository intellij-rust/intellij-rust, pull requests merged in 2021-11, with the labels that each got.

#7928 INSP: Enable unresolved reference inspection for attr macros
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Labels: feature

#7933 ANN: use top priority for AutoImportFix
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
Labels: fix

#8025 TY: fix type inference for break from a nested expression block
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: fix

#6929 ANN: Provide lifetime name check
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#7719 ANN: support E0451 for shorthand struct field literals
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
Labels: fix

#7826 INT: add intention to unwrap tuple struct/enum constructor from an expression
  src/main/kotlin/org/rust/ide/intentions/UnwrapConstructorIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/UnwrapConstructorIntention/after.rs.template
  src/main/resources/intentionDescriptions/UnwrapConstructorIntention/before.rs.template
  src/main/resources/intentionDescriptions/UnwrapConstructorIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/UnwrapConstructorIntentionTest.kt
Labels: feature

#7725 MACRO&RES: support arbitrary items expanded from custom derive
  src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt
  src/main/kotlin/org/rust/lang/core/psi/RsProcMacroPsiUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAttrProcMacroOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStructOrEnumItemElement.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapMacroIndexConsistencyTest.kt
  testData/test-proc-macros/src/lib.rs
Labels: feature

#8031 INT: Add "Merge `if`s" intention
  src/main/kotlin/org/rust/ide/intentions/MergeIfsIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/MergeIfsIntention/after.rs.template
  src/main/resources/intentionDescriptions/MergeIfsIntention/before.rs.template
  src/main/resources/intentionDescriptions/MergeIfsIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/MergeIfsIntentionTest.kt
Labels: feature

#8043 REF: do not use resolve in RsChangeFunctionSignatureConfig::create
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
Labels: fix

#7900 RES: add reference to Index trait for bracket indexing expressions
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/ext/RsIndexExpr.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsIndexExprReferenceImpl.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsIndexExprResolve.kt
Labels: feature

#8015 INT: Fix omitting parens in DemorgansLawIntention
  src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt
  src/test/kotlin/org/rust/ide/intentions/DemorgansLawIntentionTest.kt
Labels: fix

#8056 CARGO: fix build script evaluation in workspace
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: fix

#7840 INT: generalize UnwrapSingleExprIntention to support single statement expressions
  src/main/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntention.kt
  src/test/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntentionTest.kt
Labels: feature

#8080 ACT: Render parentheses for type references in `Implement Members` refactoring
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#8058 TY&RES: resolve an associated type to a trait if we're unsure about the impl
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/Substitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsNumericLiteralTypeInferenceTest.kt
Labels: fix

#7996 TOML: Enable crates local index on stable
  src/main/resources-stable/META-INF/experiments.xml
  toml/src/main/resources/META-INF/toml-only.xml
Labels: feature

#8089 Do not use resolve in EDT in RsIntroduceConstantHandler
  src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt
Labels: fix

#8098 CARGO: prevent some runtime errors in future IDE versions
  src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/main/kotlin/org/rust/ide/security/trustedProjectUtils.kt
Labels: internal

#7799 GRAM&ANN&TY: Support `if let guard` syntax
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/intentions/MoveGuardToMatchArmIntention.kt
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/match.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/match.txt
Labels: feature

#8102 REF: Enable suggested signature refactoring for trait methods
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringAvailability.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringExecution.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringTest.kt
Labels: feature

#8100 REF: fix extract variable on RsExprStmt and last expr in block
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/test/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntentionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
Labels: fix

#7978 RES: Use new resolve inside detached files
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/FakeDetachedCrate.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DetachedDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsNonPhysicalFileResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapMacroIndexConsistencyTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: feature

#8123 DBG: fix NPE in debugger support in IDEA
  debugger/src/main/resources/META-INF/native-debug-only.xml
Labels: fix, major

#8115 ANN: annotate macro 2.0 definitions as experimental
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#8138 COMP: Take into account const generic parameters while `<>` completion
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#8126 ANN: Add label name check
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#8005 INT: Support "Invert if condition" without else branch
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
Labels: feature

#8054 INSP: New auto-import for UFCS trait methods
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: feature

#8152 CI: setup Dependabot for updating `ra_ap_proc_macro_srv`
  .github/dependabot.yml
Labels: internal

#8083 New auto-import for refactorings and inspections
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
Labels: feature

#8157 Remove get, set and with patterns from RsSelfConventionInspection
  src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
Labels: fix

#8159 GRD: make 2021.3 platform default for development
  gradle-213.properties
  gradle.properties
Labels: internal

#8166 INSP: Fix false-positive unresolved reference for UFCS
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#8163 TY: correctly infer type of struct with the same name as primitive type
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: fix

#7298 ACT: Provide experimental features by "Create New Issue" action
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
Labels: feature

#8173 RES: fix exception in name resolution
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
Labels: fix

#8176 RES: prefer enum variant over associated items
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
Labels: fix

#8186 RES: Fix identity attribute proc macro on another proc macro definition
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: fix

#8189 GRD: bump since build for 213 builds
  gradle-213.properties
Labels: fix

#8167 Fix untrusted notifications in Cargo projects
  src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/ide/notifications/RsUntrustedNotificationProvider.kt
  src/main/kotlin/org/rust/ide/security/RsTrustChangeNotifier.kt
  src/main/kotlin/org/rust/ide/security/trustedProjectUtils.kt
Labels: internal

#8195 UI: fix Rust code completion settings layout
  src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
  src/main/kotlin/org/rust/ide/settings/RsCodeCompletionOptions.kt
  src/main/resources/messages/RsBundle.properties
Labels: fix

#8183 MACRO: add `async_trait` to the list of hardcoded proc macros
  src/main/kotlin/org/rust/lang/core/psi/HardcodedProcMacroProperties.kt
Labels: fix

#8194 INT: Fix "Introduce variable" intention inside match arm
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/test/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntentionTest.kt
Labels: fix

#8203 MACRO: fix expansion of proc macros with a float literal in a body
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeParser.kt
  src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeParserTest.kt
Labels: fix
