Repository intellij-rust/intellij-rust, pull requests merged in 2021-02, with the labels that each got.

#6739 ANN: Fix false-positive "Expected trait, found trait alias"
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#6731 RES: Enable new name resolution engine on nightly by default
  .github/workflows/check.yml
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/resources-nightly/META-INF/experiments.xml
Labels: feature

#6733 RES: Support resolve multi-segment macro paths in new resolve
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: feature

#6782 Fix control flow of break/continue inside block expression
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Labels: fix

#6768 CARGO: improve project opening
  src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/cargo/project/CargoProjectOpenProcessorTest.kt
  src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherIntegrationTest.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsWithToolchainAnnotationTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
  src/test/kotlin/org/rustSlowTests/CargoProjectServiceTest.kt
  src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt
  toml/src/test/kotlin/org/rust/toml/inspections/MissingFeaturesInspectionTest.kt
  toml/src/test/kotlin/org/rust/toml/search/CargoTomlFindUsagesTest.kt
Labels: fix

#6621 ANN: allow removing redundant type arguments from types with lifetimes
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeArguments.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
Labels: fix

#6591 INSP: add inspection that checks non-existent crates
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexCachesInvalidator.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/TestCrateResolverService.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/inspectionDescriptions/CrateNotFound.html
  toml/src/test/kotlin/org/rust/toml/inspections/CrateNotFoundInspectionTest.kt
Labels: feature

#6776 ANN: Check E0116 "Inherent impls should be in same crate"
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#6777 ANN: Check E0117 "Trait impls orphan rules"
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#6810 DBG: show missing Rust debugging settings on Windows
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
Labels: fix

#6804 Fix enum rendering while debugging with GDB in CLion 2021.1
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  pretty_printers_tests/tests/enum.rs
Labels: fix

#6805 RUN: Add implicit build arguments to the beginning of the command line
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/test/kotlin/org/rust/cargo/runconfig/CargoTestRunStateTest.kt
  src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
Labels: fix

#6786 Take `cfg` attributes into account in control flow
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Labels: fix

#6005 inline function from different module
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RsInlineFunctionTest.kt
Labels: fix

#6715 RUN: Suggest to install wasm32 target in wasm-pack configuration
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt
  src/main/kotlin/org/rust/ide/actions/InstallTargetAction.kt
Labels: fix

#6818 Fix crate version json parsing
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: fix

#6835 DBG: suggest to install Native Debugging Support plugin in GoLand
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
Labels: feature

#6848 ANN: Support E0116 for impls for trait objects
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#4765 Ignore underscore names during duplicates detection
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#6459 Add Python typings for LLDB/GDB pretty-printers
  .idea/inspectionProfiles/intellij_rust.xml
  .idea/scopes/prettyPrinters.xml
  prettyPrinters/gdb/__init__.pyi
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb/__init__.pyi
  prettyPrinters/lldb/formatters.pyi
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  prettyPrinters/rust_types.py
Labels: internal

#6720 RES: Fix resolve inside cfg-disabled inline mod in new resolve
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: fix

#6730 Support file level cfg attributes in new resolve
  src/main/kotlin/org/rust/ide/utils/CfgUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
Labels: fix

#6695 REF: handle where blocks in tuple <-> struct conversion
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToTupleProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt
Labels: fix

#6855 Provide builtin Clone & Copy impls for TyFunction
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: fix

#6655 Up/Down mover: move `match arm` in closure
  src/main/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMover.kt
  src/main/kotlin/org/rust/ide/actions/mover/RsMatchArmUpDownMover.kt
  src/test/kotlin/org/rust/ide/actions/mover/RsMatchArmUpDownMoverTest.kt
Labels: fix

#6869 Make native helper binary executable
  src/main/kotlin/org/rust/openapiext/RsPathManager.kt
Labels: fix

#6874 REF: Omit unchanged default type argument only if the next type argument is already ommited
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#6807 REF: allow choosing default values for new parameters in ChangeSignature
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: feature

#6877 DBG: advertise native debugging support plugin in PyCharm Pro
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
Labels: feature

#6887 REF: don't throw exception on changing name of local variable during indexing
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringSupport.kt
  src/test/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMoverTest.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsRenameSuggestedRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringTest.kt
Labels: fix

#6861 PERF: Slightly optimize RsFile.super
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsMultipleDefMapsUpdateTest.kt
Labels: performance

#6872 RES: Disable type aliases threshold in new resolve
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#6889 RES: Fix that cfg-enabled glob import overrides cfg-disabled named import
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Labels: fix

#6891 avoid empty test tool window on the Code With Me client (CWM-2044)
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt
Labels: fix

#6899 Exclude more stdlib parts from the index
  src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
Labels: fix

#6901 Associate `Cargo.toml.orig` files with TOML file type
  intellij-toml/src/main/resources/META-INF/plugin.xml
  intellij-toml/src/test/kotlin/org/toml/lang/TomlFileTypeTest.kt
Labels: feature

#6897 REF: Omit unchanged default type parameters of return type in ExtractFunction
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix
