Repository intellij-rust/intellij-rust, pull requests merged in 2021-07, with the labels that each got.

#7415 TOML: fix false-positive in multi-line array in inline table
  intellij-toml/core/src/main/kotlin/org/toml/ide/annotator/TomlAnnotator.kt
  intellij-toml/core/src/test/kotlin/org/toml/ide/annotator/TomlAnnotatorTest.kt
Labels: fix

#6342 COMP: add completion for impl trait items
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/openapiext/ui.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
Labels: feature

#7345 INT: enable SubstituteAssociatedTypeIntention for type aliases
  src/main/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntention.kt
  src/main/kotlin/org/rust/ide/intentions/SubstituteTypeAliasIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/description.html
  src/main/resources/intentionDescriptions/SubstituteTypeAliasIntention/after.rs.template
  src/main/resources/intentionDescriptions/SubstituteTypeAliasIntention/before.rs.template
  src/main/resources/intentionDescriptions/SubstituteTypeAliasIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/SubstituteTypeAliasIntentionTest.kt
Labels: feature

#7189 Use single stdlib
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
Labels: fix

#7438 COMP: reuse MembersGenerator in RsImplTraitMemberCompletionProvider
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
Labels: internal

#7436 FIX: create structs outside if invoked from inside an impl block
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt
  src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
Labels: fix

#6392 INSP: add unused imports inspection
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsUnusedImport.html
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Labels: feature

#7451 COMP: only complete ancestor mods in vis restriction paths
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#7456 ANN: Annotate trailing comma in toml inline table
  intellij-toml/core/src/main/kotlin/org/toml/ide/annotator/TomlAnnotator.kt
  intellij-toml/core/src/test/kotlin/org/toml/ide/annotator/TomlAnnotatorTest.kt
  intellij-toml/src/main/resources/META-INF/plugin.xml
Labels: feature

#6788 ANN: correctly fill empty function call arguments
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt
Labels: fix

#7148 TOML: add inspection that offers an update to a newer dependency version
  toml/src/main/kotlin/org/rust/toml/crates/local/CrateVersionRequirement.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CrateVersionInspection.kt
  toml/src/main/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspection.kt
  toml/src/main/kotlin/org/rust/toml/inspections/NewCrateVersionAvailableInspection.kt
  toml/src/main/kotlin/org/rust/toml/inspections/UpdateCrateVersionFix.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/inspectionDescriptions/NewCrateVersionAvailable.html
  toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlCrateInspectionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/inspections/NewCrateVersionAvailableInspectionTest.kt
Labels: feature

#7432 Confirm loading untrusted Cargo project
  .github/workflows/check.yml
  gradle-211.properties
  src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
  src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectsAction.kt
  src/main/kotlin/org/rust/ide/inspections/RsDetachedFileInspection.kt
  src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
  src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt
  src/main/kotlin/org/rust/ide/notifications/RsUntrustedNotificationProvider.kt
  src/main/kotlin/org/rust/ide/notifications/Utils.kt
  src/main/kotlin/org/rust/ide/security/RsTrustChangeNotifier.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
Labels: feature

#7471 COMP: only complete paths that resolve to traits in trait refs
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#7457 COMP: complete possible options inside visibility restriction
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsVisRestrictionCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsVisRestrictionCompletionTest.kt
Labels: feature

#7462 GRAM: fixed parsing priorities for expressions containing blocks
  CONTRIBUTORS.txt
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_assignment.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_assignment.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_bin_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_bin_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_call_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_call_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_cast_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_cast_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_dot_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_dot_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_full_range_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_full_range_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_full_range_expr_deprecated.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_full_range_expr_deprecated.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_index_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_index_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_lambda_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_lambda_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_open_range_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_open_range_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_return_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_return_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_try_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_try_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_unary_expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_unary_expr.txt
Labels: fix

#7427 Reset crates local index state if index is empty
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: fix

#7388 GRD: migrate to gradle-intellij-plugin 1.0
  build.gradle.kts
  gradle-211.properties
Labels: internal

#7346 COMP: add special case for String in MatchPostfixTemplate
  src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt
  src/test/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplateTest.kt
Labels: feature

#7474 INT: fixed "Create lifetime parameter from usage" with const generics
  src/main/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFix.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFixTest.kt
Labels: fix

#7437 PERF: optimize local crate index parsing
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: performance

#7491 GRD: use kotlin 1.5.20
  build.gradle.kts
Labels: internal

#7392 IDE: allow moving up/down in block expressions in comma-separated lists
  src/main/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMover.kt
  src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt
  src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt
  src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt
Labels: fix

#6664 HINT: Substitute generic parameters in Parameter info
  src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt
  src/main/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/utils/CallInfo.kt
  src/test/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandlerTest.kt
Labels: feature

#7507 INSP: Support declarative macros in unused import inspection
  src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Labels: feature

#7513 ANN: disable Grazie proofreading for Rust language in 2021.2 IDEs
  grazie/src/211/main/resources/META-INF/platform-grazie-only.xml
  grazie/src/211/test/kotlin/org/rust/grazie/compatUtils.kt
  grazie/src/212/main/resources/META-INF/platform-grazie-only.xml
  grazie/src/212/test/kotlin/org/rust/grazie/compatUtils.kt
  grazie/src/main/resources/META-INF/grazie-only.xml
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
Labels: fix

#7516 COMP: fix autoimport-aware completion after completion at empty place
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
Labels: fix

#7496 INSP: Fix handling cfg-disabled code in unused import inspection
  src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt
  src/main/kotlin/org/rust/openapiext/psi.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Labels: fix

#7487 COMP: complete lambdas in function expression position
  src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt
  src/main/kotlin/org/rust/ide/utils/template/RsTemplateBuilder.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionTest.kt
Labels: feature

#7523 GRD: make 2021.2 platform default for development
  gradle-212.properties
  gradle.properties
  src/main/kotlin/org/rust/util/jacksonUtils.kt
  src/test/kotlin/org/rustPerformanceTests/CustomRealProjectAnalysisTest.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: internal

#7480 INT: add intention to implement a trait for an ADT type
  src/main/kotlin/org/rust/ide/inspections/fixes/AddTypeArguments.kt
  src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/AddImplTraitIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddImplTraitIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddImplTraitIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/AddImplTraitIntentionTest.kt
Labels: feature

#7321 MACRO: improve macro expansion errors, show them if `show macro expansion` action fails
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt
  src/main/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentions.kt
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionError.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroCallData.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/MacroExpansionAndParsingError.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/MacroExpansionError.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/ResolveMacroWithoutPsiError.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcessAbortedException.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/DollarCrateUtil.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/openapiext/RsPathManager.kt
  src/main/kotlin/org/rust/stdext/RsResult.kt
  src/main/kotlin/org/rust/stdext/io.kt
  src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
  testData/test-proc-macros/src/lib.rs
Labels: feature, internal

#7527 Enable js module for 2021.2 builds
  build.gradle.kts
  settings.gradle.kts
Labels: fix

#7519 COMP: add postfix template for wrapping a type with another type
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/WrapTypePathPostfixTemplate.kt
  src/main/kotlin/org/rust/ide/template/postfix/utils.kt
  src/main/resources/postfixTemplates/WrapTypePathPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/WrapTypePathPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/WrapTypePathPostfixTemplate/description.html
  src/test/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/WrapTypePathPostfixTemplateTest.kt
Labels: feature

#7481 COMP: add visibility completion provider
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsVisibilityCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsVisibilityCompletionTest.kt
Labels: feature

#7503 TY: convert primitive types from object to class
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/inspections/RsCastToBoolInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsExtraSemicolonInspection.kt
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/surroundWith/expression/RsWithIfExpSurrounder.kt
  src/main/kotlin/org/rust/ide/surroundWith/expression/RsWithNotSurrounder.kt
  src/main/kotlin/org/rust/ide/surroundWith/expression/RsWithWhileExpSurrounder.kt
  src/main/kotlin/org/rust/ide/template/postfix/utils.kt
  src/main/kotlin/org/rust/ide/utils/BooleanExprSimplifier.kt
  src/main/kotlin/org/rust/lang/core/completion/RsBoolCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExpr.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprBuilder.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprEvaluator.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsPrimitiveTypeImplsTest.kt
Labels: internal

#7492 INSP: add quick fix to remove an unused import
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveImportFix.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/main/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsUseGroup.kt
  src/test/kotlin/org/rust/ide/inspections/fixes/RemoveImportFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
  src/test/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntentionTest.kt
Labels: feature

#7168 RES2: Fix resolve crate when importing private module with same name
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#7547 COMP: don't offer live templates in patterns
  src/main/kotlin/org/rust/ide/template/RsContextType.kt
  src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt
Labels: fix

#7551 COMP: Use suggestedNames() in lambda completion
  src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionTest.kt
Labels: feature

#7536 TYPE: show autocompletion popup when typing `|`
  src/main/kotlin/org/rust/ide/typing/RsDotTypedHandler.kt
  src/main/kotlin/org/rust/ide/typing/RsTypedHandler.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/typing/RsTypedHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt
Labels: feature

#7555 INSP: Handle unresolved method calls in unused imports inspection
  src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Labels: fix

#7383 FIX: support const parameters and trailing commas in ImplTraitToTypeParamIntention
  src/main/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntention.kt
  src/test/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntentionTest.kt
Labels: fix

#7552 INSP: move `Unused import` inspection into `Rust/Lints` inspection group
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#7563 INSP: Add option to enable unused import inspection in doctests
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
Labels: feature

#6410 COMP: Repr attribute layouts
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsReprCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsReprCompletionProviderTest.kt
Labels: feature

#7521 TY: lift aliasedBy from TyAdt to Ty
  src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsShortTypeRenderingTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: internal

#7534 COMP: improve completion inside impl trait
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
Labels: fix

#7571 COMP: reformat completed impl trait items after insertion
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
Labels: fix

#6838 INT: Convert local named function to lambda
  src/main/kotlin/org/rust/ide/intentions/ConvertFunctionToClosureIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/ConvertFunctionToClosureIntention/after.rs.template
  src/main/resources/intentionDescriptions/ConvertFunctionToClosureIntention/before.rs.template
  src/main/resources/intentionDescriptions/ConvertFunctionToClosureIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/ConvertFunctionToClosureIntentionTest.kt
Labels: feature

#7482 COMP: fix RsCompletionTestFixtureBase::checkCompletion
  src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsVisibilityCompletionTest.kt
Labels: internal

#7479 TY&RES: support const arguments that looks like type arguments
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: feature

#7532 ANN: add quick fix to implement missing supertrait(s)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFix.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFixTest.kt
Labels: feature

#7411 Take into account CARGO_HOME environment variable in Crates Local Index
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: fix

#7576 PERF: Optimize search scope for files with child modules
  src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Labels: performance

#7120 Take into account `pub(crate)` visibility in auto-import
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
Labels: fix

#7585 RES: Fix imported scoped macro vs textual macro from `extern crate`
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Labels: fix

#7588 FIX: Take into account const generics in `Move type constraint to parameter list` quickfix
  src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt
  src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToWhereClauseIntentionTest.kt
Labels: fix

#7593 FIX: add impl support to AddUnsafeFix
  src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
Labels: fix

#7587 RUN: Fix overflow when parsing coverage report
  coverage/src/main/kotlin/org/rust/coverage/LcovCoverageReport.kt
Labels: fix

#7601 REF: Don't try to move non-rust items in move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt
Labels: fix

#7569 The Rust 2021 Edition Autocompletion
  CONTRIBUTORS.txt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
Labels: feature

#7611 MACRO: fix proc macro expansion with Rust 1.54
  native-helper/Cargo.lock
  native-helper/Cargo.toml
Labels: fix

#7605 RES: Fix resolving re-exported derive macros by qualified path
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: fix

#7591 Highlight exit points when the caret at `fn` or `->` token
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunctionOrLambda.kt
  src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
Labels: feature
