Repository intellij-rust/intellij-rust, pull requests merged in 2021-12, with the labels that each got.

#8226 ANN: don't produce super trait is not implemented (E0277) for non fully known types
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#8217 REF: Fix extract function refactoring for argument of `println!` macro
  src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: fix

#8164 RES: Use hard references for new resolve data structures
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/RsDefMapSoftReferenceTest.kt
Labels: fix

#8241 RES: Fix handling $crate inside detached files
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/DollarCrateUtil.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Labels: fix

#7947 RES: Fix parallel macro expansion
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#8045 Fix auto-import in `include!`-ed files
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#8192 GRAM&ANN: Parse and annotate `~const` syntax
  src/main/grammars/RustLexer.flex
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPolybound.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/polybounds.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/polybounds.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/bounds.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/bounds.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
Labels: feature

#8261 TY: fix #8236
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#8235 TY&ANN: Fix false positive E0277 `Sized` is not satisfied
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFixTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
Labels: fix

#8233 MACRO: fix expansion of proc macros that weirdly mix token spans
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/MappedSubtree.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeParser.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
  testData/test-proc-macros/src/lib.rs
Labels: fix

#8278 Update ra_ap_proc_macro_srv - use a version from github
  .github/dependabot.yml
  native-helper/Cargo.lock
  native-helper/Cargo.toml
Labels: fix

#8230 REF: fix Extract Variable interaction with closures
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
Labels: fix

#8286 INSP: Don't show auto-import from auxiliary stdlib crates such as unwind
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
Labels: fix

#8288 RES: Add `extern crate alloc;` in auto-import if needed
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
Labels: fix

#8297 INSP: Fix default parameters handling in `Wrong number of type arguments` inspection
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt
Labels: fix

#8268 TY: fix type inference if dependencies have names as stdlib crates
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#8144 INSP: Detect E0747 error
  src/main/kotlin/org/rust/ide/annotator/fixes/EncloseExprInBracesFix.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddTypeArguments.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeArguments.kt
  src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeArgumentList.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprEvaluator.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsWrongGenericArgumentsOrder.html
  src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
Labels: feature

#7906 RUN: Fix Coverage runner for projects located on WSL file system
  coverage/src/main/kotlin/org/rust/coverage/LcovCoverageReport.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/util/ToolchainUtil.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/RustcVersion.kt
  src/test/kotlin/org/rust/cargo/runconfig/CargoTestRunStateTest.kt
  src/test/kotlin/org/rust/cargo/toolchain/RustcVersionParsingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTestBase.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CustomTargetCfgResolveTest.kt
Labels: fix

#7562 RUN: Don't use `Redirect Input from` when building
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
Labels: fix

#8165 INT: Fix "Invert if condition" when `return`/`continue` has no semicolon
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
Labels: fix

#8228 Do not offer `Add remaining patterns` fix when matching a non exhaustive enum
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
Labels: fix

#8310 GRD: update gradle and gradle plugins
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: internal

#8316 GRD: use `-Xjvm-default=all` and get rid of `@JvmDefault`
  build.gradle.kts
  src/main/kotlin/org/rust/RsProjectTaskQueueService.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAttrProcMacroOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldDecl.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPathReferenceElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsReferenceElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/main/kotlin/org/rust/lang/core/stubs/common/PsiOrStubInterfaces.kt
Labels: internal

#8318 MACRO: expand proc macros from [dev-dependencies]
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/RsProcMacroExpansionResolveIntegrationTest.kt
Labels: fix

#8132 REF: Add `Extract trait` refactoring
  src/main/kotlin/org/rust/cargo/project/RsToolchainPathChoosingComboBox.kt
  src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/RsMemberSelectionPanel.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitAction.kt
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/openapiext/ui.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/refactoring/RsExtractTraitTest.kt
Labels: feature

#7814 REF: support qualified paths in Generate Constructor refactoring
  src/main/kotlin/org/rust/ide/refactoring/generate/StructMember.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt
Labels: fix

#8291 INSP: Sort resolved paths first in auto-import
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#8263 INT: infer generic parameter types in ConvertClosureToFunctionIntention
  src/main/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntention.kt
  src/test/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntentionTest.kt
Labels: fix

#8315 COMP: complete 2nd path segment if the first segment is unresolved but can be imported
  src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Labels: feature

#8185 INT: Fix handling comments in `Invert if condition` intention
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
Labels: fix
