Repository intellij-rust/intellij-rust, pull requests merged in 2021-05, with the labels that each got.

#7237 Update Rust ML ranking provider to 0.2.2
  build.gradle.kts
  ml-completion/src/203/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
  ml-completion/src/211/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
Labels: feature

#6673 COMP: complete continue and break in expression context inside loops
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Labels: fix

#7239 RUN: Add sanity check for missing input file
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
Labels: feature

#7216 INSP: Introduce non-shorthand field patterns lint
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNonShorthandFieldPatternsInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsNonShorthandFieldPatterns.html
  src/test/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNonShorthandFieldPatternsInspectionTest.kt
Labels: feature

#7135 REF: add suggested refactoring support for function change signature
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSignaturePresentationBuilder.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringAvailability.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringExecution.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringStateChanges.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringSupport.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringUI.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsRenameSuggestedRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringTest.kt
Labels: feature

#7253 FIX: AddRemainingArms intention incorrectly prints enum names and variants if they are escaped rust keywords
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/utils/checkMatch/Pattern.kt
  src/test/kotlin/org/rust/ide/intentions/AddRemainingArmsIntentionTest.kt
Labels: fix

#6825 COMP: add all remaining arms match postfix template
  src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/resources/postfixTemplates/MatchPostfixTemplate/after.rs.template
  src/test/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplateTest.kt
Labels: feature

#7268 RUN: Fix toolchain validation on WSL
  src/211/main/kotlin/org/rust/cargo/toolchain/wsl/Utils.kt
Labels: fix

#7271 Don't throw exception on invalid user-created paths
  src/211/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RsSysPathToolchainFlavor.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
Labels: fix

#7274 CI: cancel previous ci runs via native `concurrency` feature
  .github/workflows/check.yml
  .github/workflows/regressions.yml
Labels: internal

#7244 ANN: Don't annotate `async` as a reserved keyword in attributes
  src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotatorTest.kt
Labels: fix

#7255 REF: add default values to suggested change signature refactoring
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringExecution.kt
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringUI.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt
Labels: feature

#7259 Support 2021.2 EAPs
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  .idea/runConfigurations/RunCLion.xml
  .idea/runConfigurations/RunIDEA.xml
  build.gradle.kts
  clion/src/203/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/211/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/212/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  gradle-211.properties
  gradle-212.properties
  gradle.properties
  intellij-toml/src/main/kotlin/org/toml/lang/parse/TomlParserDefinition.kt
  ml-completion/src/212/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
  ml-completion/src/test/kotlin/org/rust/ml/RsElementFeatureProviderTest.kt
  settings.gradle.kts
  src/203/main/kotlin/org/rust/debugger/runconfig/compatUtils.kt
  src/203/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/211/main/kotlin/org/rust/debugger/runconfig/compatUtils.kt
  src/211/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainFlavor.kt
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainProvider.kt
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/Utils.kt
  src/212/main/kotlin/org/rust/debugger/runconfig/compatUtils.kt
  src/212/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/212/main/kotlin/org/rust/ide/structure/compatUtils.kt
  src/212/main/kotlin/org/rust/ide/wordSelection/compatUtils.kt
  src/212/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/212/main/kotlin/org/rust/lang/core/psi/ext/compatUtils.kt
  src/212/main/resources/META-INF/platform-core.xml
  src/212/test/kotlin/org/rust/ide/search/RsUsageViewTreeTest.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
  src/main/kotlin/org/rust/ide/actions/InstallComponentAction.kt
  src/main/kotlin/org/rust/ide/actions/InstallTargetAction.kt
  src/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/test/kotlin/org/rust/lang/core/stubs/RsStubAccessTest.kt
Labels: feature

#7284 RUN: Fix fetching of cfg-options on WSL
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/RsTool.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt
Labels: fix
