Repository intellij-rust/intellij-rust, pull requests merged in 2021-06, with the labels that each got.

#7278 PRJ: Don't reset project toolchain after project creation
  src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
Labels: fix

#7003 INT: Introduce extract dependency in a separate table intention
  toml/src/main/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntention.kt
  toml/src/main/resources/META-INF/toml-only.xml
  toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/after.rs.template
  toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/before.rs.template
  toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/description.html
  toml/src/test/kotlin/org/rust/toml/intentions/CargoTomlIntentionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntentionTest.kt
Labels: feature

#7301 COMP: deduplicate method completion variants by name and trait
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
Labels: fix

#7318 Drop support of 2020.3 IDEs
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  README.md
  build.gradle.kts
  clion/src/203/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/main/kotlin/org/rust/clion/debugger/runconfig/RsCLionDebugRunnerUtils.kt
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacy.kt
  gradle-203.properties
  gradle.properties
  ml-completion/src/203/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
  ml-completion/src/212/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
  ml-completion/src/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
  src/203/main/kotlin/org/rust/debugger/runconfig/compatUtils.kt
  src/203/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/203/main/kotlin/org/rust/ide/structure/compatUtils.kt
  src/203/main/kotlin/org/rust/ide/wordSelection/compatUtils.kt
  src/203/main/kotlin/org/rust/lang/core/macros/compatUtils.kt
  src/203/main/kotlin/org/rust/lang/core/psi/ext/compatUtils.kt
  src/203/main/resources/META-INF/platform-core.xml
  src/203/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
  src/203/test/kotlin/org/rust/ide/search/RsUsageViewTreeTest.kt
  src/211/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/211/main/kotlin/org/rust/ide/structure/compatUtils.kt
  src/211/main/kotlin/org/rust/ide/wordSelection/compatUtils.kt
  src/211/main/kotlin/org/rust/lang/core/psi/ext/compatUtils.kt
  src/211/main/resources/META-INF/platform-core.xml
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainFlavor.kt
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainProvider.kt
  src/212/main/kotlin/org/rust/cargo/toolchain/wsl/Utils.kt
  src/212/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/212/main/kotlin/org/rust/ide/structure/compatUtils.kt
  src/212/main/kotlin/org/rust/ide/wordSelection/compatUtils.kt
  src/212/main/kotlin/org/rust/lang/core/psi/ext/compatUtils.kt
  src/212/main/resources/META-INF/platform-core.xml
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsRemoteToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainProvider.kt
  src/main/kotlin/org/rust/cargo/toolchain/wsl/Utils.kt
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
  src/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
  src/main/kotlin/org/rust/ide/statistics/RsToolchainUsagesCollector.kt
  src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
  src/main/kotlin/org/rust/ide/wordSelection/RsMacroCallSelectionHandler.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/openapiext/RsPathManager.kt
  src/main/kotlin/org/rust/stdext/Concurrency.kt
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#7068 COMP: Add completion for dependency tables using crates local index
  toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyCompletionProviders.kt
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProviders.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt
Labels: feature

#7315 REPL: Fix for Evcxr 0.10.0
  .github/workflows/check.yml
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt
  src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt
Labels: fix

#7273 RUN: Fix validation of input file
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
Labels: fix

#6455 Parse Markdown in Rust doc comments
  grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt
  src/main/grammars/RustDocHighlightingLexer.flex
  src/main/java/org/rust/lang/doc/psi/RsDocElementTypes.java
  src/main/java/org/rust/lang/doc/psi/RsDocHighlightingElementTypes.java
  src/main/kotlin/org/rust/ide/actions/RsJoinRawLinesHandler.kt
  src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
  src/main/kotlin/org/rust/ide/commenter/RsCommenter.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/formatter/blocks/RsFmtBlock.kt
  src/main/kotlin/org/rust/ide/formatter/impl/indent.kt
  src/main/kotlin/org/rust/ide/highlight/RsHighlighter.kt
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
  src/main/kotlin/org/rust/ide/typing/RsEnterInLineCommentHandler.kt
  src/main/kotlin/org/rust/lang/core/RsASTFactory.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
  src/main/kotlin/org/rust/lang/doc/lexer/RsDocHighlightingLexer.kt
  src/main/kotlin/org/rust/lang/doc/psi/Psi.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocComment.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocCommentElementType.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocElementTypes.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocHighlightingTokenType.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocKind.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocLine.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocTokenType.kt
  src/main/kotlin/org/rust/lang/doc/psi/ext/IElementType.kt
  src/main/kotlin/org/rust/lang/doc/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt
  src/main/kotlin/org/rust/lang/doc/psi/impl/RsDocCommentImpl.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/docs/RsRenderedDocumentationTest.kt
  src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/kotlin/org/rust/lang/doc/RsDocRemoveDecorationTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsParsingPerformanceTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/comment_binding.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/doc_comments.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/doc_comments.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
Labels: feature, internal

#7217 UI: Extend toolchain path field to have an opportunity to choose a suggested path
  src/main/kotlin/org/rust/cargo/project/RsToolchainPathChoosingComboBox.kt
  src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Labels: feature

#7333 Fix interop with `rainbow-brackets` plugin
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
Labels: fix

#7337 Fix NPE in debugger advertising runner in 2021.2 IDEs
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
Labels: fix

#7335 Fix <enter> typing between braces in doctest injections
  src/main/kotlin/org/rust/ide/actions/RsEnterHandler.kt
  src/main/kotlin/org/rust/ide/typing/RsEnterInLineCommentHandler.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/ide/typing/RsEnterInLineCommentHandlerTest.kt
  src/test/kotlin/org/rust/ide/typing/RsTypingTestBase.kt
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/after_inner_doc_comment.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/after_inner_doc_comment_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/after_line_comment.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/after_line_comment_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/after_module_comment.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/after_module_comment_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/at_file_beginning.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/at_file_beginning_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/directly_after_token.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/directly_after_token_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_block_comment.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_block_comment_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_inner_doc_comment.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_inner_doc_comment_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_line_comment.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_line_comment_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_outer_doc_comment.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/in_outer_doc_comment_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/inside_comment_inside_token.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/inside_comment_inside_token_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/inside_string_literal.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/inside_string_literal_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/inside_token.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/inside_token_after.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/issue578.rs
  src/test/resources/org/rust/ide/typing/lineComment/fixtures/issue578_after.rs
Labels: fix

#7300 ANN: Fix links to Clippy lints
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Labels: fix

#7339 INT: keep existing comments in NestUseStatementsIntention
  src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
  src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
Labels: fix

#7137 INT: add intention to create a tuple struct
  src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/CreateTupleStructIntention/after.rs.template
  src/main/resources/intentionDescriptions/CreateTupleStructIntention/before.rs.template
  src/main/resources/intentionDescriptions/CreateTupleStructIntention/description.html
  src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
Labels: feature

#7267 TY: infer expression type of log-like macros
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#7349 Fix rustdoc undecoration
  src/main/kotlin/org/rust/lang/core/macros/DocsLowering.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocCommentElementType.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocKind.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocLine.kt
  src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt
  src/test/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
  src/test/kotlin/org/rust/lang/doc/RsDocRemoveDecorationTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/comment_binding.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/doc_comments.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
Labels: fix

#7356 ANN: highlight format templates in custom macros
  src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: feature

#7288 Take `asm!` macro calls into account in control flow and data flow
  src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/macros.txt
Labels: fix

#7347 ANN: highlight emphasis and strong emphasis in rustdocs
  src/main/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/colors/RsColors.kt
  src/main/resources/org/rust/ide/colors/RustDarcula.xml
  src/main/resources/org/rust/ide/colors/RustDefault.xml
  src/main/resources/org/rust/ide/colors/highlighterDemoText.rs
  src/test/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotatorTest.kt
Labels: feature

#7060 INT: Generate documentation stub
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/intentions/GenerateDocStubIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/GenerateDocStubIntention/after.rs.template
  src/main/resources/intentionDescriptions/GenerateDocStubIntention/before.rs.template
  src/main/resources/intentionDescriptions/GenerateDocStubIntention/description.html
Labels: feature

#6842 INSP: extend RsSelfConventionInspection with get, set and with
  src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
Labels: feature

#7373 MACRO: support `:pat_param` `macro_rules!` matcher, fix `:pat` matcher
  src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/decl/FragmentKind.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt
Labels: feature, fix

#7243 fix highlighting variables//default to actually highlight variables only
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/colors/RsColors.kt
  src/main/kotlin/org/rust/ide/highlight/RsHighlighter.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/docs/RsCodeHighlightingInQuickDocumentationTest.kt
  src/test/kotlin/org/rust/ide/docs/RsRenderedDocumentationTest.kt
Labels: fix

#7390 CARGO: escape keywords in cargo test command invocations
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt
  src/main/kotlin/org/rust/ide/refactoring/RsNamesValidator.kt
  src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
  src/test/resources/org/rust/cargo/runconfig/producers/fixtures/use_raw_identifier_for_module_named_with_keyword.xml
Labels: fix

#7397 INT: considers siblings near caret in FlattenUseStatementsIntention
  src/main/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntention.kt
  src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt
Labels: fix

#7395 Properly escape crate urls produced by line markers in Cargo.toml
  toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
  toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
Labels: fix

#7316 DBG: Fix pretty printers if WSL toolchain is used
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
Labels: fix

#7401 Add API to get inferred method type and substitution
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
  src/main/kotlin/org/rust/lang/core/types/Substitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Labels: internal

#7407 FIX: parenthesize expressions where needed in Inline Value refactoring
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RsInlineValueTest.kt
Labels: fix

#7307 CI&MACRO: expand proc macros on Apple Silicon machines
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  build.gradle.kts
  src/main/kotlin/org/rust/openapiext/RsPathManager.kt
Labels: feature

#7412 REF: add support for type aliases in getter/setter generation
  src/main/kotlin/org/rust/ide/refactoring/generate/getter/GenerateGetterHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/setter/GenerateSetterHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateSetterActionTest.kt
Labels: fix

#7247 COMP: Display enums with variants in code completion popup when appropriate
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: feature

#7067 Invoke crates local index update on on cargo registry repository changes
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexStartupActivity.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/TestCratesLocalIndexServiceImpl.kt
Labels: feature
