Repository intellij-rust/intellij-rust, pull requests merged in 2022-12, with the labels that each got.

#9829 Fix NPE in RsGrammarCheckingStrategy on 2022.3
  grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt
Labels: fix

#9832 Fix `type info` action inside attribute procedural macro calls
  src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/test/kotlin/org/rust/ide/hints/type/RsExpressionTypeProviderTest.kt
  testData/test-proc-macros/src/lib.rs
Labels: fix

#9753 MACRO: get rid of `RsIncludeMacroIndex`, use `CrateDefMap` instead
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsIndexExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/builtin/RsBuiltinMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: fix

#9841 PERF: don't calculate CFG, Liveness and borrowck in cfg-disabled code
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
Labels: performance

#9851 MACRO: Don't add whitespace between tokens adjacent in macro call body
  src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/MappedSubtree.kt
  src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
  src/test/kotlin/org/rust/ide/hints/type/RsExpressionTypeProviderTest.kt
Labels: fix

#9804 MACRO: properly limit max depth of im-memory macro expansions
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/openapiext/psi.kt
  src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt
Labels: fix

#9803 HINT: Show type hints inside attribute procedural macros
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt
Labels: feature

#9528 PERF: move path caching root to a root type reference
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPathCachingRootTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: performance

#9836 Respect #[allow(clippy::wrong_self_convention)]
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsSelfConventionInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/inspections/RsInspectionSuppressorTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsSelfConventionInspectionTest.kt
Labels: feature

#9341 TYPE: fix action names in Undo stack
  src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt
  src/main/kotlin/org/rust/ide/refactoring/RsDowngradeModuleToFile.kt
  src/main/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryAction.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerfTest.kt
Labels: fix

#9858 ANN: Annotate range patterns
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatRange.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsRangeExpr.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Labels: feature

#9347 REF: Convert `Self` usages in "Convert struct to tuple" refactoring
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToTupleProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt
  src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt
Labels: fix

#8544 TY: Support type inference for GATs
  src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAssocTypeBinding.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiTypeImplUtil.kt
  src/main/kotlin/org/rust/lang/core/types/Substitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: feature

#9754 Remove `RsExternCrateReexportIndex` and `RsMacroCallIndex` since they are unused now
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroCallIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsExternCrateReexportIndex.kt
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#9796 TY: take into account `impl`s expanded from macro calls inside function bodies and `impl`s from doctests
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
Labels: fix

#9875 Fix `CFG_UNKNOWN` vs `ATTR_PROC_MACRO_CALL` code status
  src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt
  src/test/kotlin/org/rust/lang/core/psi/RsCodeStatusTest.kt
Labels: fix

#9816 INSP: Add support for E0044
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsTypeParamsInExternAnnotatorTest.kt
Labels: feature

#9794 Remove unused imports inside functions
  src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
  src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
Labels: fix
