Repository intellij-rust/intellij-rust, pull requests merged in 2022-10, with the labels that each got.

#7597 IDE: add imports after pasting code
  src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
  src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt
  src/main/kotlin/org/rust/ide/typing/paste/RsImportCopyPasteProcessor.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/ide/typing/paste/RsAddImportOnCopyPasteTest.kt
Labels: feature

#9344 REF: Fix adding import for default value in change signature refactoring
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#9332 Suggest importing modules in completion
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Labels: feature

#9434 COMP: don't prioritize functions that return `!` type (e.g. panic)
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
Labels: fix

#9433 COMP: Take into account some stdlib macro types
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/completion/RsTupleFieldCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
Labels: feature

#9430 TY: fix mixed type/const type arguments
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: fix

#9461 Fix issue #9432 random false-positives caused by GC activity
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt
  src/test/kotlin/org/rustSlowTests/RsGcSoftlyReachableObjectsCacheTest.kt
Labels: fix

#9239 CARGO: support new Cargo features syntax from 1.60.0
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/test/kotlin/org/rust/common.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlNameResolution.kt
  toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProviderTest.kt
Labels: feature

#9374 RES: Fix nested labels shadowing
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#9357 PERF: use `ModData` instead of `RsMod` in `VisibilityFilter`
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/PathResolutionContext.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Labels: performance

#9488 Make implementation query async
  src/222/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt
  src/223/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt
  src/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilderBase.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt
  src/test/kotlin/org/rust/ide/lineMarkers/LineMarkerTestHelper.kt
  src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt
Labels: performance

#9451 COMP: complete `'static` lifetime
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsStaticLifetimeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStaticLifetimeCompletionTest.kt
Labels: feature

#9480 Convert compiler features to json and update compiler features
  attributes-info/Cargo.lock
  attributes-info/Cargo.toml
  attributes-info/rustc_feature/build.rs
  attributes-info/rustc_span/build.rs
  attributes-info/src/main.rs
  build.gradle.kts
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/format/impl.kt
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt
  src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantAction.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/compiler-info/compiler-features.json
Labels: internal

#9502 ANN: annotate usage of `wasm` abi as experimental
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#9504 REF: Fix import references from return type in "Change signature"
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#9416 ANN: Fix handling auto-traits when checking orphan rules
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#9510 Don't use private reexport in crate root in auto-import
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#9485 RES: Fix passing paths with $crate to derive proc macro
  src/main/kotlin/org/rust/lang/core/macros/MacroCallBody.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
  testData/test-proc-macros/src/lib.rs
Labels: fix

#9507 INSP: Improve error message for E0407 (unknown member in trait impl)
  src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt
Labels: fix

#9358 TY: fix `todo!()` macro type inference
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#9459 RES: Resolve stdlib items in detached files
  ml-completion/src/main/kotlin/org/rust/ml/RsElementFeatureProvider.kt
  src/main/kotlin/org/rust/ide/actions/ShareInPlaygroundAction.kt
  src/main/kotlin/org/rust/ide/annotator/AnnotationSessionEx.kt
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddAsyncAttributeFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
  src/main/kotlin/org/rust/ide/annotator/format/impl.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/icons/RsIconProvider.kt
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/DeriveCopyFix.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryAction.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt
  src/main/kotlin/org/rust/ide/template/postfix/editable/RsPostfixTemplateExpressionCondition.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/FakeCrate.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DetachedDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/actions/RsRebuildDefMapsAction.kt
  src/main/kotlin/org/rust/lang/core/stubs/common/PsiOrStubInterfaces.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsExternCrateReexportIndex.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateTestBase.kt
Labels: feature

#9532 Enable build script evaluation by default
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature, to be documented

#9540 MACRO: fix proc macro expansion PSI cache invalidation
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: fix

#9537 INT: Fix "Attach file to module"
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/FakeCrate.kt
  src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt
Labels: fix

#9312 Filter not bang proc macros in completion
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Labels: fix

#9552 TY: properly infer type of custom macros which shadow built-in macros
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#7134 ANN: Add a quick fix to add missing trait definitions
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddDefinitionToTraitFix.kt
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/fixes/AddDefinitionToTraitFixTest.kt
Labels: feature

#9558 COMP: Fix proc macro completion in imports
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#9559 COMP: Fix duplicate completion of proc macros when there is local import
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
Labels: fix

#9469 Fix issue #9468 random false-positive `Variable is never used`
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/test/kotlin/org/rustSlowTests/RsGcSoftlyReachableObjectsCacheTest.kt
Labels: fix

#9562 Disable intention preview for some intentions
  src/main/kotlin/org/rust/ide/annotator/fixes/AddFeatureAttributeFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt
  src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt
Labels: fix

#8916 RUN: Emulate terminal for implicit run configurations by default on the nightly version of the plugin
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
  src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
Labels: feature

#9598 TY: fix `Self` substitution in the case of trait inheritance
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/types/TraitRef.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#9614 MACRO: Fix expansion of attr and derive proc macros inside functions
  src/main/kotlin/org/rust/lang/core/resolve2/util/RsBlockStubBuilder.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
Labels: fix

#9526 COMP: Guess proper type of brackets while proc macro call completion
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroDefinitionBase.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
  src/test/kotlin/org/rust/lang/core/completion/RsMacroBracketCompletionTest.kt
Labels: feature

#9170 COMP: Fix raw identifier in `use` cannot be complete
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#9615 MACRO: split `org.rust.macros.proc` experimental feature into 3 features
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt
  src/main/kotlin/org/rust/lang/core/psi/RsProcMacroPsiUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt
  src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
Labels: internal

#9620 Ty: normalize associated type in `impl` item trait ref
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#9628 MACRO: enable function-like procedural macro expansion in nightly plugin builds
  src/main/resources-nightly/META-INF/experiments.xml
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
Labels: feature

#9627 RUN: Don't show line markers for tests in dependence crates
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoBenchRunConfigurationProducer.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
Labels: fix

#9637 CARGO: don't fail build script evaluation without native helper
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
  src/test/kotlin/org/rust/common.kt
Labels: fix

#9650 Increase minimal supported version of rustc to 1.56
  .github/workflows/check.yml
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
Labels: feature

#8755 GRAM&ANN: add basic parsing and annotation of `let_chains`
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/inspections/RsConstantConditionIfInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt
  src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MergeIfsIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MoveGuardToMatchArmIntention.kt
  src/main/kotlin/org/rust/ide/intentions/SplitIfIntention.kt
  src/main/kotlin/org/rust/ide/presentation/PresentationInfo.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLetExpr.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/conditions.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/conditions.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/loops.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/match.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/match.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/patterns.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
Labels: feature
