Repository intellij-rust/intellij-rust, pull requests merged in 2022-09, with the labels that each got.

#9267 Fix auto import of attr proc macros
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#9280 MACRO: fix local proc macro expansion
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
Labels: fix

#8961 CARGO: invoke `cargo metadata` only for current platform
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/cargo/project/model/CargoPackagesTest.kt
  src/test/kotlin/org/rust/cargo/project/model/CargoStdlibPackagesTest.kt
Labels: feature

#9251 ANN: Detect E0728 error (`await` outside `async` function)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/MakeAsyncFix.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunctionOrLambda.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakeAsyncFixTest.kt
Labels: feature

#9270 REF: Simplify "Inline function" refactoring dialog
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineUtils.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueHandler.kt
Labels: fix

#9238 ANN: allow leading | in nested or patterns
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#9288 CARGO: reload the project model after changes in toolchain settings
  src/222/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
Labels: fix

#9295 GRD: fix searchable options building
  build.gradle.kts
  src/222/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
Labels: fix

#9256 ANN: Detect E0733 error (recursive async function)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddAsyncAttributeFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddAsyncRecursionAttributeFixTest.kt
Labels: feature

#9296 ACT: Remove resolve engine info from "Create new issue" action
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
Labels: feature

#7435 INT: generalize MatchToIfLetIntention to arbitrary arm count
  src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt
  src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
Labels: feature

#9298 REF: Fix "Inline function" dialog when number of occurrences is unknown
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionDialog.kt
Labels: fix

#9322 PERF: Speed up type parameters extraction in some places
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
Labels: performance

#9297 REF: Use function name instead of signature in "Inline function" dialog
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
Labels: fix

#9302 TYPE: provide human-readable name to some refactorings
  src/main/kotlin/org/rust/ide/refactoring/RsDowngradeModuleToFile.kt
  src/main/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryAction.kt
Labels: fix

#9211 PERF: resolve nested paths at once
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/PathResolutionContext.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsPathResolveResult.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Labels: performance

#9331 PERF: speed up `RsResolveProcessor.lazy()`, get rid of `LazyScopeEntry`
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
Labels: performance

#9176 CARGO: Use `--keep-going` when building and evaluating buildscripts
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
Labels: feature

#9325 CARGO: enable build script evaluation in nightly plugin builds
  src/221/main/resources/META-INF/platform-experiments.xml
  src/222/main/resources-nightly/META-INF/platform-experiments.xml
  src/222/main/resources-stable/META-INF/platform-experiments.xml
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
Labels: feature

#5911 ANN: Check if the custom attr override is used by `findInScope`
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
Labels: fix

#9337 PERF: move recursion guard out of `advancedResolve`
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
Labels: performance

#9334 PERF: optimize `getRootCachingElement` for stub-based case
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
Labels: performance

#9338 PERF: refactor and optimize lowering of `RsTypeRerefence` to `Ty`
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReference.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/Kind.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiTypeImplUtil.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPlaceholder.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: performance

#9327 RES: resolve assoc type in where pred with generic decl on upper level
  src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
Labels: fix

#9222 RUN: Don't erase the file content while formatting if `#![cfg_attr(rustfmt, rustfmt_skip)]` attribute is presented
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
Labels: fix

#9303 ANN: Don't show fix to make function async for function returning Future
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakeAsyncFixTest.kt
Labels: fix

#9336 Filter derive proc macros when auto-import in derive attribute
  src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#9313 COMP: Improve completion of proc macros
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Labels: feature

#9078 CARGO: don't override content entries
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt
Labels: fix

#9376 Drop support for 2022.1 platform
  .github/workflows/build-plugin.yml
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  README.md
  build.gradle.kts
  debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
  gradle-221.properties
  gradle.properties
  src/221/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/221/main/kotlin/org/rust/ide/refactoring/changeSignature/compatUtils.kt
  src/221/main/resources/META-INF/platform-experiments.xml
  src/221/main/resources/META-INF/platform-rust-core.xml
  src/222/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/222/main/kotlin/org/rust/ide/refactoring/changeSignature/compatUtils.kt
  src/222/main/resources-nightly/META-INF/platform-experiments.xml
  src/222/main/resources-stable/META-INF/platform-experiments.xml
  src/222/main/resources/META-INF/platform-rust-core.xml
  src/main/kotlin/org/rust/cargo/project/configurable/CargoProjectConfigurableProvider.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemIconProvider.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAware.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustfmtProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
  src/main/kotlin/org/rust/ide/todo/RsTodoSearcher.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerfTest.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlReferenceContributor.kt
  toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlUrlReferenceProvider.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlUrlResolveTest.kt
Labels: feature

#7157 IDE: Add support for navbar breadcrumbs
  src/main/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProvider.kt
  src/main/kotlin/org/rust/ide/navigationToolbar/RsNavBarModelExtension.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/miscExtensions/RsNavBarTest.kt
Labels: feature

#5866 INSP: add inspection to check associated type bindings
  src/main/kotlin/org/rust/ide/inspections/RsWrongAssocTypeArgumentsInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddAssocTypeBindingsFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveAssocTypeBindingFix.kt
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsWrongAssocTypeArguments.html
  src/test/kotlin/org/rust/ide/inspections/RsWrongAssocTypeArgumentsInspectionTest.kt
Labels: feature

#9335 INT: Support "Create associated function" for path `Self::func()`
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Labels: feature

#9293 REF: Fix adding imports in "Change signature" refactoring
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#9153 INT: Add an intention to import constants in match arms
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/intentions/AddImportForPatternIntention.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/intentionDescriptions/AddImportForPatternIntention/after.rs.template
  src/main/resources/intentionDescriptions/AddImportForPatternIntention/before.rs.template
  src/main/resources/intentionDescriptions/AddImportForPatternIntention/description.html
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
  src/test/kotlin/org/rust/ide/intentions/AddImportForPatternIntentionTest.kt
Labels: feature

#9308 COMP: Complete derive proc macros
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt
Labels: feature

#9428 MACRO: fix `format` macro expansion when param name is keyword (`self`) or there is a syntax error in param name
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/format/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/RsNamesValidator.kt
  src/main/kotlin/org/rust/lang/core/lexer/utils.kt
  src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/builtin/RsBuiltinMacroExpansionTest.kt
Labels: fix
