Repository intellij-rust/intellij-rust, pull requests merged in 2022-04, with the labels that each got.

#8683 PRJ: properly validate new Rust project name in minor IDEs
  src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
Labels: fix

#8699 Allow files generated by the buildscripts up to 8Mb in size
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: feature

#8703 LI: Dont inject doctests if there are unbalanced code fences in prev doc
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/main/kotlin/org/rust/lang/doc/psi/Psi.kt
  src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt
  src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
Labels: fix

#7998 RUN: Enable Valgrind for WSL toolchains
  clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
  clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
  clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindRunner.kt
  clion/src/main/kotlin/org/rust/clion/valgrind/legacy/RsValgrindRunnerLegacy.kt
  src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt
Labels: feature

#8738 Don't release editor of macro expansion view twice
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
Labels: fix

#8739 RUN: Fix events parsing in Test Tool Window
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestOutputEventSplitter.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
Labels: fix

#8726 TY: infer associated types on supertraits if possible
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#8675 IDE: use #[serde(rename)] attribute for fields when converting from JSON
  src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt
  src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteTest.kt
Labels: feature

#8784 ANN: don't highlight safe intrinsics as unsafe
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionErrorAnnotatorTest.kt
Labels: bug

#8746 PERF: Reuse single thread pool in name resolution
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ResolveCommonThreadPool.kt
Labels: performance

#8790 TY: improve type inference around call expressions
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#8796 RUN: Enable `Emulate terminal in console` option by default in nightly plugin on macOS and Linux
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature
