Repository intellij-rust/intellij-rust, pull requests merged in 2022-08, with the labels that each got.

#9097 CARGO: support IDEs without `Build Tools` settings
  src/221/main/resources/META-INF/platform-rust-core.xml
  src/222/main/kotlin/org/rust/cargo/project/configurable/CargoPlaceholderConfigurable.kt
  src/222/main/resources/META-INF/platform-rust-core.xml
  src/main/kotlin/org/rust/cargo/project/configurable/CargoBuildToolConfigurableProvider.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoProjectConfigurableProvider.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#9127 UI: Use checkbox for "Expand macros" setting
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/resources/messages/RsBundle.properties
Labels: to be documented

#9138 COMP: Fix auto-import when completing impl trait items
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
Labels: fix

#9146 FIX: Do not allow empty member selection in Extract struct fields and Generate getter/setter dialog
  src/main/kotlin/org/rust/ide/refactoring/extractStructFields/RsExtractStructFieldsAction.kt
  src/main/kotlin/org/rust/ide/refactoring/extractStructFields/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/BaseGenerateHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/constructor/GenerateConstructorHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/ui.kt
  src/main/resources/messages/RsBundle.properties
Labels: fix

#9150 REF: increase robustness of handling self parameters in Change Signature refactoring
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#9079 REPL: Inherit execute action shortcut from `Console.Execute.Multiline`
  src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
Labels: fix

#9160 Fix `attribute-info` compilation
  .idea/runConfigurations/Generate_compiler_features.xml
  attributes-info/rust-toolchain.toml
  attributes-info/rustc_span/src/symbol.rs
Labels: internal

#9158 Fix auto-import grouping with existing unnamed import
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix

#9155 TOML: suppress completion in Cargo.toml based on JSON scheme
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixture.kt
  toml/src/main/kotlin/org/rust/toml/jsonSchema/CargoTomlJsonSchemaProviderFactory.kt
  toml/src/main/resources/jsonSchema/cargo.toml-schema.json
  toml/src/main/resources/org.rust.toml.xml
  toml/src/test/kotlin/org/rust/toml/completion/CargoTomlCompletionTestBase.kt
Labels: fix

#9152 COMP: Fix redundant macro completion in mod item name
  src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#9083 RES: Fix resolve of enum variants in match pattern in some cases
  src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#9106 RES: Fix resolve of macro without `macro_export` reexported as macro 2.0
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Labels: fix

#9080 RES: Fix glob import of item with identity proc macro
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: fix

#9169 Hotfix #9110 by reverting #9021
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
Labels: fix

#9137 COMP: update list of autocompleted keys in Cargo.toml
  toml/src/main/kotlin/org/rust/toml/completion/RsTomlKeysCompletionProvider.kt
Labels: feature

#9168 Add slice pretty-printers
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/slice.rs
Labels: feature

#9104 PERF: reduce cfg evaluation in `expandedItemsCached` and cache `CfgEvaluator` for a crate
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/THashMapBase.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapMacroIndexConsistencyTest.kt
Labels: performance

#9081 MACRO: support liveness inspection for implicit args in `format_args`
  src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
  src/main/kotlin/org/rust/ide/annotator/format/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/format/impl.kt
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/macros/MappedText.kt
  src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorToolchainTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsBuiltinMacroExpansionTest.kt
Labels: fix

#9173 MACRO: Use `rust-analyzer-proc-macro-srv` from toolchain if available
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
Labels: fix

#9182 PERF: Index new stdlib parts `portable-simd`
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/test/kotlin/org/rust/lang/core/resolve2/TestAllStdlibFilesAreIndexed.kt
Labels: performance

#9194 Fix `java.io.IOException` during typing inside a macro call
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
Labels: fix

#9006 REF&MACRO: support rename refactoring of items expanded from a macro
  src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroBodyReferenceDelegateImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceBase.kt
  src/main/kotlin/org/rust/openapiext/Query.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
  testData/test-proc-macros/Cargo.lock
  testData/test-proc-macros/src/lib.rs
Labels: feature

#9200 DBG: Add `alloc::rc::Weak` and `alloc::sync::Weak` pretty-printers
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  prettyPrinters/gdb_lookup.py
  prettyPrinters/lldb_lookup.py
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/rc_arc.rs
Labels: feature

#8944 INSP: configure project to run inspections from command line
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/ide/inspections/CargoCommandLineInspectionProjectConfigurator.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
Labels: internal

#9190 PERF: speed up prelude processing using new resolve
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Labels: performance

#9203 DBG: Update `Ref`/`RefMut` pretty-printers to Rust 1.63 and add tests
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_providers.py
  pretty_printers_tests/tests/cell.rs
Labels: fix

#9188 PERF: speed up `containingCrate` and similar properties
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt
Labels: performance

#9208 PERF&MACRO: use stubs for expansions of macro calls inside `impl`s
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFileInternals.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsBuiltinMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/psi/RsPsiFileInternalsTest.kt
Labels: performance

#9225 CARGO: properly parse env variable in cargo config
  src/main/kotlin/org/rust/cargo/CargoConfig.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/cargo/toolchain/CargoConfigTest.kt
Labels: fix

#9209 DBG: Add summary pretty-printers for range types
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  prettyPrinters/gdb_lookup.py
  prettyPrinters/gdb_providers.py
  prettyPrinters/lldb_lookup.py
  prettyPrinters/lldb_providers.py
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/range.rs
Labels: feature

#9202 RES: Fix module declaration in `include!`-ed file
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
Labels: fix

#9233 Fix cargo features inference
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: fix

#9171 PERF: stop using `RsModuleIndex` in `RsFile.doGetCachedData`
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoPackageIndex.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
  src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: performance

#9236 PERF: re-revert #9021 speed up `getIncludingMod` usages
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
Labels: performance

#9237 DBG: Fix `Ref`/`RefMut` GDB pretty-printers on Rust 1.62
  prettyPrinters/gdb_providers.py
Labels: fix

#9234 CARGO: show error msg in Sync tool window if project dir does not exist
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
Labels: fix

#9235 Do not unconditionally succeed RUSTC_WRAPPER when run by build scripts
  native-helper/src/rustc_wrapper.rs
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: fix

#9269 COMP: add completions for more lints
  src/main/kotlin/org/rust/lang/core/completion/lint/ClippyLints.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RustcLints.kt
Labels: feature

#9265 Filter single mod in auto-import when root path resolves to same item
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Labels: fix
