Repository intellij-rust/intellij-rust, pull requests merged in 2022-11, with the labels that each got.

#9350 REF: Support renaming derive procedural macros
  src/main/kotlin/org/rust/ide/presentation/Utils.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsExternCrateCompletionTest.kt
  toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlKeyResolveTest.kt
Labels: feature

#9602 RUN: Don't allow to use Run targets alongside with WSL toolchain
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
Labels: fix

#9649 DBG: Enable native Rust support in MSVC LLDB in 2022.3 builds
  src/222/main/resources/META-INF/platform-rust-core.xml
  src/223/main/resources/META-INF/platform-rust-core.xml
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#9658 MACRO: do not trigger dumb mode when changing small quantity of macros
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
Labels: performance, fix

#9641 INT: Support intention preview
  src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt
  src/222/test/kotlin/org/rust/ide/intentions/RsIntentionTestPlatformBase.kt
  src/223/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt
  src/223/test/kotlin/org/rust/ide/intentions/RsIntentionTestPlatformBase.kt
  src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt
  src/main/kotlin/org/rust/ide/intentions/AddImportIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntention.kt
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/main/kotlin/org/rust/ide/intentions/RsElementBaseIntentionAction.kt
  src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt
  src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt
  src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
  src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt
  src/test/kotlin/org/rust/ide/intentions/AddFmtStringArgumentIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddImplTraitIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddImportIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddRemainingArmsIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/DestructureIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
  src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/SubstituteTypeAliasIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt
  toml/src/main/kotlin/org/rust/toml/Util.kt
  toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt
  toml/src/test/kotlin/org/rust/toml/intentions/CargoTomlIntentionTestBase.kt
Labels: feature

#9689 CARGO: fallback to hardcoded stdlib structure if fetching metadata fails
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
Labels: fix

#9667 Await macro expansion in `CargoCommandLineInspectionProjectConfigurator`
  src/main/kotlin/org/rust/ide/inspections/CargoCommandLineInspectionProjectConfigurator.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTaskListener.kt
Labels: internal

#9515 "Add missing fields" quickfix: add trailing comma if needed
  src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
Labels: fix

#9694 MACRO: enable derive proc macro expansion in nightly plugin
  src/main/resources-nightly/META-INF/experiments.xml
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: feature

#9708 COMP: fix completion in function-like macros
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: fix

#9470 COMP: improve completion in the middle of identifier
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsFullMacroArgumentCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt
Labels: fix

#9714 Ty: infer const arguments in a path qualifier type arguments
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/RsDiagnosticBasedInspection.kt
  src/main/kotlin/org/rust/lang/core/dfa/borrowck/BorrowChecker.kt
  src/main/kotlin/org/rust/lang/core/dfa/liveness/Liveness.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeInferenceCachingTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Labels: fix

#9585 Fix "Add unambiguous imports on the fly" in 223 platform
  src/222/main/kotlin/org/rust/ide/inspections/import/RsReferenceImporter.kt
  src/223/main/kotlin/org/rust/ide/inspections/import/RsReferenceImporter.kt
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/test/kotlin/org/rust/ide/inspections/import/RsReferenceImporterTest.kt
Labels: fix

#9737 Don't create separate undo entry when adding unambiguous import
  src/223/main/kotlin/org/rust/ide/inspections/import/RsReferenceImporter.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
Labels: fix

#9729 Enable `function-like` and `derive` proc macro expansion by default
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#9741 INT: Don't offer `Un-elide lifetimes` intention when no input lifetimes
  src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
  src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
Labels: fix

#9686 Parse rust path in short doc links
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/doc/psi/Psi.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocCommentElementType.kt
  src/main/kotlin/org/rust/lang/doc/psi/RsDocLinkDestinationParser.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsDocLinkResolveTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/doc_comments.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/doc_comments.txt
Labels: feature

#9345 INT: fix nesting of renamed imports
  src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
  src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
Labels: fix

#9761 Fix `RsLangItemIndex`: pick only cfg-enabled lang items
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt
Labels: fix

#9762 MACRO: fix find usages for pat bindings defined by macros
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Labels: fix

#9711 MACRO&COMP: let a proc macro know if it is invoked during completion
  src/main/kotlin/org/rust/lang/core/macros/RsMacroCallData.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroCallDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
Labels: feature

#9767 MACRO: fix `getContext()` for elements expanded from macros in pat ctx
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt
Labels: fix

#4768 ACT: show coerced type in "type info" (ctrl+shift+P)
  src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt
Labels: feature

#9783 TYPE: fix unavailable move item action
  src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt
Labels: fix

#9779 MACRO: refresh `MacroExpansionFileSystem` after project reopening
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Labels: fix

#9760 CARGO: track changes in crate roots of procedural macro libraries
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt
Labels: feature

#9788 Don't show "File does not belong to Cargo project" for scratch files
  src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt
Labels: fix

#9800 TY: fix impl search when there are multiple type aliases with same name
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#9808 GRAM: Parse half-open range patterns
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/patterns.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/patterns.txt
Labels: feature

#9823 COMP&MACRO: fix completion inside local macro calls in 2022.3
  src/main/kotlin/org/rust/lang/core/completion/Utils.kt
Labels: fix
