Repository intellij-rust/intellij-rust, pull requests merged in 2022-03, with the labels that each got.

#8461 REF: Support Extract trait refactoring for traits
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt
  src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt
  src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractSuperTraitTest.kt
  src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitBaseTest.kt
  src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitFromImplTest.kt
Labels: feature

#8639 RES: improve ambiguity resolution for type parameters between types and values with same names
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt
Labels: fix

#8565 UI: Render generic parameters for assoc types if any
  src/main/kotlin/org/rust/ide/presentation/PresentationInfo.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#8609 CARGO: use the same project toolchain to get info about stdlib as project uses
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt
  src/main/kotlin/org/rust/cargo/util/TestUnitTestRustcCacheService.kt
  src/main/kotlin/org/rust/cargo/util/UnitTestRustcCacheService.kt
  src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
Labels: fix

#8596 IDE: add derive to structs generated from JSON if `serde` is in dependencies
  src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt
  src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteToolchainTest.kt
Labels: feature

#8628 REF: Offer "Extract trait" refactoring only in Rust files
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitAction.kt
Labels: fix

#8563 REF: Fix inline function dialog
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/ui.kt
Labels: fix

#8648 REF: Create public trait if needed in "Extract trait" refactoring
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
  src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractSuperTraitTest.kt
  src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitFromImplTest.kt
Labels: fix

#8670 Do not initialize Cargo tool window too early
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Labels: fix

#8631 CARGO: build all targets during build script evaluation
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Labels: fix

#8679 CARGO: Ignore parsing for directories starting with dot
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Labels: fix

#8684 GRD: make 2022.1 platform default for development
  gradle.properties
Labels: internal

#8647 Collapse macro expansion steps into single one
  src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroCallBody.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/main/kotlin/org/rust/stdext/HashCode.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/InlineFile.kt
  src/test/kotlin/org/rust/ide/annotator/AnnotationTestFixtureBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
  src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
Labels: feature

#8674 REF: move cursor after generated constructor in GenerateConstructor action
  src/main/kotlin/org/rust/ide/refactoring/generate/constructor/GenerateConstructorHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt
Labels: fix

#8666 DBG: avoid `NoClassDefFoundError` in Rider 2021.3
  debugger/src/main/kotlin/org/rust/debugger/debuggingIntegration.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacy.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
Labels: fix

#8689 RUN: provide file links in terminal for dbg! macro output
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/filters/RsDbgFilter.kt
  src/test/kotlin/org/rust/cargo/runconfig/filters/RsDbgFilterTest.kt
Labels: feature
