Repository intellij-rust/intellij-rust, pull requests merged in 2022-07, with the labels that each got.

#8987 CARGO: detect changes in build scripts and notify users about it
  src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAware.kt
  src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt
  src/222/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt
  src/main/kotlin/org/rust/cargo/CargoConstants.kt
Labels: internal

#8998 REF&MACRO: fix macro metavar renaming
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBinding.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceBase.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Labels: feature

#8968 PERF: optimize `coerceUnsized` for equivalent types
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Labels: performance

#9015 PERF: cache `expandedStmtsAndTailExpr`
  src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt
Labels: performance

#9016 PERF: cache `MacroExpansionManager.getExpandedFrom`
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: performance

#8869 INSP: Use kotlin-semver to avoid false-positives in version comparison & enable version inspections
  build.gradle.kts
  src/main/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspection.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CrateVersionRequirement.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
  toml/src/main/kotlin/org/rust/toml/inspections/NewCrateVersionAvailableInspection.kt
  toml/src/main/resources/org.rust.toml.xml
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt
  toml/src/test/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspectionTest.kt
Labels: feature

#9025 GRD: make 2022.2 platform default for development
  gradle-222.properties
  gradle.properties
Labels: internal

#9024 ACT: support "type info" with field shorthand
  src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt
  src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStructLiteralField.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsStructExprFieldReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/test/kotlin/org/rust/ide/hints/type/RsExpressionTypeProviderTest.kt
Labels: feature

#9034 Fix `Undo` (Ctrl+Z) action after typing in a macro call
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/test/kotlin/org/rust/lang/core/macros/RsUndoAfterTypingInMacroTest.kt
Labels: fix

#9000 ANN: Check E0742 (visibilities can only be restricted to ancestor mods)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnnecessaryQualificationsInspection.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#9020 ANN: Detect E0430 error (multiple self imports in use group)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#8951 INSP: do not offer to remove unused patterns if they are required
  src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
Labels: fix

#8986 MACRO: try to fix up rust syntax before calling an attribute proc macro
  src/main/kotlin/org/rust/lang/core/macros/MacroCallBody.kt
  src/main/kotlin/org/rust/lang/core/macros/MappedText.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroSyntaxFixupTest.kt
Labels: fix

#9021 PERF: speed up `getIncludingMod` usages
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
Labels: performance

#7299 DBG: Pretty-print HashMap/HashSet with MSVC LLDB
  prettyPrinters/lldb/__init__.pyi
  prettyPrinters/lldb_providers.py
  pretty_printers_tests/tests/hash_map.rs
Labels: feature

#9058 Update ra_ap_proc_macro_srv
  native-helper/Cargo.lock
  native-helper/Cargo.toml
Labels: fix

#9026 ANN: Rework duplicate definition errors
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
Labels: feature

#9009 REF: Fix counting number of occurrences in inline function refactoring
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineUtils.kt
  src/main/kotlin/org/rust/ide/refactoring/inlineValue/ui.kt
Labels: fix

#9067 IDE: Fix feature popup missing component for `DataContext`
  toml/src/main/kotlin/org/rust/toml/CargoFeatureLineMarkerProvider.kt
Labels: fix

#9070 UI: migrate Kotlin UI DSL to second version
  debugger/src/main/kotlin/org/rust/debugger/settings/RsBreakOnPanicConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerDataViewConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerGeneralSettingsConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerUiComponent.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsExternalLinterConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
  src/main/kotlin/org/rust/cargo/runconfig/target/RsLanguageRuntimeConfigurable.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/WasmPackCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/ide/actions/ui/CargoNewCrateDialog.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt
  src/main/kotlin/org/rust/ide/module/CargoConfigurationWizardStep.kt
  src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt
  src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/extractStructFields/ui.kt
  src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt
  src/main/kotlin/org/rust/openapiext/ui.kt
  src/main/resources/messages/RsBundle.properties
Labels: internal

#9085 Fix deadlock in MacroExpansionFileSystem
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
Labels: fix

#9090 MACRO: limit maximal recursion depth to 1000
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#9074 PERF: optimize `expandedItemsCached`
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
Labels: performance

#9095 MACRO: Fix macro expansion error messages in several cases
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionErrorTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroErrorTest.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt
Labels: fix

#9027 PERF: reduce usages of `existsAfterExpansion` in annotators
  src/main/kotlin/org/rust/ide/annotator/AnnotationSessionEx.kt
  src/main/kotlin/org/rust/ide/annotator/RsAnnotationHolder.kt
  src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
  src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
  src/main/kotlin/org/rust/ide/presentation/Utils.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
Labels: performance

#9082 TY&COMP: support `.await`ing `IntoFuture`
  src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Labels: fix

#9107 RES: Fix propagation of `include!`-ed macros to child modules
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
Labels: fix

#9117 REF: Fix rename of item used in struct literal field shorthand
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Labels: fix
