Repository intellij-rust/intellij-rust, pull requests merged in 2022-01, with the labels that each got.

#8187 REF: Support indirect self-references in move refactoring
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Labels: fix

#8362 Update compiler features
  src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: fix

#8363 CI: set up dependabot for gradle dependencies
  .github/dependabot.yml
Labels: internal

#8382 Fix stuck external linter errors
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
Labels: fix

#8335 Do not run inspections on cfg-disabled files
  src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Labels: feature

#8323 CARGO: parse available compiler messages even if build script evaluation fails
  src/main/kotlin/org/rust/cargo/toolchain/impl/BuildMessages.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/RsProcMacroExpansionResolveIntegrationTest.kt
Labels: feature

#8400 Fix cargo features inference with renamed packages with hyphens
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Labels: fix

#8402 Suppress `Unresolved reference` inspection if the path qualifier is multiresolved
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Labels: fix

#8398 RES: Fix resolve of macros inside functions using new resolve
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/HangingModData.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveInsideFunctionsTest.kt
Labels: fix

#8401 RES: fix primitive vs mod
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#8408 Fix "Find usages" for modules with relative path attribute
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Labels: fix

#8392 Suppress `Unresolved reference` inspection in test mods in packages with cyclic dev-dependencies
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/lang/core/crate/Crate.kt
  src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
  src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/psi/RsIsUnderCfgTestTest.kt
Labels: fix

#8376 Fix `IllegalStateException` during new project creation after dynamic plugin loading
  src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Labels: fix

#8375 ANN: Make `Add missing fields` quick-fix work properly with raw identifiers
  src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsPatFixTest.kt
Labels: fix

#8410 TY: infer type of `&raw const` and `&raw mut` operators
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: feature

#8430 Mark usages in doctests as "Test usages"
  src/main/kotlin/org/rust/cargo/project/model/RsTestSourcesFilter.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#8146 INSP&ACT: Take into account const generics in `Wrong generic arguments number` inspection and corresponding quick fixes
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveGenericArguments.kt
  src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddImplTraitIntentionTest.kt
Labels: fix

#8444 CI: create release branch one day earlier
  scripts/check_release_branch_date.py
Labels: internal

#8438 COMP: enable ref and refm postfix completions for type references
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/resources/postfixTemplates/RefExprPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/RefExprPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/RefExprPostfixTemplate/description.html
  src/main/resources/postfixTemplates/RefTypePostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/RefTypePostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/RefTypePostfixTemplate/description.html
  src/main/resources/postfixTemplates/RefmExprPostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/RefmExprPostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/RefmExprPostfixTemplate/description.html
  src/main/resources/postfixTemplates/RefmTypePostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/RefmTypePostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/RefmTypePostfixTemplate/description.html
  src/test/kotlin/org/rust/ide/template/postfix/RefExprPostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/RefTypePostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/RefmExprPostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/RefmTypePostfixTemplateTest.kt
Labels: feature

#7867 RUN: Enable profiler for WSL 2 toolchains
  clion/src/main/kotlin/org/rust/clion/profiler/RsProfilerRunner.kt
  clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
  clion/src/main/kotlin/org/rust/clion/profiler/legacy/RsProfilerRunnerLegacy.kt
  clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
Labels: feature

#8265 DBG: second attempt to support debugging in Rider for Unreal Engine
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerDriverConfigurationProviderImpl.kt
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerGeneralSettingsConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt
  debugger/src/main/resources/META-INF/debugger-only.xml
  plugin/src/main/resources/META-INF/plugin.xml
Labels: feature, to be documented

#8456 Drop support of 2021.2 major builds
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  .idea/runConfigurations/RunCLion.xml
  .idea/runConfigurations/RunIDEA.xml
  README.md
  build.gradle.kts
  gradle-212.properties
  gradle.properties
  src/212/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/212/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/212/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/212/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentEditorTextField.kt
  src/212/main/kotlin/org/rust/ide/notifications/RsUntrustedNotificationProvider.kt
  src/212/main/kotlin/org/rust/ide/refactoring/changeSignature/compatUtils.kt
  src/212/main/kotlin/org/rust/ide/security/RsTrustChangeNotifier.kt
  src/212/main/kotlin/org/rust/ide/security/trustedProjectUtils.kt
  src/212/main/resources/META-INF/platform-rust-core.xml
  src/213/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/213/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/213/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/213/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentEditorTextField.kt
  src/213/main/kotlin/org/rust/ide/refactoring/changeSignature/compatUtils.kt
  src/213/main/kotlin/org/rust/ide/security/trustedProjectUtils.kt
  src/213/main/resources/META-INF/platform-rust-core.xml
  src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentPopup.kt
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
  src/main/kotlin/org/rust/ide/security/RsTrustStateListener.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProviderTest.kt
Labels: feature

#8431 Refactor process running code: use RsResult instead of exceptions
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsCapturingProcessHandler.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt
  src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt
  src/main/kotlin/org/rust/ide/actions/RustfmtCargoProjectAction.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/main/kotlin/org/rust/ide/formatter/RustfmtFormattingService.kt
  src/main/kotlin/org/rust/ide/module/RsModuleBuilder.kt
  src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
  src/main/kotlin/org/rust/ide/newProject/Utils.kt
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
  src/main/kotlin/org/rust/openapiext/CommandLineExt.kt
  src/main/kotlin/org/rust/openapiext/RsProcessResult.kt
  src/main/kotlin/org/rust/stdext/RsResult.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/cargo/toolchain/CargoProjectGenerationTest.kt
Labels: internal

#8266 Implement "Add unambiguous imports on the fly" option
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportHintFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/RsReferenceImporter.kt
  src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
  src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/annotator/AnnotationTestFixtureBase.kt
  src/test/kotlin/org/rust/ide/inspections/import/RsReferenceImporterTest.kt
Labels: feature

#8489 Update `ra_ap_proc_macro_srv` to `0.0.94`, fix disk usage, fix pwd
  native-helper/Cargo.lock
  native-helper/Cargo.toml
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/Request.kt
Labels: fix

#8490 ANN: don't highlight format templates in cfg-disabled code
  src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: fix
