Repository intellij-rust/intellij-rust, pull requests merged in 2022-02, with the labels that each got.

#8357 REF: support fields with qualified type paths in Generate getter/setter
  src/main/kotlin/org/rust/ide/refactoring/generate/getter/GenerateGetterHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/setter/GenerateSetterHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateSetterActionTest.kt
Labels: fix

#8358 INSP: handle arbitrary and explicit self parameter in RsSelfConventionInspection
  src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
Labels: fix

#8505 ACT: Fix an exception in `Un-elide lifetimes` intention while processing nested ADTs
  src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
  src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
Labels: fix

#8501 REF: fix change signature inside extern block
  src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
  src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Labels: fix

#8436 ANN: Don't suggest multi-part quick fixes from External Linter
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFix.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
Labels: fix

#8514 Refactor completion variants sorting: use weighers
  ml-completion/src/main/kotlin/org/rust/ml/RsElementFeatureProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsBoolCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsFragmentSpecifierCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLookupElement.kt
  src/main/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsReprCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsTupleFieldCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsVisRestrictionCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsVisibilityCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RsLintCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/sort/RsCompletionWeigher.kt
  src/main/kotlin/org/rust/lang/core/completion/sort/RsCompletionWeighers.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
Labels: internal

#8515 #6411: Provide context features and more element features for ML-completion
  ml-completion/src/main/kotlin/org/rust/ml/RsCompletionFeaturesPolicy.kt
  ml-completion/src/main/kotlin/org/rust/ml/RsContextFeatureProvider.kt
  ml-completion/src/main/kotlin/org/rust/ml/RsElementFeatureProvider.kt
  ml-completion/src/main/resources/META-INF/ml-completion-only.xml
  ml-completion/src/test/kotlin/org/rust/ml/RsElementFeatureProviderTest.kt
  src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLookupElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
Labels: feature

#8516 Disable "liftShorter" completion classifier on 221 platform
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
Labels: fix

#8524 Use `Self` for constructor expression in `GenerateConstructor` action
  src/main/kotlin/org/rust/ide/refactoring/generate/constructor/GenerateConstructorHandler.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt
Labels: fix

#8531 INT: Take into account type arguments/parameters ordering and const generics in some intentions/fixes
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/actions/RsMoveLeftRightHandler.kt
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFix.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/hints/parameter/RsGenericParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspection.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/ElideLifetimesFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/RemoveGenericArguments.kt
  src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt
  src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodOrPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeArgumentList.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameterList.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
  src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
Labels: fix

#8532 DBG: Hide filtering button
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
Labels: fix

#8538 INSP: update bundled spellchecker dictionary
  src/main/kotlin/org/rust/ide/spelling/RsSpellCheckerDictionaryGenerator.kt
  src/main/kotlin/org/rust/ide/spelling/RsSpellCheckerGenerateDictionariesAction.kt
  src/main/resources/org/rust/ide/spelling/rust.dic
  src/test/kotlin/org/rust/ide/spellchecker/RsSpellCheckerTest.kt
Labels: fix

#7977 REF: Render generic parameters for associated types in `Implement Members`
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/ui.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#8446 ANN: Detect E0049 (Implementation has wrong number of type or const parameters)
  src/main/kotlin/org/rust/ide/inspections/RsWrongGenericParametersNumberInspection.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsWrongGenericParametersNumber.html
  src/test/kotlin/org/rust/ide/inspections/RsWrongGenericParametersNumberInspectionTest.kt
Labels: feature

#8580 ANN: Don't suggest multi-span quick fixes from External Linter
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
Labels: fix

#7816 IDE: convert JSON object to Rust struct after paste
  src/main/kotlin/org/rust/ide/typing/paste/JsonStructParser.kt
  src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteTest.kt
Labels: feature

#8184 INSP: remove spurious unreachable warnings for match exprs with no arms
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Labels: fix

#8594 ANN: don't suggest adding `unsafe` to main function in build scripts
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunConfigurationProducer.kt
  src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoExecutableRunLineMarkerContributorTest.kt
  src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
  src/test/kotlin/org/rust/ide/lineMarkers/RsLineMarkerProviderTestBase.kt
  toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt
Labels: fix

#7864 RUN: Correctly handle `+toolchain` in Cargo command configuration
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskProvider.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTest.kt
Labels: fix

#8578 add --respect-source-config to Cargo vendor
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
Labels: fix
