Repository intellij-rust/intellij-rust, pull requests merged in 2022-06, with the labels that each got.

#8888 TY: take into account recursion limit in associated type normalization
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#8890 PERF: slightly speed up `canCombineTypes`
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/utils/snapshot/Snapshot.kt
Labels: performance

#8807 RUN: Use proper terminal if `Emulate terminal in output console` option is enabled
  src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsProcessHandler.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt
  src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
  src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunState.kt
Labels: feature

#8864 ACT: Fix rendering of assoc type bindings in `Implement members` action
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#8881 ANN: Get rid of toolchain validation in local inspections
  src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt
Labels: performance

#8907 RES: Fix resolve of macros when other item with same name is in scope
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Labels: fix

#8900 MACRO: Remove Old Macro Expansion Engine
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
  src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/IterPostFixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
  src/test/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplateTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Labels: fix

#8925 Update ra_ap_proc_macro_srv - use a version from GitHub
  .github/dependabot.yml
  .github/workflows/check.yml
  native-helper/Cargo.lock
  native-helper/Cargo.toml
Labels: fix

#8934 COMP: add completion for `clippy::all`
  scripts/fetch_lints.py
  src/main/kotlin/org/rust/lang/core/completion/lint/ClippyLints.kt
  src/main/kotlin/org/rust/lang/core/completion/lint/RustcLints.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLintCompletionProviderTest.kt
Labels: fix

#8919 CARGO: support common approach for project model reloading for Cargo via `ExternalSystemProjectAware`
  build.gradle.kts
  src/221/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/221/main/resources-nightly/META-INF/platform-experiments.xml
  src/221/main/resources-stable/META-INF/platform-experiments.xml
  src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAware.kt
  src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt
  src/222/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/222/main/resources-nightly/META-INF/platform-experiments.xml
  src/222/main/resources-stable/META-INF/platform-experiments.xml
  src/222/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#8730 IDE: add support for unifying structs in arrays containing nulls
  src/main/kotlin/org/rust/ide/typing/paste/JsonStructParser.kt
  src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteTest.kt
Labels: feature

#8952 COMP: fix method completion filtering by trait bounds with autoderef
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
Labels: fix

#8957 TY&RES: take into account impls for macro types
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#8955 PERF: reduce memory usage by `TraitImplSource` instances
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Labels: performance

#8943 TY: take into account negative impls
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/refactoring/generate/BaseGenerateHandler.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
Labels: fix

#8946 DBG: Add registry flag to enable native Rust support in MSVC LLDB
  clion/src/main/kotlin/org/rust/clion/debugger/RsCLionDebuggerDriverConfigurationProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/RsDefaultDebuggerDriverConfigurationProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunParameters.kt
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#8960 CARGO: watch changes in cargo config and rust toolchain files
  src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt
  src/222/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt
  src/main/kotlin/org/rust/cargo/CargoConstants.kt
Labels: internal

#8967 TY&RES: fix method picking by self type when self type is arbitrary
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Labels: fix

#8980 CARGO: provide icon for Cargo project reloading
  src/221/main/resources/META-INF/platform-rust-core.xml
  src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemIconProvider.kt
  src/222/main/resources/META-INF/platform-rust-core.xml
  src/main/kotlin/org/rust/cargo/icons/CargoIcons.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/icons/reloadRustProject.svg
  src/main/resources/icons/reloadRustProject_dark.svg
Labels: internal

#8972 ANN: Check E0429 and E0431 (self imports)
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#8850 TY: implement type adjustments
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/main/kotlin/org/rust/lang/core/dfa/MemoryCategorization.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsIndexExpr.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsIndexExprReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Autoderef.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsMemoryCategorizationTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsAdjustmentTest.kt
Labels: fix, internal

#8981 PERF: slightly speed up `canCombineTypes` (2nd attempt)
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
Labels: performance

#8977 PERF&MACRO: edit single macro without entering the dumb mode
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/openapiext/utils.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
Labels: performance, fix

#8978 PERF: introduce dependencies modification tracker
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedTypeAlias.kt
  src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
  src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerfTest.kt
Labels: performance

#8985 PERF: Don't increment rust structure mod tracker on change in macro call
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
Labels: performance

#8989 MACRO: fix macro expansion error messages, add tests for them
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt
  src/main/kotlin/org/rust/lang/core/macros/errors/ResolveMacroWithoutPsiError.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt
Labels: fix
