Repository intellij-rust/intellij-rust, pull requests merged in 2023-07, with the labels that each got.

#10119 RUN: Support `Emulate terminal in output console` for Debug runner
  clion/src/main/kotlin/org/rust/clion/debugger/RsCLionDebuggerDriverConfigurationProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerDriverConfigurationProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/RsDefaultDebuggerDriverConfigurationProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunParameters.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsProcessHandler.kt
Labels: feature

#10645 Fix live templates suggestion in loop labels and other positions
  src/main/kotlin/org/rust/ide/template/RsContextType.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/org/rust/ide/liveTemplates/iterations.xml
  src/main/resources/org/rust/ide/liveTemplates/other.xml
  src/main/resources/org/rust/ide/liveTemplates/output.xml
  src/main/resources/org/rust/ide/liveTemplates/test.xml
  src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt
Labels: fix

#10647 COMP: complete Cargo instructions in build scripts
  src/main/kotlin/org/rust/lang/core/completion/RsBuildScriptCargoInstructionCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsBuildScriptCargoInstructionCompletionTest.kt
Labels: feature

#10428 (INT): Fix `Add unsafe to function` quickfix false positives
  src/main/kotlin/org/rust/ide/fixes/AddUnsafeFix.kt
  src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
Labels: fix

#10648 Show `Unresolved Reference` error for type-independent paths
  src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Labels: feature

#10436 (ANN): Change bare trait object lint to error E0782
  src/main/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspection.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspectionTest.kt
Labels: feature

#10654 INSP: Fix false-positive `Use of moved value` for lambda expressions in `for` loops
  src/main/kotlin/org/rust/lang/core/types/regions/Scope.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: fix

#10592 INSP: Enable path statements inspection by default
  src/main/kotlin/org/rust/ide/inspections/lints/RsPathStatementsInspection.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/types/infer/NeedsDrop.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/inspections/lints/RsPathStatementsInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsNeedsDropTest.kt
Labels: feature

#10661 GRAM&ANN: Permissive parsing for `impl` and `dyn` in type parameters bounds
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParamBounds.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impl_dyn_type_bound.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/impl_dyn_type_bound.txt
Labels: feature

#10663 Don't add new line by smart enter action after `;` completion
  src/main/kotlin/org/rust/ide/typing/assist/AfterSemicolonEnterProcessor.kt
  src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
  src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt
Labels: fix

#10664 INSP: main function is async (E0752)
  .gitignore
  src/main/kotlin/org/rust/ide/inspections/RsAsyncMainFunctionInspection.kt
  src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsAsyncMainFunction.html
  src/test/kotlin/org/rust/ide/inspections/RsAsyncMainFunctionInspectionTest.kt
Labels: feature

#10669 Normalize parameter values after substitution in struct pattern matching
  src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
  src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
  src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
Labels: fix

#10670 GDB: Initial support for gdb debugging outside CLion
  debugger/src/231/main/kotlin/org/rust/debugger/RsDebuggerUrlProvider.kt
  debugger/src/232/main/kotlin/org/rust/debugger/RsDebuggerUrlProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/DebuggerAvailability.kt
  debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
  debugger/src/main/kotlin/org/rust/debugger/RsDefaultDebuggerDriverConfigurationProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt
  debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
Labels: internal

#10671 INSP: use new API from to detect grammar errors
  grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt
  grazie/src/main/kotlin/org/rust/grazie/RsTextExtractor.kt
  grazie/src/main/resources/org.rust.grazie.xml
  grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
Labels: fix

#10675 MACRO: fix error message for non-expanded macro inside an impl
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroErrorTest.kt
Labels: fix

#10676 RES: Fix name resolution inside a nested block under cfg attribute
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Labels: fix

#10674 Fix dependency keys completion when another key exists before
  toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
  toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
  toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependencyKeysCompletionProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt
Labels: fix

#10679 COMP: Show completion auto-popup when literal suffix is typed
  src/main/kotlin/org/rust/ide/typing/RsTypedHandler.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionLiteralSuffixAutoPopupTest.kt
Labels: feature

#10680 COMP: Only complete float suffixes for literals in scientific notation
  src/main/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProviderTest.kt
Labels: fix

#10681 PARSE&ANN: Permissive parsing of struct inheritance
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/struct_inheritance.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/struct_inheritance.txt
Labels: feature

#10682 Fix scope for `macro` template
  src/main/resources/org/rust/ide/liveTemplates/other.xml
  src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt
Labels: fix

#10684 GRAM&TY&ANN: Permissive parsing for prefix/postfix operators
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/ReplaceIncDecOperatorFix.kt
  src/main/kotlin/org/rust/ide/inspections/RsDoubleNegInspection.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceIncDecOperatorFixTest.kt
  src/test/kotlin/org/rust/ide/inspections/RsDoubleNegInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/block_cast_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/inc_dec.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/inc_dec.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/const_generics.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/inc_dec.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/inc_dec.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/macros.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/match_expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/reserved_keywords.txt
Labels: feature

#10686 Fix recently introduced i18n problems
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
Labels: fix

#10689 Complete chained iterator methods
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
Labels: feature

#10702 COMP: Don't show literal suffix completion if the literal already contains a suffix
  src/main/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProviderTest.kt
Labels: fix

#10706 Fix stdlib deps fetching on 1.72.0-beta
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
Labels: fix

#10708 Update 2023.2 IDE and plugin dependencies
  build.gradle.kts
  gradle-232.properties
  gradle.properties
Labels: internal

#10714 PARSE&TY&ANN: Support `c_str_literal` feature
  src/main/grammars/RustLexer.flex
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsLiteralAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/format/impl.kt
  src/main/kotlin/org/rust/ide/highlight/RsHighlighter.kt
  src/main/kotlin/org/rust/ide/injected/RsStringLiteralEscaper.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/typing/RsQuoteHandler.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/lexer/RsEscapesLexer.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/RsLiteralKind.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/lexer/RsLexingTestCase.kt
  src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
  src/test/resources/org/rust/lang/core/lexer/fixtures/c_string_literals.rs
  src/test/resources/org/rust/lang/core/lexer/fixtures/c_string_literals.txt
Labels: feature

#10719 Fix Cargo tool window initialization on 2023.3
  src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
Labels: fix

#10721 Consider trait bounds when performing dereference
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Autoderef.kt
  src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Labels: fix

#10720 RES: resolve enum variants through a type
  src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
Labels: fix

#10718 Add macro expansion to quick doc
  src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
Labels: feature

#10726 Add inspection `thread_rng().gen()` to `random()`
  src/main/kotlin/org/rust/ide/inspections/RsThreadRngGenInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsThreadRngGen.html
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/inspections/RsThreadRngGenInspectionTest.kt
Labels: feature

#10729 Add quick fix for printing struct without Debug or Display
  src/main/kotlin/org/rust/ide/annotator/format/impl.kt
  src/main/kotlin/org/rust/ide/fixes/DeriveDebugAndChangeFormatToDebugFix.kt
  src/main/kotlin/org/rust/ide/fixes/ImplementDisplayFix.kt
  src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: feature

#10739 Support inspection "Unused must_use" for `impl Trait`
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMustUseInspection.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedMustUseInspectionTest.kt
Labels: feature

#10744 Improve completion of `if` and `match` keywords
  src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Labels: feature

#10748 Add Expectation to RsTypeInferenceWalker.inferMacroAsExpr
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt
Labels: fix

#10755 Implement `impl`s search for an alias of alias and for a use alias
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionStubsProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsCachedTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsImplIndexAndTypeAliasCache.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsAliasIndex.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
  src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Labels: fix

#10756 Enable VCS Code Vision hints by default
  src/232/test/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionTestCase.kt
  src/main/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionContext.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#10760 Adjust intellisense file size limit for Rust files
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/lang/core/psi/RsFileViewProviderFactory.kt
  src/main/kotlin/org/rust/lang/core/resolve/indexes/RsAliasIndex.kt
  src/main/resources/META-INF/rust-core.xml
Labels: fix

#10763 Enable `RsReferenceCodeVisionProvider` for top-level items
  src/232/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt
  src/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/PathResolutionContext.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsStructExprFieldReferenceImpl.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
Labels: feature
