Repository intellij-rust/intellij-rust, pull requests merged in 2023-03, with the labels that each got.

#10196 Do not run inspections which uses resolve on files outside valid project
  src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNonShorthandFieldPatternsInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsRedundantSemicolonsInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsSelfConventionInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspection.kt
Labels: fix

#10200 ANN: Highlight that `_` can only be used on the left-hand side of an assignment
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Labels: feature

#10215 support let-else statement for CFG
  src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt
  src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Labels: fix

#10096 RES: Improve support for identity attribute proc macros
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
  src/main/kotlin/org/rust/ide/inspections/RsWithMacrosInspectionVisitor.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
  src/main/kotlin/org/rust/lang/core/psi/AttrCache.kt
  src/main/kotlin/org/rust/lang/core/psi/HardcodedProcMacroProperties.kt
  src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAttrProcMacroOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMembers.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionRangeMappingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
  testData/test-proc-macros/src/lib.rs
Labels: fix

#10230 HINT: Add hints for chained method calls in attribute procedural macros
  src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
  src/test/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProviderTest.kt
Labels: feature

#10231 GRD: add plugin sources to plugin zip archive
  build.gradle.kts
  src/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProviderBase.kt
Labels: internal

#10229 ANN: add `RsDiagnostic`-based API for quick-fixes with arbitrary ranges
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/AnnotationTestFixtureBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFixTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFixTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/DoctestFixTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFixTest.kt
Labels: fix

#10179 ANN: Add support for E0785
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsImplForDynTraitTest.kt
Labels: feature

#10182 INT: Make intention actions work inside an attribute macro expansion
  src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/ide/intentions/AddCurlyBracesIntention.kt
  src/main/kotlin/org/rust/ide/intentions/AddDeriveIntention.kt
  src/main/kotlin/org/rust/ide/intentions/AddElseIntention.kt
  src/main/kotlin/org/rust/ide/intentions/AddImportForPatternIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ChangeReferenceMutabilityIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ConvertFunctionToClosureIntention.kt
  src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt
  src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt
  src/main/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntention.kt
  src/main/kotlin/org/rust/ide/intentions/FlipBinaryExpressionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/GenerateDocStubIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntention.kt
  src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/main/kotlin/org/rust/ide/intentions/JoinWildcardsIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ListIntentionBase.kt
  src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MergeIfsIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MoveGuardToMatchArmIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt
  src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToWhereClauseIntention.kt
  src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
  src/main/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ReplaceBlockCommentWithLineCommentIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ReplaceLineCommentWithBlockCommentIntention.kt
  src/main/kotlin/org/rust/ide/intentions/RsElementBaseIntentionAction.kt
  src/main/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentions.kt
  src/main/kotlin/org/rust/ide/intentions/RunCargoExpandIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ShareInPlaygroundIntention.kt
  src/main/kotlin/org/rust/ide/intentions/SplitIfIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ToggleIgnoreTestIntention.kt
  src/main/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntention.kt
  src/main/kotlin/org/rust/ide/intentions/WrapLambdaExprIntention.kt
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt
  src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentPopup.kt
  src/main/kotlin/org/rust/ide/intentions/util/macros/IntentionInMacroUtil.kt
  src/main/kotlin/org/rust/ide/intentions/util/macros/InvokeInside.kt
  src/main/kotlin/org/rust/ide/intentions/util/macros/RsIntentionInsideMacroExpansionContext.kt
  src/main/kotlin/org/rust/ide/intentions/util/macros/RsIntentionInsideMacroExpansionEditor.kt
  src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt
  src/main/kotlin/org/rust/ide/utils/PsiInsertionPlace.kt
  src/main/kotlin/org/rust/ide/utils/PsiModificationUtil.kt
  src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt
  src/main/kotlin/org/rust/ide/utils/template/RsTemplateBuilder.kt
  src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/DollarCrateUtil.kt
  src/main/kotlin/org/rust/openapiext/Editor.kt
  src/main/kotlin/org/rust/openapiext/ui.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
Labels: feature

#10260 INT: Fix `StackOverflowError` in `Invert if condition` intention
  src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
  src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
Labels: fix

#10277 T: set up tests for an intention action inside an attribute macro
  intelliLang/src/test/kotlin/org/rust/ide/intentions/InjectLanguageIntentionTest.kt
  src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
  src/test/kotlin/org/rust/RsJUnit4ParameterizedTestRunner.kt
  src/test/kotlin/org/rust/RsJUnit4TestRunner.kt
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/SkipTestWrapping.kt
  src/test/kotlin/org/rust/TestWrapping.kt
  src/test/kotlin/org/rust/ide/intentions/AddImportForPatternIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/AddImportIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/RemoveDbgIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
  src/test/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentionBaseTest.kt
  src/test/kotlin/org/rust/ide/intentions/ShareInPlaygroundIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt
  src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
  src/test/kotlin/org/rust/ide/previewUtils.kt
  toml/src/test/kotlin/org/rust/toml/intentions/CargoTomlIntentionTestBase.kt
Labels: internal

#6675 IDE: basic implementation of SSR (Struct, ConstantItem, MetaItem, Types)
  CONTRIBUTORS.txt
  src/main/kotlin/org/rust/ide/ssr/RsCompilingVisitor.kt
  src/main/kotlin/org/rust/ide/ssr/RsMatchingVisitor.kt
  src/main/kotlin/org/rust/ide/ssr/RsPredefinedConfigurations.kt
  src/main/kotlin/org/rust/ide/ssr/RsStructuralSearchProfile.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/ssr/RsSSRConstantTest.kt
  src/test/kotlin/org/rust/ide/ssr/RsSSRMetaItemTest.kt
  src/test/kotlin/org/rust/ide/ssr/RsSSRStructTest.kt
  src/test/kotlin/org/rust/ide/ssr/RsSSRTestBase.kt
  src/test/kotlin/org/rust/ide/ssr/RsSSRTypeTest.kt
Labels: feature

#10265 ANN: Don't show "Conditionally disabled code" in the `Problems` view
  src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt
Labels: fix

#10283 ANN: Improve E0784 (union expr does not have exactly one field)
  src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/RemoveStructLiteralFieldFix.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnionExprWithWrongFieldCountTest.kt
Labels: feature

#10281 RUN: Support `Rebuild ...` and `Clean` actions
  clion/src/main/kotlin/org/rust/clion/cargo/CargoCleanTaskRunner.kt
  clion/src/main/resources/org.rust.clion.xml
  src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
  src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
Labels: fix

#10285 ANN: Add E0226: Too many lifetime bounds on traitobj
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/RemovePolyBoundFix.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsTooManyLifetimeBoundsOnTraitObjectTest.kt
Labels: feature

#9375 INSP: Add unused_labels warning and fix
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedLabelsInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsUnusedLabels.html
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedLabelsInspectionTest.kt
Labels: feature

#10301 MACRO: parse reserved keywords as identifiers in macro matching
  src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt
  src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeParserTest.kt
Labels: fix
