Repository intellij-rust/intellij-rust, pull requests merged in 2023-02, with the labels that each got.

#10056 UI: provide icon for procedural macros
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
  src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/resources/icons/nodes/macroP.svg
Labels: feature

#9746 Don't suggest removing unused parameter in trait methods and proc macros
  src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
Labels: fix

#7489 DBG: add option to not step into stdlib sources
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSteppingSettingsConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsStepFilterSettings.kt
  debugger/src/main/resources/messages/RsDebuggerBundle.properties
Labels: feature, to be documented

#10066 ANN: Add support for E0131, E0197, E0203
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsMainWithGenericsTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsMultipleRelaxedBoundsTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnsafeInherentImplTest.kt
Labels: feature

#9965 DBG: Update MSVC pretty-printers and type name decorators to Rust 1.67
  .github/workflows/get-rust-versions.yml
  debugger/src/main/antlr/RsTypeName.g4
  debugger/src/main/kotlin/org/rust/debugger/lang/RsMSVCTypeNameDecoratorVisitor.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt
  debugger/src/test/kotlin/org/rust/debugger/lang/RsTypeNameParserTest.kt
  prettyPrinters/lldb_lookup.py
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/string.rs
Labels: fix

#9996 RES: fix namespace shadowing for a path in a type argument position
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/main/kotlin/org/rust/lang/core/resolve/RsPathResolveResult.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt
Labels: fix

#10090 IDE: use Boolean instead of a data class in debugger settings
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSteppingSettingsConfigurableUi.kt
  debugger/src/main/kotlin/org/rust/debugger/settings/RsStepFilterSettings.kt
Labels: fix

#10095 PERF: Don't expand cfg-disabled macro calls inside functions
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Labels: performance

#10098 CLEAN: simplify `RsTemplateBuilder` API
  src/main/kotlin/org/rust/ide/annotator/fixes/AddTypeFix.kt
  src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddAssocTypeBindingsFix.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt
  src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMustUseInspection.kt
  src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
  src/main/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
  src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt
  src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt
  src/main/kotlin/org/rust/ide/template/postfix/WrapTypePathPostfixTemplate.kt
  src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt
  src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt
  src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt
  src/main/kotlin/org/rust/ide/utils/template/RsTemplateBuilder.kt
  src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt
Labels: internal

#10103 RES: take into account attr macros for impl/trait members
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMembers.kt
  src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
Labels: fix

#10105 UI: Fix icon for abstract functions in new UI
  src/main/resources/icons/expui/nodes/abstractFunction.svg
  src/main/resources/icons/expui/nodes/abstractFunction_dark.svg
Labels: fix

#10071 COMP: Don't complete built-in attributes for qualified path
  src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
Labels: fix

#9864 HINT: Show type hints inside macro calls
  src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
  src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
  src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt
  src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsTestBase.kt
Labels: feature

#10120 GRAM: Support underscore expression
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/match_expr.txt
Labels: feature

#10118 ANN: Add support for E0571
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsBreakExprInNonLoopTest.kt
Labels: feature

#10139 Add `tokio_macros::test_rt` to list of hardcoded macros
  src/main/kotlin/org/rust/lang/core/psi/HardcodedProcMacroProperties.kt
Labels: fix

#10018 COMP: don't complete unstable stdlib items when on stable or beta
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsStability.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
Labels: feature

#10124 RUN: Fix parsing command line arguments
  src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt
  src/test/kotlin/org/rust/cargo/util/CargoArgsParserTest.kt
Labels: fix

#10171 ANN: Add support for E0224
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsAtLeastOneTraitForObjectTypeTest.kt
Labels: feature
