Repository intellij-rust/intellij-rust, pull requests merged in 2023-04, with the labels that each got.

#10322 Parse reserved keywords as identifier and annotate them
  src/main/grammars/RustLexer.flex
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/EscapeKeywordFix.kt
  src/main/kotlin/org/rust/ide/refactoring/RsNamesValidator.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsReservedKeywordAnnotatorTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
  src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
  src/test/resources/org/rust/lang/core/lexer/fixtures/keywords.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/reserved_keywords.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/reserved_keywords.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/reserved_keywords.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/reserved_keywords.txt
Labels: feature

#10308 INT: Fix handling associated types in `Implement members` intention
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Labels: fix

#10272 ANN: Support for E0183, fn* traits related experimental features errors
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitRef.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#10331 PERF: don't expand special macros in `RsLivenessInspection`
  src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt
Labels: performance

#10317 CARGO: fix building local crate index
  toml/src/main/kotlin/org/rust/toml/RsTomlBundle.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexUpdater.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexWaker.kt
  toml/src/main/resources/messages/RsTomlBundle.properties
  toml/src/main/resources/org.rust.toml.xml
  toml/src/test/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceTest.kt
Labels: fix

#10306 UI: Alphabetical sort for all files in project view
  src/main/kotlin/org/rust/ide/projectView/RsTreeStructureProvider.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#10338 REF: Fix inlining async function
  src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/test/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionTest2.kt
Labels: fix

#8842 ANN: Provide lint-based suppress quick-fixes for external linter annotations
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
  src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
Labels: feature

#8161 DBG: Allow loading NatVis files from Rust MSVC toolchain on Windows
  debugger/src/main/kotlin/org/rust/debugger/RustcNatvisFileProvider.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurator.kt
  debugger/src/main/resources/org.rust.debugger.xml
Labels: feature

#10315 REF: Support control flow in `Extract function` refactoring
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
  src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
  src/main/kotlin/org/rust/ide/surroundWith/utils.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLambdaExpr.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStmt.kt
  src/test/kotlin/org/rust/FileTree.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Labels: feature

#10146 Generate info about built-in attributes
  attributes-info/rustc_feature/src/lib.rs
  attributes-info/rustc_span/src/lib.rs
  attributes-info/src/builtin_attributes.rs
  attributes-info/src/compiler_features.rs
  attributes-info/src/formatter.rs
  attributes-info/src/main.rs
  src/main/kotlin/org/rust/lang/core/psi/BuiltinAttributes.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/resources/compiler-info/builtin-attributes.json
  src/test/kotlin/org/rust/lang/core/psi/RsAttributeTest.kt
Labels: internal

#9287 RUN: Enable Debugger, Profiler, Valgrind, Code Coverage, and Build/Test tool windows for `bench` command
  src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
  src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTestBase.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt
  src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
Labels: feature

#8147 UI: Render const generics in quick docs and inline hints
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt
  src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
  src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
  src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
  src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt
  src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
  src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Labels: fix

#9254 INSP: Fix `Needless lifetimes` inspection in case of async fn
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Labels: fix

#9948 Add support for binary crates installed manually
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
Labels: fix

#7917 ANN: Check builtin attributes even when there is proc macro in scope
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: fix

#10359 ANN: Add attribute errors support
  src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
Labels: feature

#7141 RES: Fix completion of derive proc macro in imports
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: fix

#10380 ANN: Fix showing error when assigning value to union field
  src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionErrorAnnotatorTest.kt
Labels: fix

#10385 Fix false-positive "Malformed feature attribute"
  src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt
Labels: fix

#10388 T: run tests with JUnit4
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
  src/test/kotlin/org/rust/ide/formatter/RsFormatterTestBase.kt
  src/test/kotlin/org/rust/lang/core/lexer/LexerTestCaseBase.kt
  src/test/kotlin/org/rust/lang/core/parser/RsParsingTestCaseBase.kt
Labels: internal

#8087 INSP: Add `#[repr(...)]` quick fix for E0308 error
  src/main/kotlin/org/rust/ide/fixes/ChangeReprAttributeFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReprAttributeFixTest.kt
Labels: feature

#10392 Fix #10391 Wrong message for attribute error
  src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
Labels: fix

#10393 Collect project settings statistics
  src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt
  src/main/resources/META-INF/rust-core.xml
Labels: internal

#10396 ANN: Reduce the error scope for E0130, E0561 and E0642 from value parameter to pattern
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInForeignFunctionTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInFunctionPointerTypeTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInFunctionWithoutBodyTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInFuntionPointerTypeTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Labels: fix

#10399 ANN: Add support for E0708 error
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLambdaExpr.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsAsyncNonMoveClosureWithParametersTest.kt
Labels: feature

#8908 Rewrite Rust settings and configurables
  src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
  src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsConfigurableBase.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsExternalLinterConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/settings/RsExternalLinterProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/RsProjectSettingsServiceBase.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustfmtProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/SerializationUtils.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
  src/main/kotlin/org/rust/ide/actions/ToggleExternalLinterOnTheFlyAction.kt
  src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
  src/main/kotlin/org/rust/ide/formatter/RustfmtFormattingService.kt
  src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
  src/main/kotlin/org/rust/ide/notifications/RsExternalLinterSlowRunNotifier.kt
  src/main/kotlin/org/rust/ide/notifications/RsExternalLinterTooltipService.kt
  src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt
  src/main/kotlin/org/rust/ide/status/RsExternalLinterWidget.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/cargo/project/RsExternalLinterProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/cargo/project/RsProjectSettingsServiceTestBase.kt
  src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/cargo/project/RustfmtProjectSettingsServiceTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
  src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Labels: fix

#9551 RUN: Allow to configure the channel and environment variables for external linters
  src/main/kotlin/org/rust/cargo/project/configurable/RsExternalLinterConfigurable.kt
  src/main/kotlin/org/rust/cargo/project/settings/RsExternalLinterProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/cargo/project/RsExternalLinterProjectSettingsServiceTest.kt
Labels: feature

#9219 UI: Adjust new Rust project generator to new project wizard in IDEA
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/ide/module/RsModuleBuilder.kt
  src/main/kotlin/org/rust/ide/newProject/RsNewProjectWizard.kt
  src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt
  src/main/kotlin/org/rust/ide/newProject/Utils.kt
  src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature, to be documented

#10406 ANN: Add support for E0536 error
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/ConvertMalformedCfgNotPatternToCfgAllPatternFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#10408 COMP: fix `.await` completion for async fn returned type
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt
Labels: fix

#10410 GRAM&MACRO: Parse and expand macros in attributes: `#[doc = foo!()]`
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
  src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt
Labels: fix
