Repository intellij-rust/intellij-rust, pull requests merged in 2023-05, with the labels that each got.

#10140 ANN: check `#[deprecated]` attr syntax: E0538, E0551, E0541
  src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt
Labels: feature

#10421 Fixes #10420 ANN: Use RsAnnotationHolder instead of AnnotationHolder in RsAttrErrorAnnotator
  src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt
Labels: fix

#10426 ANN: Add support for E0777 error
  src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt
Labels: feature

#10452 MIR: Setup MIR-dataflow framework
  src/main/kotlin/org/rust/lang/core/mir/Extensions.kt
  src/main/kotlin/org/rust/lang/core/mir/MirBuilder.kt
  src/main/kotlin/org/rust/lang/core/mir/WithIndex.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/FacadeBorrowck.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/MirBorrowCheckVisitor.kt
  src/main/kotlin/org/rust/lang/core/mir/building/BasicBlocksBuilder.kt
  src/main/kotlin/org/rust/lang/core/mir/building/LocalsBuilder.kt
  src/main/kotlin/org/rust/lang/core/mir/building/SourceScopesBuilder.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Analysis.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Direction.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Engine.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/GenKillAnalysis.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/ResultsVisitor.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/util.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/impls/MaybeUninitializedPlaces.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/move/DropFlagEffect.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/move/MovePaths.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirBasicBlock.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirBody.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocal.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocation.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirSourceScope.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirTerminator.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/impls/MirBasicBlockImpl.kt
  src/main/kotlin/org/rust/lang/core/mir/util/IndexAlloc.kt
  src/main/kotlin/org/rust/lang/core/mir/util/IndexKeyMap.kt
  src/main/kotlin/org/rust/lang/core/mir/util/LocationMap.kt
  src/test/kotlin/org/rust/lang/core/mir/MirPrettyPrinter.kt
  src/test/kotlin/org/rust/lang/core/mir/dataflow/impls/MaybeUninitializedPlacesTest.kt
  src/test/kotlin/org/rust/lang/core/mir/dataflow/impls/MirDataflowTestBase.kt
Labels: internal

#10453 MIR: Annotate E0381
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/FacadeBorrowck.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/MirBorrowCheckVisitor.kt
  src/main/kotlin/org/rust/lang/core/types/Extensions.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
Labels: internal

#10455 Drop support for 2022.3 platform
  .github/workflows/build-plugin.yml
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  .idea/runConfigurations/RunCLion.xml
  .idea/runConfigurations/RunIDEA.xml
  build.gradle.kts
  gradle-223.properties
  gradle.properties
  scripts/run_pretty_printer_tests.py
  src/223/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
  src/223/main/kotlin/org/rust/ide/lineMarkers/compatUtils.kt
  src/223/main/kotlin/org/rust/ide/refactoring/compatUtils.kt
  src/223/test/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/223/test/kotlin/org/rust/ide/hints/codeVision/RsCodeVisionTestCaseBase.kt
  src/231/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
  src/231/main/kotlin/org/rust/ide/lineMarkers/compatUtils.kt
  src/231/main/kotlin/org/rust/ide/refactoring/compatUtils.kt
  src/231/test/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/231/test/kotlin/org/rust/ide/hints/codeVision/RsCodeVisionTestCaseBase.kt
  src/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
  src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
  src/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilderBase.kt
  src/main/kotlin/org/rust/ide/refactoring/RsInPlaceVariableIntroducer.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
  src/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt
  src/test/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionTestCase.kt
Labels: internal

#10456 E0696 support: highlighting and completion improvement
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/RsConvertBlockToLoopFix.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsContinueLabelPointToBlockTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/RsConvertBlockToLoopFixTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: feature

#10457 MIR: Annotate E0382
  src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/FacadeBorrowck.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/MirBorrowCheckVisitor.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Labels: internal

#10459 COMP: complete `let` after `if` and `while`
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: feature

#10460 ANN: Add support for E0589 and E0693 errors
  src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/ConvertToUnsuffixedIntegerFix.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/main/kotlin/org/rust/stdext/Utils.kt
  src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt
Labels: feature

#10446 Collect project settings statistics: add `offline`
  src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt
Labels: fix

#10477 INSP: Implement `unnecessary cast` inspection
  src/main/kotlin/org/rust/ide/fixes/RemoveCastFix.kt
  src/main/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsUnnecessaryCast.html
  src/test/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspectionTest.kt
Labels: feature

#10480 COMP: Complete `for` after `impl` block
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsImplForCompletionTest.kt
Labels: feature

#10511 Disable test tool window on toolchain version >= 1.70-beta
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
Labels: fix

#10514 MIR: Initial support for E0505 using MIR framework
  src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/FacadeBorrowck.kt
  src/main/kotlin/org/rust/lang/core/mir/borrowck/MirBorrowCheckVisitor.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Analysis.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/BorrowSet.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Direction.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/GenKillAnalysis.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/ResultsVisitor.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Utils.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/impls/Borrows.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/impls/MaybeUninitializedPlaces.kt
  src/main/kotlin/org/rust/lang/core/mir/dataflow/move/MovePaths.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirAbstractDomain.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirBorrowKind.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocal.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocalInfo.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocation.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirPlace.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirProjectionElem.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirSpan.kt
  src/main/kotlin/org/rust/lang/core/mir/schemas/MirVisitor.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/lang/core/mir/MirPrettyPrinter.kt
  src/test/kotlin/org/rust/lang/core/mir/dataflow/impls/BorrowsTest.kt
Labels: feature
