Repository intellij-rust/intellij-rust, pull requests merged in 2023-06, with the labels that each got.

#10522 INSP: Fix false-positive `unnecessary cast` inspection for function types
  src/main/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspectionTest.kt
Labels: fix

#10524 FMT: Make `Run rustfmt` available as pre-commit action
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
  src/main/kotlin/org/rust/ide/actions/RustfmtCheckingFactory.kt
  src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
  src/main/kotlin/org/rust/ide/settings/RsVcsConfiguration.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
Labels: feature

#10525 Small refactoring to avoid making ambiguous ordering operation
  src/main/kotlin/org/rust/ide/presentation/PresentationInfo.kt
Labels: improvement

#10530 ANN: Support `return_position_impl_trait_in_trait` feature
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: feature

#10540 ANN: Fix regression for E0562 in return types
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
Labels: fix

#10541 FMT: Add filename in error message for pre-commit rustfmt
  src/main/kotlin/org/rust/ide/actions/RustfmtCheckinFactory.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
Labels: feature

#10546 COMP: Provide unresolved imported items as completion items
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLookupElement.kt
  src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionFromUnresolvedImportTest.kt
Labels: feature

#10550 INSP: Support `Unnecessary cast` inspection for function types
  src/main/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspectionTest.kt
Labels: feature

#10552 INSP: Highlight unused mut as weak warning. Reduce highlight scope
  src/main/kotlin/org/rust/ide/fixes/RemoveMutableFix.kt
  src/main/kotlin/org/rust/ide/inspections/RsVariableMutableInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/inspections/RsVariableMutableInspectionTest.kt
Labels: feature

#10553 Make sure tests catch regression for non-feature gated returns
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Labels: improvement

#10554 RUN: Pass `RUSTC_BOOTSTRAP` to the `cargo test` on 1.70.0+ stable if Test Tool Window is enabled
  src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
  src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestConsoleProperties.kt
  src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
  src/main/kotlin/org/rust/ide/statistics/CargoTestToolWindowUsagesCollector.kt
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
Labels: fix

#10556 INSP: Update `unused mut` description
  src/main/resources/inspectionDescriptions/RsVariableMutable.html
Labels: fix

#10561 Make parameter info available inside struct literal
  src/main/kotlin/org/rust/ide/hints/parameter/RsAsyncParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/hints/parameter/RsStructLiteralParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/typing/RsTypedHandler.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandlerTestBase.kt
  src/test/kotlin/org/rust/ide/hints/parameter/RsStructLiteralParameterInfoHandlerTest.kt
Labels: feature

#10563 Fix `self` parameter type handling in suggested refactoring
  src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringStateChanges.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt
Labels: fix

#10565 Add stub-only tests for function coercion
  src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Labels: improvement

#10569 Don't report unused mut in doctests
  src/main/kotlin/org/rust/ide/inspections/RsUnusedMutInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsUnusedMut.html
  src/test/kotlin/org/rust/ide/inspections/RsUnusedMutInspectionTest.kt
Labels: fix

#10570 Highlight missing format string inside `println`-like calls
  src/main/kotlin/org/rust/ide/annotator/format/RsFormatMacroAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/format/impl.kt
  src/main/kotlin/org/rust/ide/fixes/AddFormatStringFix.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Labels: feature

#10572 ANN: Unsupport `box` syntax
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/fixes/ReplaceBoxSyntaxFix.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorWithToolchainOverrideTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceBoxSyntaxFixTest.kt
Labels: feature

#10581 Support macros for unused `mut` inspection
  src/main/kotlin/org/rust/ide/inspections/RsUnusedMutInspection.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnusedMutInspectionTest.kt
Labels: feature

#10585 Make `RsUnusedMutInspection` lint inspection
  src/main/kotlin/org/rust/ide/inspections/RsUnusedMutInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnusedMutInspectionTest.kt
Labels: fix

#10586 Use TyFunctionDef for enum variants and tuples
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumVariant.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/kotlin/org/rust/lang/core/types/RsCallable.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
  src/main/kotlin/org/rust/lang/core/types/ty/FnSig.kt
  src/main/kotlin/org/rust/lang/core/types/ty/TyFunctionDef.kt
  src/test/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
  src/test/kotlin/org/rust/lang/core/type/RsAdjustmentTest.kt
Labels: fix

#10590 INSP: move `Unused mut modifier` and `Unnecessary cast` inspections to `Rust/Lint` group
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnnecessaryCastInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnnecessaryCastInspectionTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspectionTest.kt
Labels: fix

#10593 INSP: respect lint level by `Unused mut` inspection
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspectionTest.kt
Labels: fix

#10598 Support proc macro expander version 2
  src/main/kotlin/org/rust/lang/core/macros/proc/ProMacroExpanderVersion.kt
  src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
  src/main/kotlin/org/rust/lang/core/macros/tt/FlatTree.kt
  src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonTest.kt
  src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeParserTest.kt
Labels: fix

#10602 Highlight `compile_error!()` usage as an error
  src/main/kotlin/org/rust/ide/inspections/RsCompileErrorMacroInspection.kt
  src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt
  src/main/kotlin/org/rust/ide/inspections/RsWithMacrosInspectionVisitor.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroHighlightingUtil.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsCompileErrorMacro.html
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/ide/inspections/RsCompileErrorMacroInspectionTest.kt
  testData/test-proc-macros/src/lib.rs
Labels: feature

#10605 INSP: Implement `as` cast can be replaced with literal suffix inspection
  src/main/kotlin/org/rust/ide/fixes/ReplaceCastWithLiteralSuffixFix.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsReplaceCastWithSuffixInspection.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inspectionDescriptions/RsReplaceCastWithSuffix.html
  src/test/kotlin/org/rust/ide/inspections/fixes/ReplaceCastWithSuffixTest.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsReplaceCastWithSuffixInspectionTest.kt
Labels: feature

#10604 MACRO&ANN: Don't mishighlight cfg-disabled code in macro calls
  src/main/kotlin/org/rust/ide/annotator/AnnotatorBase.kt
  src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
  src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt
Labels: fix

#10607 Enable attribute procedural macro expansion by default
  src/main/resources-nightly/META-INF/experiments.xml
  src/main/resources-stable/META-INF/experiments.xml
  src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt
  src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt
Labels: feature

#10608 HINT: Show inlay hints for exclusive range patterns and expressions
  src/main/kotlin/org/rust/ide/hints/value/RsInlayValueHintsProvider.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/inlayProviders/rust.value.hints/exclusive_range_expressions.rs
  src/main/resources/inlayProviders/rust.value.hints/range_patterns.rs
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/ide/hints/value/RsInlayValueHintsProviderTest.kt
Labels: feature

#10613 Fix proc macro hygiene
  src/main/kotlin/org/rust/ide/utils/PsiInsertionPlace.kt
  src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
  src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
Labels: fix

#10619 INSP: Fix false positive unused `mut` inspection detection for some macros like `writeln!()`
  src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspectionTest.kt
Labels: fix

#10620 Detect E0061 for impl trait calls. Fixes #5681
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceWithStdMemDropFixTest.kt
Labels: fix

#10628 Remove timeout and add progress when fetching rustc version
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt
Labels: fix

#10631 COMP: Provide postfix completion items `.sublist` and `.slice` on indexable expressions that will complete into `[]`
  src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
  src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
  src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
  src/main/resources/postfixTemplates/SlicePostfixTemplate/after.rs.template
  src/main/resources/postfixTemplates/SlicePostfixTemplate/before.rs.template
  src/main/resources/postfixTemplates/SlicePostfixTemplate/description.html
  src/test/kotlin/org/rust/ide/template/postfix/SlicePostfixTemplateTest.kt
Labels: feature

#10634 COMP: Add `as` keyword completion
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
Labels: feature

#10635 COMP: Suggest keys inside TOML dependency
  src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
  toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
  toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
  toml/src/main/kotlin/org/rust/toml/completion/CratesIoCargoTomlDependencyCompletionProviders.kt
  toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProviders.kt
  toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
  toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependenciesCompletionTest.kt
  toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependencyKeysCompletionProviderTest.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlCompletionTestBase.kt
  toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt
Labels: feature

#10636 Complete enum variants inside patterns
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
  src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Labels: feature

#10637 COMP: Add completion for literal suffix
  src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
  src/main/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProvider.kt
  src/test/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProviderTest.kt
Labels: feature
