Repository intellij-rust/intellij-rust, pull requests merged in 2023-01, with the labels that each got.

#9747 Support "Create field" quick-fix for struct literals with `Self`
  src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFixTest.kt
Labels: fix

#9926 IDE: add version control author Code Vision
  src/223/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt
  src/main/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionContext.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature

#9928 ANN: update duplicate definition annotations
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsDuplicateDefinitionAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsInvalidReexportErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
Labels: fix

#9441 IDE: qualify unimportable elements in import after paste
  src/main/kotlin/org/rust/ide/inspections/fixes/QualifyPathFix.kt
  src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
  src/main/kotlin/org/rust/ide/typing/paste/RsImportCopyPasteProcessor.kt
  src/test/kotlin/org/rust/ide/typing/paste/RsAddImportOnCopyPasteTest.kt
Labels: feature

#9940 IDE: Support for Rust GitHub attr to generate web reference
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
  src/test/kotlin/org/rust/RustProjectDescriptors.kt
  src/test/kotlin/org/rust/lang/core/resolve/ref/RsLiteralWebReferenceProviderTest.kt
Labels: feature

#9927 IDE: add references Code Vision hint
  src/223/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
  src/223/main/resources/META-INF/platform-rust-core.xml
  src/223/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt
  src/223/test/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionTestCase.kt
  src/main/resources/messages/RsBundle.properties
Labels: feature

#9901 Don't pass `RUSTC_BOOTSTRAP` to rustc during build script evaluation
  native-helper/src/rustc_wrapper.rs
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
Labels: fix

#9971 Add BLOCK_EXPR to USELESS_PARENS_EXPR
  src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt
Labels: fix

#9977 UI: provide separate icons for constants and statics
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
  src/main/resources/icons/nodes/abstractConstant.svg
  src/main/resources/icons/nodes/constant.svg
  src/main/resources/icons/nodes/static.svg
Labels: feature

#9945 COMP: Suggest only methods from accessible traits
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
  src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
  src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
  src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Labels: fix

#9960 ACT: use background thread for Rust action `update`
  src/main/kotlin/org/rust/cargo/project/model/CargoProjectActionBase.kt
  src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandActionBase.kt
  src/main/kotlin/org/rust/ide/actions/CargoEditSettingsAction.kt
  src/main/kotlin/org/rust/ide/actions/RsBuildAction.kt
  src/main/kotlin/org/rust/ide/actions/RsToolsActionGroup.kt
  src/main/kotlin/org/rust/ide/actions/RustfmtCargoProjectAction.kt
  src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
  src/main/kotlin/org/rust/ide/actions/ShareInPlaygroundAction.kt
  src/main/kotlin/org/rust/ide/actions/ToggleExternalLinterOnTheFlyAction.kt
  src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
  src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt
  src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionGroup.kt
  src/main/kotlin/org/rust/ide/console/RunRustConsoleAction.kt
  src/main/kotlin/org/rust/ide/spelling/RsSpellCheckerGenerateDictionariesAction.kt
  src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
Labels: performance

#9842 INSP: Fix handling fn pointer in `Needless lifetimes`
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Labels: fix

#9850 INSP: Fix handling reference-like `self` parameter in `Needless lifetimes`
  src/main/kotlin/org/rust/ide/inspections/fixes/ElideLifetimesFix.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Labels: fix

#9914 INSP: properly process items by `Main function not found`
  src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
Labels: fix

#9802 UI: add marker to icons of unsafe items
  src/main/kotlin/org/rust/ide/icons/RsIcons.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
  src/main/resources/icons/unsafeMark.svg
Labels: feature

#9472 TY: fix default generic arg subst if it refers to another generic param
  src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
  src/main/kotlin/org/rust/lang/core/types/Substitution.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt
  src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Labels: fix

#9978 Optimize `Insert imports on paste`
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMovePathHelper.kt
  src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
  src/main/kotlin/org/rust/ide/typing/paste/RsImportCopyPasteProcessor.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Labels: performance

#9990 RES: Fix resolve of custom macros with same name as in prelude
  src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
  src/main/kotlin/org/rust/openapiext/psi.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Labels: fix

#9589 COMP: Fix jumping outside closing bracket/quote with Tab when typing
  src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
  src/test/kotlin/org/rust/lang/core/completion/RsCompletionTabOutTest.kt
Labels: fix

#9991 Drop support for 2022.2 platform
  .github/workflows/build-plugin.yml
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  .idea/runConfigurations/RunCLion.xml
  .idea/runConfigurations/RunIDEA.xml
  build.gradle.kts
  debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
  gradle-222.properties
  gradle.properties
  profiler/src/222/main/kotlin/org/rust/profiler/perf/compatUtils.kt
  profiler/src/223/main/kotlin/org/rust/profiler/perf/compatUtils.kt
  profiler/src/main/kotlin/org/rust/profiler/perf/RsPerfConfigurationExtension.kt
  src/222/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/222/main/kotlin/org/rust/ide/inspections/import/RsReferenceImporter.kt
  src/222/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt
  src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt
  src/222/main/resources/META-INF/platform-rust-core.xml
  src/222/test/kotlin/org/rust/ide/previewUtils.kt
  src/223/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/223/main/kotlin/org/rust/cargo/runconfig/target/compatUtils.kt
  src/223/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt
  src/223/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt
  src/223/main/resources/META-INF/platform-rust-core.xml
  src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
  src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
  src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
  src/main/kotlin/org/rust/cargo/runconfig/target/RsCommandLineSetup.kt
  src/main/kotlin/org/rust/cargo/runconfig/target/Utils.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchain.kt
  src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
  src/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
  src/main/kotlin/org/rust/ide/inspections/import/RsReferenceImporter.kt
  src/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilderBase.kt
  src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
  src/main/resources/META-INF/rust-core.xml
  src/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt
  src/test/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionTestCase.kt
  src/test/kotlin/org/rust/ide/previewUtils.kt
Labels: feature

#10002 Initial support for 2023.1 EAPs
  .github/workflows/build-plugin.yml
  .github/workflows/check.yml
  .github/workflows/rust-nightly.yml
  .github/workflows/rust-release.yml
  .idea/runConfigurations/RunCLion.xml
  .idea/runConfigurations/RunIDEA.xml
  build.gradle.kts
  gradle-223.properties
  gradle-231.properties
  gradle.properties
  src/223/main/kotlin/org/rust/ide/lineMarkers/compatUtils.kt
  src/223/main/kotlin/org/rust/ide/refactoring/compatUtils.kt
  src/223/test/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/223/test/kotlin/org/rust/ide/hints/codeVision/RsCodeVisionTestCaseBase.kt
  src/231/main/kotlin/org/rust/ide/lineMarkers/compatUtils.kt
  src/231/main/kotlin/org/rust/ide/refactoring/compatUtils.kt
  src/231/test/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
  src/231/test/kotlin/org/rust/ide/hints/codeVision/RsCodeVisionTestCaseBase.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
  src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
  src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
  src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
  src/main/kotlin/org/rust/cargo/toolchain/flavors/RsWinToolchainFlavor.kt
  src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
  src/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilderBase.kt
  src/main/kotlin/org/rust/ide/refactoring/RsInPlaceVariableIntroducer.kt
  src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
  src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
  src/main/kotlin/org/rust/lang/core/resolve2/ResolveCommonThreadPool.kt
  src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt
  src/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt
  src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
  src/test/kotlin/org/rust/ide/highlight/RsHighlightAwaitHandlerFactoryTest.kt
  src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
  src/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt
  src/test/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionTestCase.kt
  src/test/kotlin/org/rust/ide/refactoring/suggested/RsRenameSuggestedRefactoringTest.kt
  src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
  src/test/kotlin/org/rust/ide/search/RsUsageViewTreeTest.kt
  src/test/kotlin/org/rust/ide/utils.kt
  src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
  toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
  toml/src/test/kotlin/org/rust/toml/search/CargoTomlFindUsagesTest.kt
Labels: feature

#9974 LI: allow injecting languages into macro calls
  intelliLang/src/test/kotlin/org/rust/ide/intentions/InjectLanguageIntentionTest.kt
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/injected/RsMacroCallManipulator.kt
  src/main/kotlin/org/rust/ide/injected/RsStringLiteralManipulator.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
  src/main/resources/META-INF/rust-core.xml
Labels: feature, internal

#10014 Fix a UI freeze caused by navbar
  src/main/kotlin/org/rust/ide/structure/RsNavBarModelExtension.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
Labels: fix

#9988 PRJ: Trim template name and URL when creating new project
  src/main/kotlin/org/rust/ide/actions/ui/CargoNewCrateDialog.kt
  src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt
  src/main/kotlin/org/rust/openapiext/ui.kt
Labels: fix

#10021 INSP: Fix handling Fn trait with path lifetimes in `Needless lifetimes`
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Labels: fix

#9123 Allow to exclude specific paths from auto-import
  src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
  src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt
  src/main/kotlin/org/rust/ide/settings/RsPathsExcludeTable.kt
  src/main/kotlin/org/rust/ide/settings/RsProjectCodeInsightSettings.kt
  src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
  src/main/resources/META-INF/rust-core.xml
  src/main/resources/messages/RsBundle.properties
  src/test/kotlin/org/rust/RsTestBase.kt
  src/test/kotlin/org/rust/WithExcludedPaths.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
  src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
  src/test/kotlin/org/rust/lang/core/completion/RsTraitMethodCompletionTest.kt
Labels: feature, to be documented

#9987 INSP: Annotate missing lifetimes in function signature
  src/main/kotlin/org/rust/ide/inspections/RsWrongLifetimeParametersNumberInspection.kt
  src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt
  src/test/kotlin/org/rust/ide/inspections/RsWrongLifetimeParametersNumberTest.kt
Labels: feature

#10049 GRD: increase kotlin language level to 1.8
  build.gradle.kts
Labels: internal

#10050 Provide options for Rust line markers
  js/src/main/kotlin/org/rust/js/RsWasmBindgenLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsCrateDocLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsRecursiveCallLineMarkerProvider.kt
  src/main/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProvider.kt
  src/main/resources/messages/RsBundle.properties
  toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
Labels: feature

#8826 GRAM&ANN: Support new `where` clause location for associated types
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
  src/main/kotlin/org/rust/ide/hints/parameter/RsGenericParameterInfoHandler.kt
  src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
  src/main/kotlin/org/rust/ide/refactoring/functionSignature.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLifetimeParameter.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt
  src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
  src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/type.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/type.txt
  src/test/resources/org/rust/lang/core/parser/fixtures/partial/types.txt
Labels: feature

#9962 #9961: Support raw slice pointers in debugger pretty-printers
  debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt
  prettyPrinters/rust_types.py
  pretty_printers_tests/tests/slice.rs
Labels: feature

#9894 ANN: Add support for E0130, E0642
  src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
  src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
  src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInForeignFunctionTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInFunctionWithoutBodyTest.kt
  src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Labels: feature

#10057 GRAM&ANN: Parse and annotate `const_closures` feature
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
  src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
  src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLambdaExpr.kt
  src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.rs
  src/test/resources/org/rust/lang/core/parser/fixtures/complete/expr.txt
Labels: feature

#9972 PSI&PERF: use mixed AST where possible
  build.gradle.kts
  grammar-kit-fake-psi-deps/README.md
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsElementImpl.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldLookupImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsLabelDeclImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsLabelImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBindingImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBodyIdentMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBodyQuoteIdentMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroReferenceImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCallImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedElementImpl.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBindingImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsPatFieldFullImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsPatImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsStructLiteralFieldImplMixin.kt
  grammar-kit-fake-psi-deps/src/main/kotlin/org/rust/lang/core/psi/ext/RsStubbedElementImpl.kt
  settings.gradle.kts
  src/main/grammars/RustParser.bnf
  src/main/kotlin/org/rust/lang/core/psi/RsCompositeElementType.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldLookup.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLabel.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsLabelDecl.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBinding.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBodyIdent.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBodyQuoteIdent.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroReference.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedElement.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsPatFieldFull.kt
  src/main/kotlin/org/rust/lang/core/psi/ext/RsStructLiteralField.kt
Labels: performance, internal
